// Code generated by go-swagger; DO NOT EDIT.

package meters

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// NewCreateMeterParams creates a new CreateMeterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMeterParams() *CreateMeterParams {
	return NewCreateMeterParamsWithTimeout(cr.DefaultTimeout)
}

// NewCreateMeterParamsWithTimeout creates a new CreateMeterParams object
// with the ability to set a timeout on a request.
func NewCreateMeterParamsWithTimeout(timeout time.Duration) *CreateMeterParams {
	return &CreateMeterParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewCreateMeterParamsWithContext creates a new CreateMeterParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMeterParams].
func NewCreateMeterParamsWithContext(ctx context.Context) *CreateMeterParams {
	return &CreateMeterParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewCreateMeterParamsWithHTTPClient creates a new CreateMeterParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMeterParamsWithHTTPClient(client *http.Client) *CreateMeterParams {
	return &CreateMeterParams{
		HTTPClient: client,
	}
}

/*
CreateMeterParams contains all the parameters to send to the API endpoint

	for the create meter operation.

	Typically these are written to a http.Request.
*/
type CreateMeterParams struct {

	/* Request.

	   Meter
	*/
	Request *models.MeterCreateRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the create meter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMeterParams) WithDefaults() *CreateMeterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create meter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMeterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create meter params.
func (o *CreateMeterParams) WithTimeout(timeout time.Duration) *CreateMeterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create meter params.
func (o *CreateMeterParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the create meter params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMeterParams].
func (o *CreateMeterParams) WithContext(ctx context.Context) *CreateMeterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create meter params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMeterParams].
func (o *CreateMeterParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the create meter params.
func (o *CreateMeterParams) WithHTTPClient(client *http.Client) *CreateMeterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create meter params.
func (o *CreateMeterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create meter params.
func (o *CreateMeterParams) WithRequest(request *models.MeterCreateRequest) *CreateMeterParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create meter params.
func (o *CreateMeterParams) SetRequest(request *models.MeterCreateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *CreateMeterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
