// Code generated by go-swagger; DO NOT EDIT.

package meters

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// CreateMeterReader is a Reader for the CreateMeter structure.
type CreateMeterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMeterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateMeterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateMeterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateMeterConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateMeterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/meters] createMeter", response, response.Code())
	}
}

// NewCreateMeterCreated creates a CreateMeterCreated with default headers values
func NewCreateMeterCreated() *CreateMeterCreated {
	return &CreateMeterCreated{}
}

/*
CreateMeterCreated describes a response with status code 201, with default header values.

Created
*/
type CreateMeterCreated struct {
	Payload *models.Meter
}

// IsSuccess returns true when this create meter created response has a 2xx status code
func (o *CreateMeterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create meter created response has a 3xx status code
func (o *CreateMeterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create meter created response has a 4xx status code
func (o *CreateMeterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create meter created response has a 5xx status code
func (o *CreateMeterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create meter created response a status code equal to that given
func (o *CreateMeterCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create meter created response
func (o *CreateMeterCreated) Code() int {
	return 201
}

func (o *CreateMeterCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterCreated %s", 201, payload)
}

func (o *CreateMeterCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterCreated %s", 201, payload)
}

func (o *CreateMeterCreated) GetPayload() *models.Meter {
	return o.Payload
}

func (o *CreateMeterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Meter)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateMeterBadRequest creates a CreateMeterBadRequest with default headers values
func NewCreateMeterBadRequest() *CreateMeterBadRequest {
	return &CreateMeterBadRequest{}
}

/*
CreateMeterBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateMeterBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create meter bad request response has a 2xx status code
func (o *CreateMeterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create meter bad request response has a 3xx status code
func (o *CreateMeterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create meter bad request response has a 4xx status code
func (o *CreateMeterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create meter bad request response has a 5xx status code
func (o *CreateMeterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create meter bad request response a status code equal to that given
func (o *CreateMeterBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create meter bad request response
func (o *CreateMeterBadRequest) Code() int {
	return 400
}

func (o *CreateMeterBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterBadRequest %s", 400, payload)
}

func (o *CreateMeterBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterBadRequest %s", 400, payload)
}

func (o *CreateMeterBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateMeterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateMeterConflict creates a CreateMeterConflict with default headers values
func NewCreateMeterConflict() *CreateMeterConflict {
	return &CreateMeterConflict{}
}

/*
CreateMeterConflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateMeterConflict struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create meter conflict response has a 2xx status code
func (o *CreateMeterConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create meter conflict response has a 3xx status code
func (o *CreateMeterConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create meter conflict response has a 4xx status code
func (o *CreateMeterConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create meter conflict response has a 5xx status code
func (o *CreateMeterConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create meter conflict response a status code equal to that given
func (o *CreateMeterConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create meter conflict response
func (o *CreateMeterConflict) Code() int {
	return 409
}

func (o *CreateMeterConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterConflict %s", 409, payload)
}

func (o *CreateMeterConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterConflict %s", 409, payload)
}

func (o *CreateMeterConflict) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateMeterConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateMeterInternalServerError creates a CreateMeterInternalServerError with default headers values
func NewCreateMeterInternalServerError() *CreateMeterInternalServerError {
	return &CreateMeterInternalServerError{}
}

/*
CreateMeterInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateMeterInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create meter internal server error response has a 2xx status code
func (o *CreateMeterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create meter internal server error response has a 3xx status code
func (o *CreateMeterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create meter internal server error response has a 4xx status code
func (o *CreateMeterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create meter internal server error response has a 5xx status code
func (o *CreateMeterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create meter internal server error response a status code equal to that given
func (o *CreateMeterInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create meter internal server error response
func (o *CreateMeterInternalServerError) Code() int {
	return 500
}

func (o *CreateMeterInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterInternalServerError %s", 500, payload)
}

func (o *CreateMeterInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/meters][%d] createMeterInternalServerError %s", 500, payload)
}

func (o *CreateMeterInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateMeterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
