// Code generated by go-swagger; DO NOT EDIT.

package meters

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// ListMetersReader is a Reader for the ListMeters structure.
type ListMetersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMetersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListMetersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListMetersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListMetersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/meters] listMeters", response, response.Code())
	}
}

// NewListMetersOK creates a ListMetersOK with default headers values
func NewListMetersOK() *ListMetersOK {
	return &ListMetersOK{}
}

/*
ListMetersOK describes a response with status code 200, with default header values.

OK
*/
type ListMetersOK struct {
	Payload *models.MeterListResponse
}

// IsSuccess returns true when this list meters o k response has a 2xx status code
func (o *ListMetersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list meters o k response has a 3xx status code
func (o *ListMetersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list meters o k response has a 4xx status code
func (o *ListMetersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list meters o k response has a 5xx status code
func (o *ListMetersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list meters o k response a status code equal to that given
func (o *ListMetersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list meters o k response
func (o *ListMetersOK) Code() int {
	return 200
}

func (o *ListMetersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersOK %s", 200, payload)
}

func (o *ListMetersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersOK %s", 200, payload)
}

func (o *ListMetersOK) GetPayload() *models.MeterListResponse {
	return o.Payload
}

func (o *ListMetersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MeterListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListMetersBadRequest creates a ListMetersBadRequest with default headers values
func NewListMetersBadRequest() *ListMetersBadRequest {
	return &ListMetersBadRequest{}
}

/*
ListMetersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListMetersBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list meters bad request response has a 2xx status code
func (o *ListMetersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list meters bad request response has a 3xx status code
func (o *ListMetersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list meters bad request response has a 4xx status code
func (o *ListMetersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list meters bad request response has a 5xx status code
func (o *ListMetersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list meters bad request response a status code equal to that given
func (o *ListMetersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list meters bad request response
func (o *ListMetersBadRequest) Code() int {
	return 400
}

func (o *ListMetersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersBadRequest %s", 400, payload)
}

func (o *ListMetersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersBadRequest %s", 400, payload)
}

func (o *ListMetersBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListMetersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListMetersInternalServerError creates a ListMetersInternalServerError with default headers values
func NewListMetersInternalServerError() *ListMetersInternalServerError {
	return &ListMetersInternalServerError{}
}

/*
ListMetersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListMetersInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list meters internal server error response has a 2xx status code
func (o *ListMetersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list meters internal server error response has a 3xx status code
func (o *ListMetersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list meters internal server error response has a 4xx status code
func (o *ListMetersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list meters internal server error response has a 5xx status code
func (o *ListMetersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list meters internal server error response a status code equal to that given
func (o *ListMetersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list meters internal server error response
func (o *ListMetersInternalServerError) Code() int {
	return 500
}

func (o *ListMetersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersInternalServerError %s", 500, payload)
}

func (o *ListMetersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/meters][%d] listMetersInternalServerError %s", 500, payload)
}

func (o *ListMetersInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListMetersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
