// Code generated by go-swagger; DO NOT EDIT.

package meters

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewListMetersParams creates a new ListMetersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListMetersParams() *ListMetersParams {
	return NewListMetersParamsWithTimeout(cr.DefaultTimeout)
}

// NewListMetersParamsWithTimeout creates a new ListMetersParams object
// with the ability to set a timeout on a request.
func NewListMetersParamsWithTimeout(timeout time.Duration) *ListMetersParams {
	return &ListMetersParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListMetersParamsWithContext creates a new ListMetersParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMetersParams].
func NewListMetersParamsWithContext(ctx context.Context) *ListMetersParams {
	return &ListMetersParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListMetersParamsWithHTTPClient creates a new ListMetersParams object
// with the ability to set a custom HTTPClient for a request.
func NewListMetersParamsWithHTTPClient(client *http.Client) *ListMetersParams {
	return &ListMetersParams{
		HTTPClient: client,
	}
}

/*
ListMetersParams contains all the parameters to send to the API endpoint

	for the list meters operation.

	Typically these are written to a http.Request.
*/
type ListMetersParams struct {

	/* Cursor.

	   Pagination cursor
	*/
	Cursor *string

	/* Limit.

	   Page size
	*/
	Limit *int64

	/* Name.

	   Filter by meter name
	*/
	Name *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list meters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMetersParams) WithDefaults() *ListMetersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list meters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMetersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list meters params.
func (o *ListMetersParams) WithTimeout(timeout time.Duration) *ListMetersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list meters params.
func (o *ListMetersParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list meters params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMetersParams].
func (o *ListMetersParams) WithContext(ctx context.Context) *ListMetersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list meters params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListMetersParams].
func (o *ListMetersParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list meters params.
func (o *ListMetersParams) WithHTTPClient(client *http.Client) *ListMetersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list meters params.
func (o *ListMetersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the list meters params.
func (o *ListMetersParams) WithCursor(cursor *string) *ListMetersParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the list meters params.
func (o *ListMetersParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithLimit adds the limit to the list meters params.
func (o *ListMetersParams) WithLimit(limit *int64) *ListMetersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list meters params.
func (o *ListMetersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the list meters params.
func (o *ListMetersParams) WithName(name *string) *ListMetersParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list meters params.
func (o *ListMetersParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListMetersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
