version: '3'

includes:
  runtime:
    taskfile: ./taskfiles/runtime.yml
    flatten: true
  test:
    taskfile: ./taskfiles/test.yml
    flatten: true
  apps:
    taskfile: ./taskfiles/apps.yml
    flatten: true
  openapi:
    taskfile: ./taskfiles/openapi.yml
    flatten: true
  sdk:
    taskfile: ./taskfiles/sdk.yml
    flatten: true
  release:
    taskfile: ./taskfiles/release.yml
    flatten: true

tasks:
  default:
    desc: Run tests
    cmds:
      - task: test
