// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenSpanner.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The last_prune_run property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenSpanner.Models.SystemLastPruneRun? LastPruneRun { get; set; }
#nullable restore
#else
        public global::OpenSpanner.Models.SystemLastPruneRun LastPruneRun { get; set; }
#endif
        /// <summary>The meters property</summary>
        public int? Meters { get; set; }
        /// <summary>The prune_runs property</summary>
        public int? PruneRuns { get; set; }
        /// <summary>The usage_events property</summary>
        public int? UsageEvents { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.Models.SystemStats"/> and sets the default values.
        /// </summary>
        public SystemStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.Models.SystemStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OpenSpanner.Models.SystemStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenSpanner.Models.SystemStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "last_prune_run", n => { LastPruneRun = n.GetObjectValue<global::OpenSpanner.Models.SystemLastPruneRun>(global::OpenSpanner.Models.SystemLastPruneRun.CreateFromDiscriminatorValue); } },
                { "meters", n => { Meters = n.GetIntValue(); } },
                { "prune_runs", n => { PruneRuns = n.GetIntValue(); } },
                { "usage_events", n => { UsageEvents = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::OpenSpanner.Models.SystemLastPruneRun>("last_prune_run", LastPruneRun);
            writer.WriteIntValue("meters", Meters);
            writer.WriteIntValue("prune_runs", PruneRuns);
            writer.WriteIntValue("usage_events", UsageEvents);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
