// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenSpanner.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsageBucket : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aggregation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Aggregation { get; set; }
#nullable restore
#else
        public string Aggregation { get; set; }
#endif
        /// <summary>The bucket_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketSize { get; set; }
#nullable restore
#else
        public string BucketSize { get; set; }
#endif
        /// <summary>The bucket_start property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketStart { get; set; }
#nullable restore
#else
        public string BucketStart { get; set; }
#endif
        /// <summary>The group property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OpenSpanner.Models.UsageBucket_group? Group { get; set; }
#nullable restore
#else
        public global::OpenSpanner.Models.UsageBucket_group Group { get; set; }
#endif
        /// <summary>The meter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Meter { get; set; }
#nullable restore
#else
        public string Meter { get; set; }
#endif
        /// <summary>The quantity property</summary>
        public double? Quantity { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.Models.UsageBucket"/> and sets the default values.
        /// </summary>
        public UsageBucket()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.Models.UsageBucket"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OpenSpanner.Models.UsageBucket CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenSpanner.Models.UsageBucket();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregation", n => { Aggregation = n.GetStringValue(); } },
                { "bucket_size", n => { BucketSize = n.GetStringValue(); } },
                { "bucket_start", n => { BucketStart = n.GetStringValue(); } },
                { "group", n => { Group = n.GetObjectValue<global::OpenSpanner.Models.UsageBucket_group>(global::OpenSpanner.Models.UsageBucket_group.CreateFromDiscriminatorValue); } },
                { "meter", n => { Meter = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("aggregation", Aggregation);
            writer.WriteStringValue("bucket_size", BucketSize);
            writer.WriteStringValue("bucket_start", BucketStart);
            writer.WriteObjectValue<global::OpenSpanner.Models.UsageBucket_group>("group", Group);
            writer.WriteStringValue("meter", Meter);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("unit", Unit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
