// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// EntitlementCheckRequest EntitlementCheckRequest
//
// swagger:model EntitlementCheckRequest
type EntitlementCheckRequest struct {

	// meter
	Meter string `json:"meter,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this entitlement check request
func (m *EntitlementCheckRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this entitlement check request based on context it is used
func (m *EntitlementCheckRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntitlementCheckRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntitlementCheckRequest) UnmarshalBinary(b []byte) error {
	var res EntitlementCheckRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
