// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// InternalMeteringAdaptersHTTPUsageEventSearchRequest internal metering adapters http usage event search request
//
// swagger:model internal_metering_adapters_http_usage.EventSearchRequest
type InternalMeteringAdaptersHTTPUsageEventSearchRequest struct {

	// cursor
	Cursor string `json:"cursor,omitempty"`

	// filter
	Filter *InternalMeteringAdaptersHTTPUsageFilterRequest `json:"filter,omitempty"`

	// from
	From string `json:"from,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// meter
	Meter string `json:"meter,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this internal metering adapters http usage event search request
func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) validateFilter(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Filter) { // not required
		return nil
	}

	if m.Filter != nil {
		if err := m.Filter.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filter")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this internal metering adapters http usage event search request based on the context it is used
func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) contextValidateFilter(ctx context.Context, formats strfmt.Registry) error {

	if m.Filter != nil {

		if typeutils.IsZero(m.Filter) { // not required
			return nil
		}

		if err := m.Filter.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("filter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("filter")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalMeteringAdaptersHTTPUsageEventSearchRequest) UnmarshalBinary(b []byte) error {
	var res InternalMeteringAdaptersHTTPUsageEventSearchRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
