// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// MeterCreateRequest MeterCreateRequest
//
// swagger:model MeterCreateRequest
type MeterCreateRequest struct {

	// aggregation
	Aggregation string `json:"aggregation,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// dimensions
	Dimensions []*MeterDimensionRequest `json:"dimensions"`

	// event retention days
	EventRetentionDays int64 `json:"event_retention_days,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`
}

// Validate validates this meter create request
func (m *MeterCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDimensions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MeterCreateRequest) validateDimensions(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Dimensions) { // not required
		return nil
	}

	for i := 0; i < len(m.Dimensions); i++ {
		if typeutils.IsZero(m.Dimensions[i]) { // not required
			continue
		}

		if m.Dimensions[i] != nil {
			if err := m.Dimensions[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("dimensions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("dimensions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this meter create request based on the context it is used
func (m *MeterCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDimensions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MeterCreateRequest) contextValidateDimensions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Dimensions); i++ {

		if m.Dimensions[i] != nil {

			if typeutils.IsZero(m.Dimensions[i]) { // not required
				return nil
			}

			if err := m.Dimensions[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("dimensions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("dimensions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MeterCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MeterCreateRequest) UnmarshalBinary(b []byte) error {
	var res MeterCreateRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
