// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// PlanLimit PlanLimit
//
// swagger:model PlanLimit
type PlanLimit struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// limit
	Limit float64 `json:"limit,omitempty"`

	// meter
	Meter string `json:"meter,omitempty"`

	// period
	Period string `json:"period,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// warning percent
	WarningPercent float64 `json:"warning_percent,omitempty"`
}

// Validate validates this plan limit
func (m *PlanLimit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plan limit based on context it is used
func (m *PlanLimit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlanLimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanLimit) UnmarshalBinary(b []byte) error {
	var res PlanLimit
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
