// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SubjectStats SubjectStats
//
// swagger:model SubjectStats
type SubjectStats struct {

	// last event at
	LastEventAt string `json:"last_event_at,omitempty"`

	// meters
	Meters int64 `json:"meters,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// usage events
	UsageEvents int64 `json:"usage_events,omitempty"`
}

// Validate validates this subject stats
func (m *SubjectStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this subject stats based on context it is used
func (m *SubjectStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubjectStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubjectStats) UnmarshalBinary(b []byte) error {
	var res SubjectStats
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
