// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SystemLastPruneRun SystemLastPruneRun
//
// swagger:model SystemLastPruneRun
type SystemLastPruneRun struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// deleted
	Deleted int64 `json:"deleted,omitempty"`

	// dry run
	DryRun bool `json:"dry_run,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this system last prune run
func (m *SystemLastPruneRun) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this system last prune run based on context it is used
func (m *SystemLastPruneRun) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SystemLastPruneRun) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemLastPruneRun) UnmarshalBinary(b []byte) error {
	var res SystemLastPruneRun
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
