// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UsageDimensionValue UsageDimensionValue
//
// swagger:model UsageDimensionValue
type UsageDimensionValue struct {

	// events
	Events int64 `json:"events,omitempty"`

	// field
	Field string `json:"field,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this usage dimension value
func (m *UsageDimensionValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this usage dimension value based on context it is used
func (m *UsageDimensionValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsageDimensionValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsageDimensionValue) UnmarshalBinary(b []byte) error {
	var res UsageDimensionValue
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
