// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UsageCreateRequest UsageCreateRequest
//
// swagger:model UsageCreateRequest
type UsageCreateRequest struct {

	// IdempotencyKey replays the original accepted event when reused.
	IdempotencyKey string `json:"idempotency_key,omitempty"`

	// metadata
	Metadata map[string]any `json:"metadata,omitempty"`

	// meter
	Meter string `json:"meter,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this usage create request
func (m *UsageCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this usage create request based on context it is used
func (m *UsageCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsageCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsageCreateRequest) UnmarshalBinary(b []byte) error {
	var res UsageCreateRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
