// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UsageBreakdown UsageBreakdown
//
// swagger:model UsageBreakdown
type UsageBreakdown struct {

	// aggregation
	Aggregation string `json:"aggregation,omitempty"`

	// events
	Events int64 `json:"events,omitempty"`

	// field
	Field string `json:"field,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this usage breakdown
func (m *UsageBreakdown) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this usage breakdown based on context it is used
func (m *UsageBreakdown) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsageBreakdown) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsageBreakdown) UnmarshalBinary(b []byte) error {
	var res UsageBreakdown
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
