// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: open_spanner/v1/usage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsageService_CreateUsage_FullMethodName     = "/open_spanner.v1.UsageService/CreateUsage"
	UsageService_CreateUsageBulk_FullMethodName = "/open_spanner.v1.UsageService/CreateUsageBulk"
	UsageService_StreamUsage_FullMethodName     = "/open_spanner.v1.UsageService/StreamUsage"
)

// UsageServiceClient is the client API for UsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsageServiceClient interface {
	CreateUsage(ctx context.Context, in *CreateUsageRequest, opts ...grpc.CallOption) (*CreateUsageResponse, error)
	CreateUsageBulk(ctx context.Context, in *CreateUsageBulkRequest, opts ...grpc.CallOption) (*CreateUsageBulkResponse, error)
	StreamUsage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamUsageRequest, StreamUsageResponse], error)
}

type usageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageServiceClient(cc grpc.ClientConnInterface) UsageServiceClient {
	return &usageServiceClient{cc}
}

func (c *usageServiceClient) CreateUsage(ctx context.Context, in *CreateUsageRequest, opts ...grpc.CallOption) (*CreateUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUsageResponse)
	err := c.cc.Invoke(ctx, UsageService_CreateUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) CreateUsageBulk(ctx context.Context, in *CreateUsageBulkRequest, opts ...grpc.CallOption) (*CreateUsageBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUsageBulkResponse)
	err := c.cc.Invoke(ctx, UsageService_CreateUsageBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) StreamUsage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamUsageRequest, StreamUsageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UsageService_ServiceDesc.Streams[0], UsageService_StreamUsage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUsageRequest, StreamUsageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UsageService_StreamUsageClient = grpc.ClientStreamingClient[StreamUsageRequest, StreamUsageResponse]

// UsageServiceServer is the server API for UsageService service.
// All implementations should embed UnimplementedUsageServiceServer
// for forward compatibility.
type UsageServiceServer interface {
	CreateUsage(context.Context, *CreateUsageRequest) (*CreateUsageResponse, error)
	CreateUsageBulk(context.Context, *CreateUsageBulkRequest) (*CreateUsageBulkResponse, error)
	StreamUsage(grpc.ClientStreamingServer[StreamUsageRequest, StreamUsageResponse]) error
}

// UnimplementedUsageServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsageServiceServer struct{}

func (UnimplementedUsageServiceServer) CreateUsage(context.Context, *CreateUsageRequest) (*CreateUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUsage not implemented")
}
func (UnimplementedUsageServiceServer) CreateUsageBulk(context.Context, *CreateUsageBulkRequest) (*CreateUsageBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUsageBulk not implemented")
}
func (UnimplementedUsageServiceServer) StreamUsage(grpc.ClientStreamingServer[StreamUsageRequest, StreamUsageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUsage not implemented")
}
func (UnimplementedUsageServiceServer) testEmbeddedByValue() {}

// UnsafeUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageServiceServer will
// result in compilation errors.
type UnsafeUsageServiceServer interface {
	mustEmbedUnimplementedUsageServiceServer()
}

func RegisterUsageServiceServer(s grpc.ServiceRegistrar, srv UsageServiceServer) {
	// If the following call pancis, it indicates UnimplementedUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsageService_ServiceDesc, srv)
}

func _UsageService_CreateUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).CreateUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_CreateUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).CreateUsage(ctx, req.(*CreateUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_CreateUsageBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUsageBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).CreateUsageBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_CreateUsageBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).CreateUsageBulk(ctx, req.(*CreateUsageBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_StreamUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UsageServiceServer).StreamUsage(&grpc.GenericServerStream[StreamUsageRequest, StreamUsageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UsageService_StreamUsageServer = grpc.ClientStreamingServer[StreamUsageRequest, StreamUsageResponse]

// UsageService_ServiceDesc is the grpc.ServiceDesc for UsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "open_spanner.v1.UsageService",
	HandlerType: (*UsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUsage",
			Handler:    _UsageService_CreateUsage_Handler,
		},
		{
			MethodName: "CreateUsageBulk",
			Handler:    _UsageService_CreateUsageBulk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUsage",
			Handler:       _UsageService_StreamUsage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "open_spanner/v1/usage.proto",
}
