// Code generated by go-swagger; DO NOT EDIT.

package entitlements

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// ConsumeEntitlementReader is a Reader for the ConsumeEntitlement structure.
type ConsumeEntitlementReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConsumeEntitlementReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewConsumeEntitlementCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewConsumeEntitlementBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewConsumeEntitlementForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewConsumeEntitlementTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewConsumeEntitlementInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/entitlements/consume] consumeEntitlement", response, response.Code())
	}
}

// NewConsumeEntitlementCreated creates a ConsumeEntitlementCreated with default headers values
func NewConsumeEntitlementCreated() *ConsumeEntitlementCreated {
	return &ConsumeEntitlementCreated{}
}

/*
ConsumeEntitlementCreated describes a response with status code 201, with default header values.

Created
*/
type ConsumeEntitlementCreated struct {
	Payload *models.EntitlementConsumeResponse
}

// IsSuccess returns true when this consume entitlement created response has a 2xx status code
func (o *ConsumeEntitlementCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this consume entitlement created response has a 3xx status code
func (o *ConsumeEntitlementCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this consume entitlement created response has a 4xx status code
func (o *ConsumeEntitlementCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this consume entitlement created response has a 5xx status code
func (o *ConsumeEntitlementCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this consume entitlement created response a status code equal to that given
func (o *ConsumeEntitlementCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the consume entitlement created response
func (o *ConsumeEntitlementCreated) Code() int {
	return 201
}

func (o *ConsumeEntitlementCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementCreated %s", 201, payload)
}

func (o *ConsumeEntitlementCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementCreated %s", 201, payload)
}

func (o *ConsumeEntitlementCreated) GetPayload() *models.EntitlementConsumeResponse {
	return o.Payload
}

func (o *ConsumeEntitlementCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntitlementConsumeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewConsumeEntitlementBadRequest creates a ConsumeEntitlementBadRequest with default headers values
func NewConsumeEntitlementBadRequest() *ConsumeEntitlementBadRequest {
	return &ConsumeEntitlementBadRequest{}
}

/*
ConsumeEntitlementBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ConsumeEntitlementBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this consume entitlement bad request response has a 2xx status code
func (o *ConsumeEntitlementBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this consume entitlement bad request response has a 3xx status code
func (o *ConsumeEntitlementBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this consume entitlement bad request response has a 4xx status code
func (o *ConsumeEntitlementBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this consume entitlement bad request response has a 5xx status code
func (o *ConsumeEntitlementBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this consume entitlement bad request response a status code equal to that given
func (o *ConsumeEntitlementBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the consume entitlement bad request response
func (o *ConsumeEntitlementBadRequest) Code() int {
	return 400
}

func (o *ConsumeEntitlementBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementBadRequest %s", 400, payload)
}

func (o *ConsumeEntitlementBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementBadRequest %s", 400, payload)
}

func (o *ConsumeEntitlementBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConsumeEntitlementBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewConsumeEntitlementForbidden creates a ConsumeEntitlementForbidden with default headers values
func NewConsumeEntitlementForbidden() *ConsumeEntitlementForbidden {
	return &ConsumeEntitlementForbidden{}
}

/*
ConsumeEntitlementForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ConsumeEntitlementForbidden struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this consume entitlement forbidden response has a 2xx status code
func (o *ConsumeEntitlementForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this consume entitlement forbidden response has a 3xx status code
func (o *ConsumeEntitlementForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this consume entitlement forbidden response has a 4xx status code
func (o *ConsumeEntitlementForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this consume entitlement forbidden response has a 5xx status code
func (o *ConsumeEntitlementForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this consume entitlement forbidden response a status code equal to that given
func (o *ConsumeEntitlementForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the consume entitlement forbidden response
func (o *ConsumeEntitlementForbidden) Code() int {
	return 403
}

func (o *ConsumeEntitlementForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementForbidden %s", 403, payload)
}

func (o *ConsumeEntitlementForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementForbidden %s", 403, payload)
}

func (o *ConsumeEntitlementForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConsumeEntitlementForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewConsumeEntitlementTooManyRequests creates a ConsumeEntitlementTooManyRequests with default headers values
func NewConsumeEntitlementTooManyRequests() *ConsumeEntitlementTooManyRequests {
	return &ConsumeEntitlementTooManyRequests{}
}

/*
ConsumeEntitlementTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type ConsumeEntitlementTooManyRequests struct {
	Payload *models.EntitlementConsumeResponse
}

// IsSuccess returns true when this consume entitlement too many requests response has a 2xx status code
func (o *ConsumeEntitlementTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this consume entitlement too many requests response has a 3xx status code
func (o *ConsumeEntitlementTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this consume entitlement too many requests response has a 4xx status code
func (o *ConsumeEntitlementTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this consume entitlement too many requests response has a 5xx status code
func (o *ConsumeEntitlementTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this consume entitlement too many requests response a status code equal to that given
func (o *ConsumeEntitlementTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the consume entitlement too many requests response
func (o *ConsumeEntitlementTooManyRequests) Code() int {
	return 429
}

func (o *ConsumeEntitlementTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementTooManyRequests %s", 429, payload)
}

func (o *ConsumeEntitlementTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementTooManyRequests %s", 429, payload)
}

func (o *ConsumeEntitlementTooManyRequests) GetPayload() *models.EntitlementConsumeResponse {
	return o.Payload
}

func (o *ConsumeEntitlementTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntitlementConsumeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewConsumeEntitlementInternalServerError creates a ConsumeEntitlementInternalServerError with default headers values
func NewConsumeEntitlementInternalServerError() *ConsumeEntitlementInternalServerError {
	return &ConsumeEntitlementInternalServerError{}
}

/*
ConsumeEntitlementInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ConsumeEntitlementInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this consume entitlement internal server error response has a 2xx status code
func (o *ConsumeEntitlementInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this consume entitlement internal server error response has a 3xx status code
func (o *ConsumeEntitlementInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this consume entitlement internal server error response has a 4xx status code
func (o *ConsumeEntitlementInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this consume entitlement internal server error response has a 5xx status code
func (o *ConsumeEntitlementInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this consume entitlement internal server error response a status code equal to that given
func (o *ConsumeEntitlementInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the consume entitlement internal server error response
func (o *ConsumeEntitlementInternalServerError) Code() int {
	return 500
}

func (o *ConsumeEntitlementInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementInternalServerError %s", 500, payload)
}

func (o *ConsumeEntitlementInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/entitlements/consume][%d] consumeEntitlementInternalServerError %s", 500, payload)
}

func (o *ConsumeEntitlementInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConsumeEntitlementInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
