// Code generated by go-swagger; DO NOT EDIT.

package entitlements

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// NewConsumeEntitlementParams creates a new ConsumeEntitlementParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConsumeEntitlementParams() *ConsumeEntitlementParams {
	return NewConsumeEntitlementParamsWithTimeout(cr.DefaultTimeout)
}

// NewConsumeEntitlementParamsWithTimeout creates a new ConsumeEntitlementParams object
// with the ability to set a timeout on a request.
func NewConsumeEntitlementParamsWithTimeout(timeout time.Duration) *ConsumeEntitlementParams {
	return &ConsumeEntitlementParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewConsumeEntitlementParamsWithContext creates a new ConsumeEntitlementParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ConsumeEntitlementParams].
func NewConsumeEntitlementParamsWithContext(ctx context.Context) *ConsumeEntitlementParams {
	return &ConsumeEntitlementParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewConsumeEntitlementParamsWithHTTPClient creates a new ConsumeEntitlementParams object
// with the ability to set a custom HTTPClient for a request.
func NewConsumeEntitlementParamsWithHTTPClient(client *http.Client) *ConsumeEntitlementParams {
	return &ConsumeEntitlementParams{
		HTTPClient: client,
	}
}

/*
ConsumeEntitlementParams contains all the parameters to send to the API endpoint

	for the consume entitlement operation.

	Typically these are written to a http.Request.
*/
type ConsumeEntitlementParams struct {

	/* Request.

	   Consumption event
	*/
	Request *models.EntitlementConsumeRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the consume entitlement params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConsumeEntitlementParams) WithDefaults() *ConsumeEntitlementParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the consume entitlement params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConsumeEntitlementParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the consume entitlement params.
func (o *ConsumeEntitlementParams) WithTimeout(timeout time.Duration) *ConsumeEntitlementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the consume entitlement params.
func (o *ConsumeEntitlementParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the consume entitlement params.
//
// Deprecated: use the operation call with context to pass the context instead of [ConsumeEntitlementParams].
func (o *ConsumeEntitlementParams) WithContext(ctx context.Context) *ConsumeEntitlementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the consume entitlement params.
//
// Deprecated: use the operation call with context to pass the context instead of [ConsumeEntitlementParams].
func (o *ConsumeEntitlementParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the consume entitlement params.
func (o *ConsumeEntitlementParams) WithHTTPClient(client *http.Client) *ConsumeEntitlementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the consume entitlement params.
func (o *ConsumeEntitlementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the consume entitlement params.
func (o *ConsumeEntitlementParams) WithRequest(request *models.EntitlementConsumeRequest) *ConsumeEntitlementParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the consume entitlement params.
func (o *ConsumeEntitlementParams) SetRequest(request *models.EntitlementConsumeRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ConsumeEntitlementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
