// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM auth_users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM auth_api_keys
WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM auth_sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const findAPIKeyByTokenHash = `-- name: FindAPIKeyByTokenHash :one
SELECT id, user_id, name, token_hash, prefix, scopes, allowed_meters, expires_at, revoked_at, created_at, last_used_at
FROM auth_api_keys
WHERE token_hash = ?
`

type FindAPIKeyByTokenHashRow struct {
	ID            string
	UserID        string
	Name          string
	TokenHash     string
	Prefix        string
	Scopes        string
	AllowedMeters string
	ExpiresAt     sql.NullString
	RevokedAt     sql.NullString
	CreatedAt     string
	LastUsedAt    sql.NullString
}

func (q *Queries) FindAPIKeyByTokenHash(ctx context.Context, tokenHash string) (FindAPIKeyByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, findAPIKeyByTokenHash, tokenHash)
	var i FindAPIKeyByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.AllowedMeters,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const findIdentityByProviderSubject = `-- name: FindIdentityByProviderSubject :one
SELECT id, user_id, provider, subject, email, email_verified, created_at, updated_at
FROM auth_identities
WHERE provider = ? AND subject = ?
`

type FindIdentityByProviderSubjectParams struct {
	Provider string
	Subject  string
}

func (q *Queries) FindIdentityByProviderSubject(ctx context.Context, arg FindIdentityByProviderSubjectParams) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, findIdentityByProviderSubject, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, user_id, token_hash, kind, expires_at, created_at
FROM auth_sessions
WHERE token_hash = ? AND kind = ? AND expires_at > ?
`

type FindSessionByTokenHashParams struct {
	TokenHash string
	Kind      string
	ExpiresAt string
}

type FindSessionByTokenHashRow struct {
	ID        string
	UserID    string
	TokenHash string
	Kind      string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) FindSessionByTokenHash(ctx context.Context, arg FindSessionByTokenHashParams) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, findSessionByTokenHash, arg.TokenHash, arg.Kind, arg.ExpiresAt)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Kind,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, created_at
FROM auth_users
WHERE email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password_hash, created_at
FROM auth_users
WHERE id = ?
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, token_hash, prefix, scopes, allowed_meters, expires_at, revoked_at, created_at, last_used_at
FROM auth_api_keys
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

type ListAPIKeysRow struct {
	ID            string
	UserID        string
	Name          string
	TokenHash     string
	Prefix        string
	Scopes        string
	AllowedMeters string
	ExpiresAt     sql.NullString
	RevokedAt     sql.NullString
	CreatedAt     string
	LastUsedAt    sql.NullString
}

func (q *Queries) ListAPIKeys(ctx context.Context, userID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.AllowedMeters,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAPIKey = `-- name: SaveAPIKey :exec
INSERT INTO auth_api_keys (id, user_id, name, token_hash, prefix, scopes, allowed_meters, expires_at, revoked_at, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SaveAPIKeyParams struct {
	ID            string
	UserID        string
	Name          string
	TokenHash     string
	Prefix        string
	Scopes        string
	AllowedMeters string
	ExpiresAt     sql.NullString
	RevokedAt     sql.NullString
	CreatedAt     string
	LastUsedAt    sql.NullString
}

func (q *Queries) SaveAPIKey(ctx context.Context, arg SaveAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, saveAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.Scopes,
		arg.AllowedMeters,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const saveIdentity = `-- name: SaveIdentity :exec
INSERT INTO auth_identities (id, user_id, provider, subject, email, email_verified, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type SaveIdentityParams struct {
	ID            string
	UserID        string
	Provider      string
	Subject       string
	Email         string
	EmailVerified int64
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) SaveIdentity(ctx context.Context, arg SaveIdentityParams) error {
	_, err := q.db.ExecContext(ctx, saveIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO auth_sessions (id, user_id, token_hash, kind, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type SaveSessionParams struct {
	ID        string
	UserID    string
	TokenHash string
	Kind      string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Kind,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO auth_users (id, email, password_hash, created_at)
VALUES (?, ?, ?, ?)
`

type SaveUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.ExecContext(ctx, saveUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE auth_api_keys
SET last_used_at = ?
WHERE id = ?
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullString
	ID         string
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
