// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumption_decisions.sql

package sqlitedb

import (
	"context"
)

const findConsumptionDecision = `-- name: FindConsumptionDecision :one
SELECT response
FROM consumption_decisions
WHERE workspace_id = ?1
	AND idempotency_key = ?2
`

type FindConsumptionDecisionParams struct {
	WorkspaceID    string
	IdempotencyKey string
}

func (q *Queries) FindConsumptionDecision(ctx context.Context, arg FindConsumptionDecisionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findConsumptionDecision, arg.WorkspaceID, arg.IdempotencyKey)
	var response string
	err := row.Scan(&response)
	return response, err
}

const saveConsumptionDecision = `-- name: SaveConsumptionDecision :execrows
INSERT INTO consumption_decisions (workspace_id, idempotency_key, response, created_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT DO NOTHING
`

type SaveConsumptionDecisionParams struct {
	WorkspaceID    string
	IdempotencyKey string
	Response       string
	CreatedAt      string
}

func (q *Queries) SaveConsumptionDecision(ctx context.Context, arg SaveConsumptionDecisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveConsumptionDecision,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.Response,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
