// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meters.sql

package sqlitedb

import (
	"context"
)

const countMeters = `-- name: CountMeters :one
SELECT COUNT(*)
FROM meters
WHERE workspace_id = ?1
`

func (q *Queries) CountMeters(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMeters, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageEventsForMeter = `-- name: CountUsageEventsForMeter :one
SELECT COUNT(*)
FROM usage_events
WHERE workspace_id = ?1
	AND meter_name = ?2
`

type CountUsageEventsForMeterParams struct {
	WorkspaceID string
	MeterName   string
}

func (q *Queries) CountUsageEventsForMeter(ctx context.Context, arg CountUsageEventsForMeterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsageEventsForMeter, arg.WorkspaceID, arg.MeterName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMeter = `-- name: DeleteMeter :exec
DELETE FROM meters
WHERE workspace_id = ?1
	AND id = ?2
`

type DeleteMeterParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteMeter(ctx context.Context, arg DeleteMeterParams) error {
	_, err := q.db.ExecContext(ctx, deleteMeter, arg.WorkspaceID, arg.ID)
	return err
}

const listMeters = `-- name: ListMeters :many
SELECT id, name, description, unit, aggregation, dimensions, event_retention_days, created_at
FROM meters
WHERE workspace_id = ?1
	AND (?2 IS NULL OR id = ?2)
	AND (?3 IS NULL OR name = ?3)
	AND (?4 IS NULL OR name > ?4)
ORDER BY name
LIMIT ?5
`

type ListMetersParams struct {
	WorkspaceID string
	ID          interface{}
	Name        interface{}
	Cursor      interface{}
	Limit       int64
}

type ListMetersRow struct {
	ID                 string
	Name               string
	Description        string
	Unit               string
	Aggregation        string
	Dimensions         string
	EventRetentionDays int64
	CreatedAt          string
}

func (q *Queries) ListMeters(ctx context.Context, arg ListMetersParams) ([]ListMetersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeters,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetersRow{}
	for rows.Next() {
		var i ListMetersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Aggregation,
			&i.Dimensions,
			&i.EventRetentionDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMeter = `-- name: SaveMeter :exec
INSERT INTO meters (id, workspace_id, name, description, unit, aggregation, dimensions, event_retention_days, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
	description = excluded.description,
	unit = excluded.unit,
	aggregation = excluded.aggregation,
	dimensions = excluded.dimensions,
	event_retention_days = excluded.event_retention_days
`

type SaveMeterParams struct {
	ID                 string
	WorkspaceID        string
	Name               string
	Description        string
	Unit               string
	Aggregation        string
	Dimensions         string
	EventRetentionDays int64
	CreatedAt          string
}

func (q *Queries) SaveMeter(ctx context.Context, arg SaveMeterParams) error {
	_, err := q.db.ExecContext(ctx, saveMeter,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.Aggregation,
		arg.Dimensions,
		arg.EventRetentionDays,
		arg.CreatedAt,
	)
	return err
}
