// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
)

type AuthApiKey struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	CreatedAt  string
	LastUsedAt sql.NullString
}

type AuthUser struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}
