// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
)

type AlertEvaluationJob struct {
	RuleID      string
	RunAfter    string
	LockedUntil sql.NullString
	Attempts    int64
	CreatedAt   string
	UpdatedAt   string
}

type AlertState struct {
	RuleID      string
	GroupKey    string
	GroupValue  string
	Status      string
	Value       float64
	Message     string
	EvaluatedAt sql.NullString
	UpdatedAt   string
}

type AuthApiKey struct {
	ID            string
	UserID        string
	WorkspaceID   string
	Name          string
	TokenHash     string
	Prefix        string
	Scopes        string
	AllowedMeters string
	ExpiresAt     sql.NullString
	RevokedAt     sql.NullString
	CreatedAt     string
	LastUsedAt    sql.NullString
}

type AuthIdentity struct {
	ID            string
	UserID        string
	Provider      string
	Subject       string
	Email         string
	EmailVerified int64
	CreatedAt     string
	UpdatedAt     string
}

type AuthSession struct {
	ID          string
	UserID      string
	WorkspaceID string
	TokenHash   string
	Kind        string
	ExpiresAt   string
	CreatedAt   string
}

type AuthUser struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}

type AuthWorkspace struct {
	ID        string
	Name      string
	CreatedAt string
}

type EntitlementCheckJob struct {
	WorkspaceID string
	Subject     string
	MeterName   string
	RunAfter    string
	LockedUntil sql.NullString
	Attempts    int64
	CreatedAt   string
	UpdatedAt   string
}

type EntitlementEvent struct {
	ID             string
	WorkspaceID    string
	Subject        string
	MeterName      string
	PlanID         string
	PlanName       string
	Period         string
	PreviousState  sql.NullString
	State          string
	Type           string
	CurrentValue   float64
	LimitValue     float64
	RemainingValue float64
	WarningPercent float64
	Message        string
	CreatedAt      string
}

type EntitlementState struct {
	WorkspaceID    string
	Subject        string
	MeterName      string
	PlanID         string
	PlanName       string
	Period         string
	State          string
	CurrentValue   float64
	LimitValue     float64
	RemainingValue float64
	WarningPercent float64
	Message        string
	EvaluatedAt    string
	UpdatedAt      string
}

type EntitlementUsageCounter struct {
	WorkspaceID    string
	Subject        string
	MeterName      string
	Period         string
	PeriodStart    string
	PeriodEnd      string
	EventCount     int64
	QuantitySum    float64
	QuantityMin    float64
	QuantityMax    float64
	FirstQuantity  float64
	FirstEventTime string
	LastQuantity   float64
	LastEventTime  string
	UpdatedAt      string
}

type UsageExportJob struct {
	ID           string
	WorkspaceID  string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int64
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

type UsageSavedQuery struct {
	ID          string
	UserID      string
	Name        string
	QueryJson   string
	GroupBy     string
	BucketSize  string
	ResultLimit int64
	Pinned      int64
	Position    int64
	CreatedAt   string
	UpdatedAt   string
}
