// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
)

type AuthApiKey struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	CreatedAt  string
	LastUsedAt sql.NullString
}

type AuthUser struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}

type UsageEvent struct {
	ID             string
	IdempotencyKey sql.NullString
	Subject        string
	MeterName      string
	Quantity       float64
	EventTime      string
	ReceivedAt     string
	Metadata       string
}

type UsageExportJob struct {
	ID          string
	Kind        string
	Status      string
	Format      string
	QueryJson   string
	Error       string
	CreatedAt   string
	UpdatedAt   string
	CompletedAt sql.NullString
}

type UsageIngestion struct {
	ID         string
	Kind       string
	Accepted   int64
	Duplicates int64
	Failed     int64
	CreatedAt  string
}

type UsagePruneRun struct {
	ID        string
	DryRun    int64
	Deleted   int64
	Meters    string
	CreatedAt string
}
