// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const claimReconciliationNotification = `-- name: ClaimReconciliationNotification :one
UPDATE reconciliation_notifications
SET locked_until = ?1
WHERE id = (
	SELECT id FROM reconciliation_notifications
	WHERE status = 'pending' AND julianday(next_attempt_at) <= julianday(?2)
		AND (locked_until IS NULL OR julianday(locked_until) <= julianday(?2))
	ORDER BY next_attempt_at, id LIMIT 1
)
RETURNING id, workspace_id, event_type, fingerprint, payload,
	status, attempts, next_attempt_at, last_error, created_at, delivered_at,
	(SELECT COUNT(*) FROM reconciliation_notification_attempts a WHERE a.notification_id = reconciliation_notifications.id) AS total_attempts
`

type ClaimReconciliationNotificationParams struct {
	LockedUntil sql.NullString
	Now         interface{}
}

type ClaimReconciliationNotificationRow struct {
	ID            string
	WorkspaceID   string
	EventType     string
	Fingerprint   string
	Payload       string
	Status        string
	Attempts      int64
	NextAttemptAt string
	LastError     string
	CreatedAt     string
	DeliveredAt   sql.NullString
	Count         int64
}

func (q *Queries) ClaimReconciliationNotification(ctx context.Context, arg ClaimReconciliationNotificationParams) (ClaimReconciliationNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, claimReconciliationNotification, arg.LockedUntil, arg.Now)
	var i ClaimReconciliationNotificationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EventType,
		&i.Fingerprint,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.Count,
	)
	return i, err
}

const claimReconciliationSchedule = `-- name: ClaimReconciliationSchedule :one
UPDATE reconciliation_schedules
SET locked_until = ?1, updated_at = ?2
WHERE workspace_id = (
	SELECT workspace_id FROM reconciliation_schedules
	WHERE julianday(next_run_at) <= julianday(?2)
		AND (locked_until IS NULL OR julianday(locked_until) <= julianday(?2))
	ORDER BY next_run_at, workspace_id LIMIT 1
)
RETURNING workspace_id, last_fingerprint, last_notified_fingerprint, last_failure_fingerprint
`

type ClaimReconciliationScheduleParams struct {
	LockedUntil sql.NullString
	Now         string
}

type ClaimReconciliationScheduleRow struct {
	WorkspaceID             string
	LastFingerprint         string
	LastNotifiedFingerprint string
	LastFailureFingerprint  string
}

func (q *Queries) ClaimReconciliationSchedule(ctx context.Context, arg ClaimReconciliationScheduleParams) (ClaimReconciliationScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, claimReconciliationSchedule, arg.LockedUntil, arg.Now)
	var i ClaimReconciliationScheduleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.LastFingerprint,
		&i.LastNotifiedFingerprint,
		&i.LastFailureFingerprint,
	)
	return i, err
}

const completeReconciliationNotification = `-- name: CompleteReconciliationNotification :exec
UPDATE reconciliation_notifications
SET status = 'delivered', attempts = attempts + 1, locked_until = NULL,
	last_error = '', delivered_at = ?1
WHERE id = ?2
`

type CompleteReconciliationNotificationParams struct {
	DeliveredAt sql.NullString
	ID          string
}

func (q *Queries) CompleteReconciliationNotification(ctx context.Context, arg CompleteReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, completeReconciliationNotification, arg.DeliveredAt, arg.ID)
	return err
}

const completeReconciliationSchedule = `-- name: CompleteReconciliationSchedule :exec
UPDATE reconciliation_schedules
SET next_run_at = ?1, locked_until = NULL,
	last_fingerprint = ?2,
	last_notified_fingerprint = CASE WHEN ?2 = '' THEN '' ELSE last_notified_fingerprint END,
	last_failure_fingerprint = '',
	updated_at = ?3
WHERE workspace_id = ?4
`

type CompleteReconciliationScheduleParams struct {
	NextRunAt   string
	Fingerprint string
	UpdatedAt   string
	WorkspaceID string
}

func (q *Queries) CompleteReconciliationSchedule(ctx context.Context, arg CompleteReconciliationScheduleParams) error {
	_, err := q.db.ExecContext(ctx, completeReconciliationSchedule,
		arg.NextRunAt,
		arg.Fingerprint,
		arg.UpdatedAt,
		arg.WorkspaceID,
	)
	return err
}

const countReconciliationNotificationStates = `-- name: CountReconciliationNotificationStates :one
SELECT
	SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) AS pending,
	SUM(CASE WHEN status = 'dead_letter' THEN 1 ELSE 0 END) AS dead_letter
FROM reconciliation_notifications
WHERE workspace_id = ?1
`

type CountReconciliationNotificationStatesRow struct {
	Pending    sql.NullFloat64
	DeadLetter sql.NullFloat64
}

func (q *Queries) CountReconciliationNotificationStates(ctx context.Context, workspaceID string) (CountReconciliationNotificationStatesRow, error) {
	row := q.db.QueryRowContext(ctx, countReconciliationNotificationStates, workspaceID)
	var i CountReconciliationNotificationStatesRow
	err := row.Scan(&i.Pending, &i.DeadLetter)
	return i, err
}

const deleteEntitlementCounterForRepair = `-- name: DeleteEntitlementCounterForRepair :execrows
DELETE FROM entitlement_usage_counters
WHERE workspace_id = ?1
	AND subject = ?2
	AND meter_name = ?3
	AND period = ?4
	AND period_start = ?5
	AND updated_at = ?6
`

type DeleteEntitlementCounterForRepairParams struct {
	WorkspaceID       string
	Subject           string
	MeterName         string
	Period            string
	PeriodStart       string
	ExpectedUpdatedAt string
}

func (q *Queries) DeleteEntitlementCounterForRepair(ctx context.Context, arg DeleteEntitlementCounterForRepairParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntitlementCounterForRepair,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueAlertWorkerDeadLetter = `-- name: EnqueueAlertWorkerDeadLetter :execrows
INSERT INTO alert_evaluation_jobs (rule_id, run_after, locked_until, attempts, created_at, updated_at)
SELECT d.rule_id, ?1, NULL, 0, ?1, ?1
FROM system_worker_dead_letters d
JOIN alert_rules r ON r.id = d.rule_id AND r.workspace_id = d.workspace_id
WHERE d.workspace_id = ?2 AND d.public_id = ?3
	AND d.worker_name = 'alert' AND d.status = 'dead_letter'
ON CONFLICT(rule_id) DO UPDATE SET run_after = excluded.run_after, locked_until = NULL, attempts = 0, updated_at = excluded.updated_at
`

type EnqueueAlertWorkerDeadLetterParams struct {
	Now         string
	WorkspaceID string
	PublicID    string
}

func (q *Queries) EnqueueAlertWorkerDeadLetter(ctx context.Context, arg EnqueueAlertWorkerDeadLetterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueAlertWorkerDeadLetter, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueEntitlementWorkerDeadLetter = `-- name: EnqueueEntitlementWorkerDeadLetter :execrows
INSERT INTO entitlement_check_jobs (workspace_id, subject, meter_name, run_after, locked_until, attempts, created_at, updated_at)
SELECT d.workspace_id, d.subject, d.meter_name, ?1, NULL, 0, ?1, ?1
FROM system_worker_dead_letters d
JOIN meters m ON m.workspace_id = d.workspace_id AND m.name = d.meter_name
WHERE d.workspace_id = ?2 AND d.public_id = ?3
	AND d.worker_name = 'entitlement' AND d.status = 'dead_letter'
ON CONFLICT(workspace_id, subject, meter_name) DO UPDATE SET run_after = excluded.run_after, locked_until = NULL, attempts = 0, updated_at = excluded.updated_at
`

type EnqueueEntitlementWorkerDeadLetterParams struct {
	Now         string
	WorkspaceID string
	PublicID    string
}

func (q *Queries) EnqueueEntitlementWorkerDeadLetter(ctx context.Context, arg EnqueueEntitlementWorkerDeadLetterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueEntitlementWorkerDeadLetter, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureReconciliationSchedules = `-- name: EnsureReconciliationSchedules :exec
INSERT INTO reconciliation_schedules (workspace_id, next_run_at, updated_at)
SELECT id, ?1, ?1
FROM auth_workspaces
WHERE 1
ON CONFLICT (workspace_id) DO NOTHING
`

func (q *Queries) EnsureReconciliationSchedules(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, ensureReconciliationSchedules, now)
	return err
}

const failReconciliationSchedule = `-- name: FailReconciliationSchedule :exec
UPDATE reconciliation_schedules
SET next_run_at = ?1, locked_until = NULL,
	last_failure_fingerprint = ?2, updated_at = ?3
WHERE workspace_id = ?4
`

type FailReconciliationScheduleParams struct {
	NextRunAt          string
	FailureFingerprint string
	UpdatedAt          string
	WorkspaceID        string
}

func (q *Queries) FailReconciliationSchedule(ctx context.Context, arg FailReconciliationScheduleParams) error {
	_, err := q.db.ExecContext(ctx, failReconciliationSchedule,
		arg.NextRunAt,
		arg.FailureFingerprint,
		arg.UpdatedAt,
		arg.WorkspaceID,
	)
	return err
}

const getEntitlementCounterForRepair = `-- name: GetEntitlementCounterForRepair :one
SELECT c.subject, c.meter_name, c.period, c.period_start, c.period_end,
	c.event_count, c.quantity_sum, c.quantity_min, c.quantity_max,
	c.first_quantity, c.first_event_time, c.last_quantity, c.last_event_time, c.updated_at,
	m.event_retention_days
FROM entitlement_usage_counters c
JOIN meters m ON m.workspace_id = c.workspace_id AND m.name = c.meter_name
WHERE c.workspace_id = ?1
	AND c.subject = ?2
	AND c.meter_name = ?3
	AND c.period = ?4
	AND c.period_start = ?5
`

type GetEntitlementCounterForRepairParams struct {
	WorkspaceID string
	Subject     string
	MeterName   string
	Period      string
	PeriodStart string
}

type GetEntitlementCounterForRepairRow struct {
	Subject            string
	MeterName          string
	Period             string
	PeriodStart        string
	PeriodEnd          string
	EventCount         int64
	QuantitySum        float64
	QuantityMin        float64
	QuantityMax        float64
	FirstQuantity      float64
	FirstEventTime     string
	LastQuantity       float64
	LastEventTime      string
	UpdatedAt          string
	EventRetentionDays int64
}

func (q *Queries) GetEntitlementCounterForRepair(ctx context.Context, arg GetEntitlementCounterForRepairParams) (GetEntitlementCounterForRepairRow, error) {
	row := q.db.QueryRowContext(ctx, getEntitlementCounterForRepair,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
	)
	var i GetEntitlementCounterForRepairRow
	err := row.Scan(
		&i.Subject,
		&i.MeterName,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EventCount,
		&i.QuantitySum,
		&i.QuantityMin,
		&i.QuantityMax,
		&i.FirstQuantity,
		&i.FirstEventTime,
		&i.LastQuantity,
		&i.LastEventTime,
		&i.UpdatedAt,
		&i.EventRetentionDays,
	)
	return i, err
}

const getReconciliationSchedule = `-- name: GetReconciliationSchedule :one
SELECT next_run_at, locked_until, updated_at
FROM reconciliation_schedules
WHERE workspace_id = ?1
`

type GetReconciliationScheduleRow struct {
	NextRunAt   string
	LockedUntil sql.NullString
	UpdatedAt   string
}

func (q *Queries) GetReconciliationSchedule(ctx context.Context, workspaceID string) (GetReconciliationScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getReconciliationSchedule, workspaceID)
	var i GetReconciliationScheduleRow
	err := row.Scan(&i.NextRunAt, &i.LockedUntil, &i.UpdatedAt)
	return i, err
}

const getWorkerDeadLetter = `-- name: GetWorkerDeadLetter :one
SELECT public_id, worker_name, job_key, rule_id, subject, meter_name, attempts, last_error, status, created_at, requeued_at
FROM system_worker_dead_letters
WHERE workspace_id = ?1 AND public_id = ?2
`

type GetWorkerDeadLetterParams struct {
	WorkspaceID string
	PublicID    string
}

type GetWorkerDeadLetterRow struct {
	PublicID   string
	WorkerName string
	JobKey     string
	RuleID     string
	Subject    string
	MeterName  string
	Attempts   int64
	LastError  string
	Status     string
	CreatedAt  string
	RequeuedAt sql.NullString
}

func (q *Queries) GetWorkerDeadLetter(ctx context.Context, arg GetWorkerDeadLetterParams) (GetWorkerDeadLetterRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkerDeadLetter, arg.WorkspaceID, arg.PublicID)
	var i GetWorkerDeadLetterRow
	err := row.Scan(
		&i.PublicID,
		&i.WorkerName,
		&i.JobKey,
		&i.RuleID,
		&i.Subject,
		&i.MeterName,
		&i.Attempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.RequeuedAt,
	)
	return i, err
}

const listActiveEntitlementCounters = `-- name: ListActiveEntitlementCounters :many
SELECT c.subject, c.meter_name, c.period, c.period_start, c.period_end,
	c.event_count, c.quantity_sum, c.quantity_min, c.quantity_max, c.updated_at,
	m.event_retention_days
FROM entitlement_usage_counters c
JOIN meters m ON m.workspace_id = c.workspace_id AND m.name = c.meter_name
WHERE c.workspace_id = ?1
	AND julianday(c.period_start) <= julianday(?2)
	AND julianday(c.period_end) > julianday(?2)
ORDER BY c.updated_at DESC, c.subject, c.meter_name, c.period
LIMIT ?3
`

type ListActiveEntitlementCountersParams struct {
	WorkspaceID string
	Now         interface{}
	Limit       int64
}

type ListActiveEntitlementCountersRow struct {
	Subject            string
	MeterName          string
	Period             string
	PeriodStart        string
	PeriodEnd          string
	EventCount         int64
	QuantitySum        float64
	QuantityMin        float64
	QuantityMax        float64
	UpdatedAt          string
	EventRetentionDays int64
}

func (q *Queries) ListActiveEntitlementCounters(ctx context.Context, arg ListActiveEntitlementCountersParams) ([]ListActiveEntitlementCountersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEntitlementCounters, arg.WorkspaceID, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEntitlementCountersRow{}
	for rows.Next() {
		var i ListActiveEntitlementCountersRow
		if err := rows.Scan(
			&i.Subject,
			&i.MeterName,
			&i.Period,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EventCount,
			&i.QuantitySum,
			&i.QuantityMin,
			&i.QuantityMax,
			&i.UpdatedAt,
			&i.EventRetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterReconciliationAssignments = `-- name: ListCounterReconciliationAssignments :many
SELECT id, assigned_at, period_anchor_at, unassigned_at
FROM plan_subject_assignments
WHERE workspace_id = ?1
	AND subject = ?2
	AND julianday(assigned_at) < julianday(?3)
	AND (unassigned_at IS NULL OR julianday(unassigned_at) > julianday(?4))
ORDER BY assigned_at DESC, id DESC
`

type ListCounterReconciliationAssignmentsParams struct {
	WorkspaceID string
	Subject     string
	WindowEnd   interface{}
	WindowStart interface{}
}

type ListCounterReconciliationAssignmentsRow struct {
	ID             string
	AssignedAt     string
	PeriodAnchorAt string
	UnassignedAt   sql.NullString
}

func (q *Queries) ListCounterReconciliationAssignments(ctx context.Context, arg ListCounterReconciliationAssignmentsParams) ([]ListCounterReconciliationAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterReconciliationAssignments,
		arg.WorkspaceID,
		arg.Subject,
		arg.WindowEnd,
		arg.WindowStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterReconciliationAssignmentsRow{}
	for rows.Next() {
		var i ListCounterReconciliationAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignedAt,
			&i.PeriodAnchorAt,
			&i.UnassignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterReconciliationEvents = `-- name: ListCounterReconciliationEvents :many
SELECT id, quantity, event_time, received_at
FROM usage_events
WHERE workspace_id = ?1
	AND subject = ?2
	AND meter_name = ?3
	AND julianday(event_time) >= julianday(?4)
	AND julianday(event_time) < julianday(?5)
ORDER BY received_at, id
`

type ListCounterReconciliationEventsParams struct {
	WorkspaceID string
	Subject     string
	MeterName   string
	PeriodStart interface{}
	PeriodEnd   interface{}
}

type ListCounterReconciliationEventsRow struct {
	ID         string
	Quantity   float64
	EventTime  string
	ReceivedAt string
}

func (q *Queries) ListCounterReconciliationEvents(ctx context.Context, arg ListCounterReconciliationEventsParams) ([]ListCounterReconciliationEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterReconciliationEvents,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterReconciliationEventsRow{}
	for rows.Next() {
		var i ListCounterReconciliationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.EventTime,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionReconciliationRows = `-- name: ListDecisionReconciliationRows :many
SELECT d.idempotency_key, d.subject, d.meter_name, d.accepted, d.created_at,
	e.id AS event_id, e.subject AS event_subject, e.meter_name AS event_meter_name
FROM consumption_decisions d
LEFT JOIN usage_events e
	ON e.workspace_id = d.workspace_id AND e.idempotency_key = d.idempotency_key
WHERE d.workspace_id = ?1
	AND d.created_at >= ?2
ORDER BY d.created_at DESC, d.idempotency_key DESC
LIMIT ?3
`

type ListDecisionReconciliationRowsParams struct {
	WorkspaceID string
	Since       string
	Limit       int64
}

type ListDecisionReconciliationRowsRow struct {
	IdempotencyKey string
	Subject        string
	MeterName      string
	Accepted       int64
	CreatedAt      string
	EventID        sql.NullString
	EventSubject   sql.NullString
	EventMeterName sql.NullString
}

func (q *Queries) ListDecisionReconciliationRows(ctx context.Context, arg ListDecisionReconciliationRowsParams) ([]ListDecisionReconciliationRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionReconciliationRows, arg.WorkspaceID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecisionReconciliationRowsRow{}
	for rows.Next() {
		var i ListDecisionReconciliationRowsRow
		if err := rows.Scan(
			&i.IdempotencyKey,
			&i.Subject,
			&i.MeterName,
			&i.Accepted,
			&i.CreatedAt,
			&i.EventID,
			&i.EventSubject,
			&i.EventMeterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaCounterRepairRuns = `-- name: ListQuotaCounterRepairRuns :many
SELECT id, subject, meter_name, period, period_start, period_end, dry_run, applied,
	before_snapshot, after_snapshot, counter_updated_at, created_at
FROM quota_counter_repair_runs
WHERE workspace_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListQuotaCounterRepairRunsParams struct {
	WorkspaceID string
	Limit       int64
}

type ListQuotaCounterRepairRunsRow struct {
	ID               string
	Subject          string
	MeterName        string
	Period           string
	PeriodStart      string
	PeriodEnd        string
	DryRun           int64
	Applied          int64
	BeforeSnapshot   string
	AfterSnapshot    string
	CounterUpdatedAt string
	CreatedAt        string
}

func (q *Queries) ListQuotaCounterRepairRuns(ctx context.Context, arg ListQuotaCounterRepairRunsParams) ([]ListQuotaCounterRepairRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuotaCounterRepairRuns, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotaCounterRepairRunsRow{}
	for rows.Next() {
		var i ListQuotaCounterRepairRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.MeterName,
			&i.Period,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DryRun,
			&i.Applied,
			&i.BeforeSnapshot,
			&i.AfterSnapshot,
			&i.CounterUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationNotificationAttempts = `-- name: ListReconciliationNotificationAttempts :many
SELECT id, attempt, status, error, created_at
FROM reconciliation_notification_attempts
WHERE notification_id = ?1
ORDER BY created_at, id
`

type ListReconciliationNotificationAttemptsRow struct {
	ID        string
	Attempt   int64
	Status    string
	Error     string
	CreatedAt string
}

func (q *Queries) ListReconciliationNotificationAttempts(ctx context.Context, notificationID string) ([]ListReconciliationNotificationAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationNotificationAttempts, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationNotificationAttemptsRow{}
	for rows.Next() {
		var i ListReconciliationNotificationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationNotifications = `-- name: ListReconciliationNotifications :many
SELECT id, event_type, fingerprint, payload, status, attempts, next_attempt_at,
	locked_until, last_error, created_at, delivered_at
FROM reconciliation_notifications
WHERE workspace_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListReconciliationNotificationsParams struct {
	WorkspaceID string
	Limit       int64
}

type ListReconciliationNotificationsRow struct {
	ID            string
	EventType     string
	Fingerprint   string
	Payload       string
	Status        string
	Attempts      int64
	NextAttemptAt string
	LockedUntil   sql.NullString
	LastError     string
	CreatedAt     string
	DeliveredAt   sql.NullString
}

func (q *Queries) ListReconciliationNotifications(ctx context.Context, arg ListReconciliationNotificationsParams) ([]ListReconciliationNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationNotifications, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationNotificationsRow{}
	for rows.Next() {
		var i ListReconciliationNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Fingerprint,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationRuns = `-- name: ListReconciliationRuns :many
SELECT id, status, decisions_checked, counters_checked, issue_count, truncated,
	lookback_hours, duration_ms, fingerprint, issues, error, created_at
FROM reconciliation_runs
WHERE workspace_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListReconciliationRunsParams struct {
	WorkspaceID string
	Limit       int64
}

type ListReconciliationRunsRow struct {
	ID               string
	Status           string
	DecisionsChecked int64
	CountersChecked  int64
	IssueCount       int64
	Truncated        int64
	LookbackHours    int64
	DurationMs       int64
	Fingerprint      string
	Issues           string
	Error            string
	CreatedAt        string
}

func (q *Queries) ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]ListReconciliationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationRuns, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationRunsRow{}
	for rows.Next() {
		var i ListReconciliationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.DecisionsChecked,
			&i.CountersChecked,
			&i.IssueCount,
			&i.Truncated,
			&i.LookbackHours,
			&i.DurationMs,
			&i.Fingerprint,
			&i.Issues,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerDeadLetters = `-- name: ListWorkerDeadLetters :many
SELECT public_id, worker_name, job_key, rule_id, subject, meter_name, attempts, last_error, status, created_at, requeued_at
FROM system_worker_dead_letters
WHERE workspace_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListWorkerDeadLettersParams struct {
	WorkspaceID string
	Limit       int64
}

type ListWorkerDeadLettersRow struct {
	PublicID   string
	WorkerName string
	JobKey     string
	RuleID     string
	Subject    string
	MeterName  string
	Attempts   int64
	LastError  string
	Status     string
	CreatedAt  string
	RequeuedAt sql.NullString
}

func (q *Queries) ListWorkerDeadLetters(ctx context.Context, arg ListWorkerDeadLettersParams) ([]ListWorkerDeadLettersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerDeadLetters, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerDeadLettersRow{}
	for rows.Next() {
		var i ListWorkerDeadLettersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.WorkerName,
			&i.JobKey,
			&i.RuleID,
			&i.Subject,
			&i.MeterName,
			&i.Attempts,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.RequeuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerDiagnostics = `-- name: ListWorkerDiagnostics :many
SELECT 'export' AS worker_name,
	COALESCE(SUM(CASE WHEN e.status = 'queued' OR (e.status = 'running' AND e.locked_until < ?1) THEN 1 ELSE 0 END), 0) AS pending_jobs,
	COALESCE(SUM(CASE WHEN e.status = 'running' AND e.locked_until >= ?1 THEN 1 ELSE 0 END), 0) AS running_jobs,
	COALESCE(SUM(CASE WHEN e.status = 'failed' THEN 1 ELSE 0 END), 0) AS failed_jobs,
	COALESCE(MIN(CASE WHEN e.status = 'queued' OR (e.status = 'running' AND e.locked_until < ?1) THEN e.created_at END), '') AS oldest_pending_at,
	COALESCE(MAX(CASE WHEN e.status = 'completed' THEN e.completed_at END), '') AS last_success_at,
	COALESCE(MAX(CASE WHEN e.status = 'failed' THEN e.updated_at END), '') AS last_failure_at
FROM usage_export_jobs e
UNION ALL
SELECT 'alert',
	(SELECT COUNT(*) FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE (j.locked_until IS NULL OR j.locked_until < ?1) AND (?2 = '' OR r.workspace_id = ?2))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE (status = 'pending' OR (status = 'running' AND (locked_until IS NULL OR locked_until < ?1))) AND (?2 = '' OR workspace_id = ?2)),
	(SELECT COUNT(*) FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE j.locked_until >= ?1 AND (?2 = '' OR r.workspace_id = ?2))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE status = 'running' AND locked_until >= ?1 AND (?2 = '' OR workspace_id = ?2)),
	(SELECT COUNT(*) FROM system_worker_dead_letters WHERE worker_name = 'alert' AND status = 'dead_letter' AND (?2 = '' OR workspace_id = ?2))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE status = 'dead_letter' AND (?2 = '' OR workspace_id = ?2)),
	COALESCE((SELECT MIN(pending_at) FROM (
		SELECT j.created_at AS pending_at FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE (j.locked_until IS NULL OR j.locked_until < ?1) AND (?2 = '' OR r.workspace_id = ?2)
		UNION ALL
		SELECT created_at FROM alert_delivery_jobs WHERE (status = 'pending' OR (status = 'running' AND (locked_until IS NULL OR locked_until < ?1))) AND (?2 = '' OR workspace_id = ?2)
	)), ''),
	MAX(COALESCE((SELECT MAX(s.evaluated_at) FROM alert_states s JOIN alert_rules r ON r.id = s.rule_id WHERE ?2 = '' OR r.workspace_id = ?2), ''), COALESCE((SELECT MAX(delivered_at) FROM alert_delivery_jobs WHERE ?2 = '' OR workspace_id = ?2), '')),
	MAX(COALESCE((SELECT MAX(created_at) FROM system_worker_dead_letters WHERE worker_name = 'alert' AND status = 'dead_letter' AND (?2 = '' OR workspace_id = ?2)), ''), COALESCE((SELECT MAX(updated_at) FROM alert_delivery_jobs WHERE status = 'dead_letter' AND (?2 = '' OR workspace_id = ?2)), ''))
UNION ALL
SELECT 'entitlement',
	COALESCE(SUM(CASE WHEN e.locked_until IS NULL OR e.locked_until < ?1 THEN 1 ELSE 0 END), 0),
	COALESCE(SUM(CASE WHEN e.locked_until >= ?1 THEN 1 ELSE 0 END), 0),
	(SELECT COUNT(*) FROM system_worker_dead_letters WHERE worker_name = 'entitlement' AND status = 'dead_letter'),
	COALESCE(MIN(CASE WHEN e.locked_until IS NULL OR e.locked_until < ?1 THEN e.created_at END), ''),
	COALESCE((SELECT MAX(evaluated_at) FROM entitlement_states), ''),
	COALESCE((SELECT MAX(created_at) FROM system_worker_dead_letters WHERE worker_name = 'entitlement' AND status = 'dead_letter'), '')
FROM entitlement_check_jobs e
UNION ALL
SELECT 'retention', 0, 0, 0, '',
	MAX(last_success_at), ''
FROM (
	SELECT COALESCE(MAX(created_at), '') AS last_success_at FROM usage_prune_runs
	UNION ALL
	SELECT COALESCE(MAX(created_at), '') FROM consumption_decision_prune_runs
)
UNION ALL
SELECT 'reconciliation',
	COALESCE(SUM(CASE WHEN n.status = 'pending' AND (n.locked_until IS NULL OR n.locked_until < ?1) THEN 1 ELSE 0 END), 0)
		+ (SELECT COUNT(*) FROM reconciliation_schedules s WHERE s.next_run_at <= ?1 AND (s.locked_until IS NULL OR s.locked_until < ?1)),
	COALESCE(SUM(CASE WHEN n.status = 'pending' AND n.locked_until >= ?1 THEN 1 ELSE 0 END), 0)
		+ (SELECT COUNT(*) FROM reconciliation_schedules s WHERE s.locked_until >= ?1),
	COALESCE(SUM(CASE WHEN n.status = 'dead_letter' THEN 1 ELSE 0 END), 0),
	COALESCE((SELECT MIN(pending_at) FROM (
		SELECT created_at AS pending_at FROM reconciliation_notifications WHERE status = 'pending' AND (locked_until IS NULL OR locked_until < ?1)
		UNION ALL
		SELECT next_run_at FROM reconciliation_schedules WHERE next_run_at <= ?1 AND (locked_until IS NULL OR locked_until < ?1)
	)), ''),
	COALESCE((SELECT MAX(created_at) FROM reconciliation_runs WHERE status IN ('healthy', 'drift_detected')), ''),
	MAX(last_failure_at)
FROM reconciliation_notifications n
CROSS JOIN (
	SELECT MAX(last_failure_at) AS last_failure_at FROM (
		SELECT COALESCE(MAX(created_at), '') AS last_failure_at FROM reconciliation_runs WHERE status = 'failed'
		UNION ALL
		SELECT COALESCE(MAX(created_at), '') FROM reconciliation_notification_attempts WHERE status = 'failed'
	)
)
`

type ListWorkerDiagnosticsParams struct {
	Now         sql.NullString
	WorkspaceID interface{}
}

type ListWorkerDiagnosticsRow struct {
	WorkerName      string
	PendingJobs     interface{}
	RunningJobs     interface{}
	FailedJobs      interface{}
	OldestPendingAt interface{}
	LastSuccessAt   interface{}
	LastFailureAt   interface{}
}

func (q *Queries) ListWorkerDiagnostics(ctx context.Context, arg ListWorkerDiagnosticsParams) ([]ListWorkerDiagnosticsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerDiagnostics, arg.Now, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerDiagnosticsRow{}
	for rows.Next() {
		var i ListWorkerDiagnosticsRow
		if err := rows.Scan(
			&i.WorkerName,
			&i.PendingJobs,
			&i.RunningJobs,
			&i.FailedJobs,
			&i.OldestPendingAt,
			&i.LastSuccessAt,
			&i.LastFailureAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerHeartbeats = `-- name: ListWorkerHeartbeats :many
SELECT worker_name, started_at, last_heartbeat_at
FROM system_worker_heartbeats
ORDER BY worker_name ASC
`

func (q *Queries) ListWorkerHeartbeats(ctx context.Context) ([]SystemWorkerHeartbeat, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemWorkerHeartbeat{}
	for rows.Next() {
		var i SystemWorkerHeartbeat
		if err := rows.Scan(&i.WorkerName, &i.StartedAt, &i.LastHeartbeatAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReconciliationNotified = `-- name: MarkReconciliationNotified :exec
UPDATE reconciliation_schedules
SET last_notified_fingerprint = ?1, updated_at = ?2
WHERE workspace_id = ?3 AND last_fingerprint = ?1
`

type MarkReconciliationNotifiedParams struct {
	Fingerprint string
	UpdatedAt   string
	WorkspaceID string
}

func (q *Queries) MarkReconciliationNotified(ctx context.Context, arg MarkReconciliationNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, markReconciliationNotified, arg.Fingerprint, arg.UpdatedAt, arg.WorkspaceID)
	return err
}

const markWorkerDeadLetterRequeued = `-- name: MarkWorkerDeadLetterRequeued :execrows
UPDATE system_worker_dead_letters
SET status = 'requeued', requeued_at = ?1
WHERE workspace_id = ?2 AND public_id = ?3 AND status = 'dead_letter'
`

type MarkWorkerDeadLetterRequeuedParams struct {
	Now         sql.NullString
	WorkspaceID string
	PublicID    string
}

func (q *Queries) MarkWorkerDeadLetterRequeued(ctx context.Context, arg MarkWorkerDeadLetterRequeuedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWorkerDeadLetterRequeued, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueReconciliationNotification = `-- name: RequeueReconciliationNotification :execrows
UPDATE reconciliation_notifications
SET status = 'pending', attempts = 0, next_attempt_at = ?1,
	locked_until = NULL, last_error = '', delivered_at = NULL
WHERE id = ?2 AND workspace_id = ?3 AND status = 'dead_letter'
`

type RequeueReconciliationNotificationParams struct {
	NextAttemptAt string
	ID            string
	WorkspaceID   string
}

func (q *Queries) RequeueReconciliationNotification(ctx context.Context, arg RequeueReconciliationNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueReconciliationNotification, arg.NextAttemptAt, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryReconciliationNotification = `-- name: RetryReconciliationNotification :exec
UPDATE reconciliation_notifications
SET status = CASE WHEN attempts + 1 >= ?1 THEN 'dead_letter' ELSE 'pending' END,
	attempts = attempts + 1, next_attempt_at = ?2,
	locked_until = NULL, last_error = ?3
WHERE id = ?4
`

type RetryReconciliationNotificationParams struct {
	MaxAttempts   int64
	NextAttemptAt string
	LastError     string
	ID            string
}

func (q *Queries) RetryReconciliationNotification(ctx context.Context, arg RetryReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, retryReconciliationNotification,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const saveQuotaCounterRepairRun = `-- name: SaveQuotaCounterRepairRun :exec
INSERT INTO quota_counter_repair_runs (
	id, workspace_id, subject, meter_name, period, period_start, period_end,
	dry_run, applied, before_snapshot, after_snapshot, counter_updated_at, created_at
) VALUES (
	?1, ?2, ?3, ?4,
	?5, ?6, ?7, ?8,
	?9, ?10, ?11,
	?12, ?13
)
`

type SaveQuotaCounterRepairRunParams struct {
	ID               string
	WorkspaceID      string
	Subject          string
	MeterName        string
	Period           string
	PeriodStart      string
	PeriodEnd        string
	DryRun           int64
	Applied          int64
	BeforeSnapshot   string
	AfterSnapshot    string
	CounterUpdatedAt string
	CreatedAt        string
}

func (q *Queries) SaveQuotaCounterRepairRun(ctx context.Context, arg SaveQuotaCounterRepairRunParams) error {
	_, err := q.db.ExecContext(ctx, saveQuotaCounterRepairRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DryRun,
		arg.Applied,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
		arg.CounterUpdatedAt,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationNotification = `-- name: SaveReconciliationNotification :exec
INSERT INTO reconciliation_notifications (
	id, workspace_id, event_type, fingerprint, payload, status,
	attempts, next_attempt_at, created_at
) VALUES (
	?1, ?2, ?3, ?4,
	?5, 'pending', 0, ?6, ?7
)
`

type SaveReconciliationNotificationParams struct {
	ID            string
	WorkspaceID   string
	EventType     string
	Fingerprint   string
	Payload       string
	NextAttemptAt string
	CreatedAt     string
}

func (q *Queries) SaveReconciliationNotification(ctx context.Context, arg SaveReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationNotification,
		arg.ID,
		arg.WorkspaceID,
		arg.EventType,
		arg.Fingerprint,
		arg.Payload,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationNotificationAttempt = `-- name: SaveReconciliationNotificationAttempt :exec
INSERT INTO reconciliation_notification_attempts (id, notification_id, attempt, status, error, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type SaveReconciliationNotificationAttemptParams struct {
	ID             string
	NotificationID string
	Attempt        int64
	Status         string
	Error          string
	CreatedAt      string
}

func (q *Queries) SaveReconciliationNotificationAttempt(ctx context.Context, arg SaveReconciliationNotificationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationNotificationAttempt,
		arg.ID,
		arg.NotificationID,
		arg.Attempt,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationRun = `-- name: SaveReconciliationRun :exec
INSERT INTO reconciliation_runs (
	id, workspace_id, status, decisions_checked, counters_checked, issue_count,
	truncated, lookback_hours, duration_ms, fingerprint, issues, error, created_at
) VALUES (
	?1, ?2, ?3,
	?4, ?5, ?6,
	?7, ?8, ?9,
	?10, ?11, ?12, ?13
)
`

type SaveReconciliationRunParams struct {
	ID               string
	WorkspaceID      string
	Status           string
	DecisionsChecked int64
	CountersChecked  int64
	IssueCount       int64
	Truncated        int64
	LookbackHours    int64
	DurationMs       int64
	Fingerprint      string
	Issues           string
	Error            string
	CreatedAt        string
}

func (q *Queries) SaveReconciliationRun(ctx context.Context, arg SaveReconciliationRunParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.DecisionsChecked,
		arg.CountersChecked,
		arg.IssueCount,
		arg.Truncated,
		arg.LookbackHours,
		arg.DurationMs,
		arg.Fingerprint,
		arg.Issues,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const updateEntitlementCounterForRepair = `-- name: UpdateEntitlementCounterForRepair :execrows
UPDATE entitlement_usage_counters SET
	event_count = ?1, quantity_sum = ?2,
	quantity_min = ?3, quantity_max = ?4,
	first_quantity = ?5, first_event_time = ?6,
	last_quantity = ?7, last_event_time = ?8,
	updated_at = ?9
WHERE workspace_id = ?10
	AND subject = ?11
	AND meter_name = ?12
	AND period = ?13
	AND period_start = ?14
	AND updated_at = ?15
`

type UpdateEntitlementCounterForRepairParams struct {
	EventCount        int64
	QuantitySum       float64
	QuantityMin       float64
	QuantityMax       float64
	FirstQuantity     float64
	FirstEventTime    string
	LastQuantity      float64
	LastEventTime     string
	UpdatedAt         string
	WorkspaceID       string
	Subject           string
	MeterName         string
	Period            string
	PeriodStart       string
	ExpectedUpdatedAt string
}

func (q *Queries) UpdateEntitlementCounterForRepair(ctx context.Context, arg UpdateEntitlementCounterForRepairParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntitlementCounterForRepair,
		arg.EventCount,
		arg.QuantitySum,
		arg.QuantityMin,
		arg.QuantityMax,
		arg.FirstQuantity,
		arg.FirstEventTime,
		arg.LastQuantity,
		arg.LastEventTime,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO system_worker_heartbeats (worker_name, started_at, last_heartbeat_at)
VALUES (?, ?, ?)
ON CONFLICT(worker_name) DO UPDATE SET started_at = excluded.started_at, last_heartbeat_at = excluded.last_heartbeat_at
`

type UpsertWorkerHeartbeatParams struct {
	WorkerName      string
	StartedAt       string
	LastHeartbeatAt string
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkerHeartbeat, arg.WorkerName, arg.StartedAt, arg.LastHeartbeatAt)
	return err
}
