// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_queries.sql

package sqlitedb

import (
	"context"
)

const deleteSavedQuery = `-- name: DeleteSavedQuery :execrows
DELETE FROM usage_saved_queries
WHERE user_id = ? AND id = ?
`

type DeleteSavedQueryParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteSavedQuery(ctx context.Context, arg DeleteSavedQueryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSavedQuery, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findSavedQueryByID = `-- name: FindSavedQueryByID :one
SELECT id, user_id, name, query_json, group_by, bucket_size, result_limit, pinned, position, created_at, updated_at
FROM usage_saved_queries
WHERE user_id = ? AND id = ?
`

type FindSavedQueryByIDParams struct {
	UserID string
	ID     string
}

func (q *Queries) FindSavedQueryByID(ctx context.Context, arg FindSavedQueryByIDParams) (UsageSavedQuery, error) {
	row := q.db.QueryRowContext(ctx, findSavedQueryByID, arg.UserID, arg.ID)
	var i UsageSavedQuery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryJson,
		&i.GroupBy,
		&i.BucketSize,
		&i.ResultLimit,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedQueries = `-- name: ListSavedQueries :many
SELECT id, user_id, name, query_json, group_by, bucket_size, result_limit, pinned, position, created_at, updated_at
FROM usage_saved_queries
WHERE user_id = ?
ORDER BY pinned DESC, position ASC, updated_at DESC, id DESC
`

func (q *Queries) ListSavedQueries(ctx context.Context, userID string) ([]UsageSavedQuery, error) {
	rows, err := q.db.QueryContext(ctx, listSavedQueries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageSavedQuery{}
	for rows.Next() {
		var i UsageSavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.QueryJson,
			&i.GroupBy,
			&i.BucketSize,
			&i.ResultLimit,
			&i.Pinned,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSavedQuery = `-- name: SaveSavedQuery :exec
INSERT INTO usage_saved_queries (id, user_id, name, query_json, group_by, bucket_size, result_limit, pinned, position, created_at, updated_at)
VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11
)
ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	query_json = excluded.query_json,
	group_by = excluded.group_by,
	bucket_size = excluded.bucket_size,
	result_limit = excluded.result_limit,
	pinned = excluded.pinned,
	position = excluded.position,
	updated_at = excluded.updated_at
`

type SaveSavedQueryParams struct {
	ID          string
	UserID      string
	Name        string
	QueryJson   string
	GroupBy     string
	BucketSize  string
	ResultLimit int64
	Pinned      int64
	Position    int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) SaveSavedQuery(ctx context.Context, arg SaveSavedQueryParams) error {
	_, err := q.db.ExecContext(ctx, saveSavedQuery,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.QueryJson,
		arg.GroupBy,
		arg.BucketSize,
		arg.ResultLimit,
		arg.Pinned,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
