// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_dimensions.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const listUsageDimensionValues = `-- name: ListUsageDimensionValues :many
SELECT value, COUNT(*) AS usage_events
FROM (
	SELECT CASE json_type(metadata, CAST(?1 AS TEXT))
		WHEN 'true' THEN 'true'
		WHEN 'false' THEN 'false'
		ELSE CAST(json_extract(metadata, CAST(?1 AS TEXT)) AS TEXT)
	END AS value
	FROM usage_events
	WHERE meter_name = ?2
		AND json_type(metadata, CAST(?1 AS TEXT)) IS NOT NULL
		AND (CAST(?3 AS TEXT) IS NULL OR subject = CAST(?3 AS TEXT))
		AND (CAST(?4 AS TEXT) IS NULL OR event_time >= CAST(?4 AS TEXT))
		AND (CAST(?5 AS TEXT) IS NULL OR event_time < CAST(?5 AS TEXT))
) discovered
WHERE value IS NOT NULL AND value != ''
GROUP BY value
ORDER BY usage_events DESC, value ASC
LIMIT ?6
`

type ListUsageDimensionValuesParams struct {
	Path      string
	MeterName string
	Subject   sql.NullString
	FromTime  sql.NullString
	ToTime    sql.NullString
	Limit     int64
}

type ListUsageDimensionValuesRow struct {
	Value       string
	UsageEvents int64
}

func (q *Queries) ListUsageDimensionValues(ctx context.Context, arg ListUsageDimensionValuesParams) ([]ListUsageDimensionValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageDimensionValues,
		arg.Path,
		arg.MeterName,
		arg.Subject,
		arg.FromTime,
		arg.ToTime,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageDimensionValuesRow{}
	for rows.Next() {
		var i ListUsageDimensionValuesRow
		if err := rows.Scan(&i.Value, &i.UsageEvents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
