// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_stats.sql

package sqlitedb

import (
	"context"
)

const ensureWorkspaceStats = `-- name: EnsureWorkspaceStats :exec
INSERT INTO workspace_stats (workspace_id, meters, usage_events, prune_runs, updated_at)
VALUES (?1, 0, 0, 0, ?2)
ON CONFLICT (workspace_id) DO NOTHING
`

type EnsureWorkspaceStatsParams struct {
	WorkspaceID string
	UpdatedAt   string
}

func (q *Queries) EnsureWorkspaceStats(ctx context.Context, arg EnsureWorkspaceStatsParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorkspaceStats, arg.WorkspaceID, arg.UpdatedAt)
	return err
}

const getWorkspaceStats = `-- name: GetWorkspaceStats :one
SELECT meters, usage_events, prune_runs
FROM workspace_stats
WHERE workspace_id = ?1
`

type GetWorkspaceStatsRow struct {
	Meters      int64
	UsageEvents int64
	PruneRuns   int64
}

func (q *Queries) GetWorkspaceStats(ctx context.Context, workspaceID string) (GetWorkspaceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceStats, workspaceID)
	var i GetWorkspaceStatsRow
	err := row.Scan(&i.Meters, &i.UsageEvents, &i.PruneRuns)
	return i, err
}

const incrementWorkspaceMeters = `-- name: IncrementWorkspaceMeters :exec
INSERT INTO workspace_stats (workspace_id, meters, usage_events, prune_runs, updated_at)
VALUES (?1, ?2, 0, 0, ?3)
ON CONFLICT (workspace_id) DO UPDATE SET
	meters = MAX(0, workspace_stats.meters + excluded.meters),
	updated_at = excluded.updated_at
`

type IncrementWorkspaceMetersParams struct {
	WorkspaceID string
	Delta       int64
	UpdatedAt   string
}

func (q *Queries) IncrementWorkspaceMeters(ctx context.Context, arg IncrementWorkspaceMetersParams) error {
	_, err := q.db.ExecContext(ctx, incrementWorkspaceMeters, arg.WorkspaceID, arg.Delta, arg.UpdatedAt)
	return err
}

const incrementWorkspacePruneRuns = `-- name: IncrementWorkspacePruneRuns :exec
INSERT INTO workspace_stats (workspace_id, meters, usage_events, prune_runs, updated_at)
VALUES (?1, 0, 0, ?2, ?3)
ON CONFLICT (workspace_id) DO UPDATE SET
	prune_runs = MAX(0, workspace_stats.prune_runs + excluded.prune_runs),
	updated_at = excluded.updated_at
`

type IncrementWorkspacePruneRunsParams struct {
	WorkspaceID string
	Delta       int64
	UpdatedAt   string
}

func (q *Queries) IncrementWorkspacePruneRuns(ctx context.Context, arg IncrementWorkspacePruneRunsParams) error {
	_, err := q.db.ExecContext(ctx, incrementWorkspacePruneRuns, arg.WorkspaceID, arg.Delta, arg.UpdatedAt)
	return err
}

const incrementWorkspaceUsageEvents = `-- name: IncrementWorkspaceUsageEvents :exec
INSERT INTO workspace_stats (workspace_id, meters, usage_events, prune_runs, updated_at)
VALUES (?1, 0, ?2, 0, ?3)
ON CONFLICT (workspace_id) DO UPDATE SET
	usage_events = MAX(0, workspace_stats.usage_events + excluded.usage_events),
	updated_at = excluded.updated_at
`

type IncrementWorkspaceUsageEventsParams struct {
	WorkspaceID string
	Delta       int64
	UpdatedAt   string
}

func (q *Queries) IncrementWorkspaceUsageEvents(ctx context.Context, arg IncrementWorkspaceUsageEventsParams) error {
	_, err := q.db.ExecContext(ctx, incrementWorkspaceUsageEvents, arg.WorkspaceID, arg.Delta, arg.UpdatedAt)
	return err
}
