// Code generated by go-swagger; DO NOT EDIT.

package system

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// GetSystemStatsReader is a Reader for the GetSystemStats structure.
type GetSystemStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetSystemStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/system/stats] getSystemStats", response, response.Code())
	}
}

// NewGetSystemStatsOK creates a GetSystemStatsOK with default headers values
func NewGetSystemStatsOK() *GetSystemStatsOK {
	return &GetSystemStatsOK{}
}

/*
GetSystemStatsOK describes a response with status code 200, with default header values.

OK
*/
type GetSystemStatsOK struct {
	Payload *models.SystemStats
}

// IsSuccess returns true when this get system stats o k response has a 2xx status code
func (o *GetSystemStatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get system stats o k response has a 3xx status code
func (o *GetSystemStatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get system stats o k response has a 4xx status code
func (o *GetSystemStatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get system stats o k response has a 5xx status code
func (o *GetSystemStatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get system stats o k response a status code equal to that given
func (o *GetSystemStatsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get system stats o k response
func (o *GetSystemStatsOK) Code() int {
	return 200
}

func (o *GetSystemStatsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/system/stats][%d] getSystemStatsOK %s", 200, payload)
}

func (o *GetSystemStatsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/system/stats][%d] getSystemStatsOK %s", 200, payload)
}

func (o *GetSystemStatsOK) GetPayload() *models.SystemStats {
	return o.Payload
}

func (o *GetSystemStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SystemStats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSystemStatsInternalServerError creates a GetSystemStatsInternalServerError with default headers values
func NewGetSystemStatsInternalServerError() *GetSystemStatsInternalServerError {
	return &GetSystemStatsInternalServerError{}
}

/*
GetSystemStatsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetSystemStatsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get system stats internal server error response has a 2xx status code
func (o *GetSystemStatsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get system stats internal server error response has a 3xx status code
func (o *GetSystemStatsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get system stats internal server error response has a 4xx status code
func (o *GetSystemStatsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get system stats internal server error response has a 5xx status code
func (o *GetSystemStatsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get system stats internal server error response a status code equal to that given
func (o *GetSystemStatsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get system stats internal server error response
func (o *GetSystemStatsInternalServerError) Code() int {
	return 500
}

func (o *GetSystemStatsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/system/stats][%d] getSystemStatsInternalServerError %s", 500, payload)
}

func (o *GetSystemStatsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/system/stats][%d] getSystemStatsInternalServerError %s", 500, payload)
}

func (o *GetSystemStatsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSystemStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
