// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// ListUsageBucketsReader is a Reader for the ListUsageBuckets structure.
type ListUsageBucketsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUsageBucketsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListUsageBucketsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListUsageBucketsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListUsageBucketsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListUsageBucketsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/usages] listUsageBuckets", response, response.Code())
	}
}

// NewListUsageBucketsOK creates a ListUsageBucketsOK with default headers values
func NewListUsageBucketsOK() *ListUsageBucketsOK {
	return &ListUsageBucketsOK{}
}

/*
ListUsageBucketsOK describes a response with status code 200, with default header values.

OK
*/
type ListUsageBucketsOK struct {
	Payload []*models.UsageBucket
}

// IsSuccess returns true when this list usage buckets o k response has a 2xx status code
func (o *ListUsageBucketsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list usage buckets o k response has a 3xx status code
func (o *ListUsageBucketsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list usage buckets o k response has a 4xx status code
func (o *ListUsageBucketsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list usage buckets o k response has a 5xx status code
func (o *ListUsageBucketsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list usage buckets o k response a status code equal to that given
func (o *ListUsageBucketsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list usage buckets o k response
func (o *ListUsageBucketsOK) Code() int {
	return 200
}

func (o *ListUsageBucketsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsOK %s", 200, payload)
}

func (o *ListUsageBucketsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsOK %s", 200, payload)
}

func (o *ListUsageBucketsOK) GetPayload() []*models.UsageBucket {
	return o.Payload
}

func (o *ListUsageBucketsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsageBucketsBadRequest creates a ListUsageBucketsBadRequest with default headers values
func NewListUsageBucketsBadRequest() *ListUsageBucketsBadRequest {
	return &ListUsageBucketsBadRequest{}
}

/*
ListUsageBucketsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListUsageBucketsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list usage buckets bad request response has a 2xx status code
func (o *ListUsageBucketsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list usage buckets bad request response has a 3xx status code
func (o *ListUsageBucketsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list usage buckets bad request response has a 4xx status code
func (o *ListUsageBucketsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list usage buckets bad request response has a 5xx status code
func (o *ListUsageBucketsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list usage buckets bad request response a status code equal to that given
func (o *ListUsageBucketsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list usage buckets bad request response
func (o *ListUsageBucketsBadRequest) Code() int {
	return 400
}

func (o *ListUsageBucketsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsBadRequest %s", 400, payload)
}

func (o *ListUsageBucketsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsBadRequest %s", 400, payload)
}

func (o *ListUsageBucketsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListUsageBucketsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsageBucketsNotFound creates a ListUsageBucketsNotFound with default headers values
func NewListUsageBucketsNotFound() *ListUsageBucketsNotFound {
	return &ListUsageBucketsNotFound{}
}

/*
ListUsageBucketsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListUsageBucketsNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list usage buckets not found response has a 2xx status code
func (o *ListUsageBucketsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list usage buckets not found response has a 3xx status code
func (o *ListUsageBucketsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list usage buckets not found response has a 4xx status code
func (o *ListUsageBucketsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list usage buckets not found response has a 5xx status code
func (o *ListUsageBucketsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list usage buckets not found response a status code equal to that given
func (o *ListUsageBucketsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list usage buckets not found response
func (o *ListUsageBucketsNotFound) Code() int {
	return 404
}

func (o *ListUsageBucketsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsNotFound %s", 404, payload)
}

func (o *ListUsageBucketsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsNotFound %s", 404, payload)
}

func (o *ListUsageBucketsNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListUsageBucketsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsageBucketsInternalServerError creates a ListUsageBucketsInternalServerError with default headers values
func NewListUsageBucketsInternalServerError() *ListUsageBucketsInternalServerError {
	return &ListUsageBucketsInternalServerError{}
}

/*
ListUsageBucketsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListUsageBucketsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list usage buckets internal server error response has a 2xx status code
func (o *ListUsageBucketsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list usage buckets internal server error response has a 3xx status code
func (o *ListUsageBucketsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list usage buckets internal server error response has a 4xx status code
func (o *ListUsageBucketsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list usage buckets internal server error response has a 5xx status code
func (o *ListUsageBucketsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list usage buckets internal server error response a status code equal to that given
func (o *ListUsageBucketsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list usage buckets internal server error response
func (o *ListUsageBucketsInternalServerError) Code() int {
	return 500
}

func (o *ListUsageBucketsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsInternalServerError %s", 500, payload)
}

func (o *ListUsageBucketsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usages][%d] listUsageBucketsInternalServerError %s", 500, payload)
}

func (o *ListUsageBucketsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListUsageBucketsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
