// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewListUsageBucketsParams creates a new ListUsageBucketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListUsageBucketsParams() *ListUsageBucketsParams {
	return NewListUsageBucketsParamsWithTimeout(cr.DefaultTimeout)
}

// NewListUsageBucketsParamsWithTimeout creates a new ListUsageBucketsParams object
// with the ability to set a timeout on a request.
func NewListUsageBucketsParamsWithTimeout(timeout time.Duration) *ListUsageBucketsParams {
	return &ListUsageBucketsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListUsageBucketsParamsWithContext creates a new ListUsageBucketsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListUsageBucketsParams].
func NewListUsageBucketsParamsWithContext(ctx context.Context) *ListUsageBucketsParams {
	return &ListUsageBucketsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListUsageBucketsParamsWithHTTPClient creates a new ListUsageBucketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListUsageBucketsParamsWithHTTPClient(client *http.Client) *ListUsageBucketsParams {
	return &ListUsageBucketsParams{
		HTTPClient: client,
	}
}

/*
ListUsageBucketsParams contains all the parameters to send to the API endpoint

	for the list usage buckets operation.

	Typically these are written to a http.Request.
*/
type ListUsageBucketsParams struct {

	/* BucketSize.

	   Bucket size: hour, day, month
	*/
	BucketSize *string

	/* From.

	   RFC3339 start time
	*/
	From string

	/* GroupBy.

	   Metadata key to group by
	*/
	GroupBy *string

	/* Limit.

	   Result limit
	*/
	Limit *int64

	/* Meter.

	   Meter name
	*/
	Meter string

	/* Subject.

	   Subject
	*/
	Subject string

	/* To.

	   RFC3339 end time
	*/
	To string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list usage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUsageBucketsParams) WithDefaults() *ListUsageBucketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list usage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUsageBucketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list usage buckets params.
func (o *ListUsageBucketsParams) WithTimeout(timeout time.Duration) *ListUsageBucketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list usage buckets params.
func (o *ListUsageBucketsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list usage buckets params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListUsageBucketsParams].
func (o *ListUsageBucketsParams) WithContext(ctx context.Context) *ListUsageBucketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list usage buckets params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListUsageBucketsParams].
func (o *ListUsageBucketsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list usage buckets params.
func (o *ListUsageBucketsParams) WithHTTPClient(client *http.Client) *ListUsageBucketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list usage buckets params.
func (o *ListUsageBucketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketSize adds the bucketSize to the list usage buckets params.
func (o *ListUsageBucketsParams) WithBucketSize(bucketSize *string) *ListUsageBucketsParams {
	o.SetBucketSize(bucketSize)
	return o
}

// SetBucketSize adds the bucketSize to the list usage buckets params.
func (o *ListUsageBucketsParams) SetBucketSize(bucketSize *string) {
	o.BucketSize = bucketSize
}

// WithFrom adds the from to the list usage buckets params.
func (o *ListUsageBucketsParams) WithFrom(from string) *ListUsageBucketsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the list usage buckets params.
func (o *ListUsageBucketsParams) SetFrom(from string) {
	o.From = from
}

// WithGroupBy adds the groupBy to the list usage buckets params.
func (o *ListUsageBucketsParams) WithGroupBy(groupBy *string) *ListUsageBucketsParams {
	o.SetGroupBy(groupBy)
	return o
}

// SetGroupBy adds the groupBy to the list usage buckets params.
func (o *ListUsageBucketsParams) SetGroupBy(groupBy *string) {
	o.GroupBy = groupBy
}

// WithLimit adds the limit to the list usage buckets params.
func (o *ListUsageBucketsParams) WithLimit(limit *int64) *ListUsageBucketsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list usage buckets params.
func (o *ListUsageBucketsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithMeter adds the meter to the list usage buckets params.
func (o *ListUsageBucketsParams) WithMeter(meter string) *ListUsageBucketsParams {
	o.SetMeter(meter)
	return o
}

// SetMeter adds the meter to the list usage buckets params.
func (o *ListUsageBucketsParams) SetMeter(meter string) {
	o.Meter = meter
}

// WithSubject adds the subject to the list usage buckets params.
func (o *ListUsageBucketsParams) WithSubject(subject string) *ListUsageBucketsParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the list usage buckets params.
func (o *ListUsageBucketsParams) SetSubject(subject string) {
	o.Subject = subject
}

// WithTo adds the to to the list usage buckets params.
func (o *ListUsageBucketsParams) WithTo(to string) *ListUsageBucketsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the list usage buckets params.
func (o *ListUsageBucketsParams) SetTo(to string) {
	o.To = to
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListUsageBucketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.BucketSize != nil {

		// query param bucket_size
		var qrBucketSize string

		if o.BucketSize != nil {
			qrBucketSize = *o.BucketSize
		}
		qBucketSize := qrBucketSize
		if qBucketSize != "" {

			if err := r.SetQueryParam("bucket_size", qBucketSize); err != nil {
				return err
			}
		}
	}

	// query param from
	qrFrom := o.From
	qFrom := qrFrom
	if qFrom != "" {

		if err := r.SetQueryParam("from", qFrom); err != nil {
			return err
		}
	}

	if o.GroupBy != nil {

		// query param group_by
		var qrGroupBy string

		if o.GroupBy != nil {
			qrGroupBy = *o.GroupBy
		}
		qGroupBy := qrGroupBy
		if qGroupBy != "" {

			if err := r.SetQueryParam("group_by", qGroupBy); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param meter
	qrMeter := o.Meter
	qMeter := qrMeter
	if qMeter != "" {

		if err := r.SetQueryParam("meter", qMeter); err != nil {
			return err
		}
	}

	// query param subject
	qrSubject := o.Subject
	qSubject := qrSubject
	if qSubject != "" {

		if err := r.SetQueryParam("subject", qSubject); err != nil {
			return err
		}
	}

	// query param to
	qrTo := o.To
	qTo := qrTo
	if qTo != "" {

		if err := r.SetQueryParam("to", qTo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
