// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// ListIngestionRunsReader is a Reader for the ListIngestionRuns structure.
type ListIngestionRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIngestionRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListIngestionRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListIngestionRunsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListIngestionRunsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/usageingestions] listIngestionRuns", response, response.Code())
	}
}

// NewListIngestionRunsOK creates a ListIngestionRunsOK with default headers values
func NewListIngestionRunsOK() *ListIngestionRunsOK {
	return &ListIngestionRunsOK{}
}

/*
ListIngestionRunsOK describes a response with status code 200, with default header values.

OK
*/
type ListIngestionRunsOK struct {
	Payload *models.UsageIngestionListResponse
}

// IsSuccess returns true when this list ingestion runs o k response has a 2xx status code
func (o *ListIngestionRunsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list ingestion runs o k response has a 3xx status code
func (o *ListIngestionRunsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list ingestion runs o k response has a 4xx status code
func (o *ListIngestionRunsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list ingestion runs o k response has a 5xx status code
func (o *ListIngestionRunsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list ingestion runs o k response a status code equal to that given
func (o *ListIngestionRunsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list ingestion runs o k response
func (o *ListIngestionRunsOK) Code() int {
	return 200
}

func (o *ListIngestionRunsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsOK %s", 200, payload)
}

func (o *ListIngestionRunsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsOK %s", 200, payload)
}

func (o *ListIngestionRunsOK) GetPayload() *models.UsageIngestionListResponse {
	return o.Payload
}

func (o *ListIngestionRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsageIngestionListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListIngestionRunsBadRequest creates a ListIngestionRunsBadRequest with default headers values
func NewListIngestionRunsBadRequest() *ListIngestionRunsBadRequest {
	return &ListIngestionRunsBadRequest{}
}

/*
ListIngestionRunsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListIngestionRunsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list ingestion runs bad request response has a 2xx status code
func (o *ListIngestionRunsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list ingestion runs bad request response has a 3xx status code
func (o *ListIngestionRunsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list ingestion runs bad request response has a 4xx status code
func (o *ListIngestionRunsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list ingestion runs bad request response has a 5xx status code
func (o *ListIngestionRunsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list ingestion runs bad request response a status code equal to that given
func (o *ListIngestionRunsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list ingestion runs bad request response
func (o *ListIngestionRunsBadRequest) Code() int {
	return 400
}

func (o *ListIngestionRunsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsBadRequest %s", 400, payload)
}

func (o *ListIngestionRunsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsBadRequest %s", 400, payload)
}

func (o *ListIngestionRunsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListIngestionRunsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListIngestionRunsInternalServerError creates a ListIngestionRunsInternalServerError with default headers values
func NewListIngestionRunsInternalServerError() *ListIngestionRunsInternalServerError {
	return &ListIngestionRunsInternalServerError{}
}

/*
ListIngestionRunsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListIngestionRunsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list ingestion runs internal server error response has a 2xx status code
func (o *ListIngestionRunsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list ingestion runs internal server error response has a 3xx status code
func (o *ListIngestionRunsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list ingestion runs internal server error response has a 4xx status code
func (o *ListIngestionRunsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list ingestion runs internal server error response has a 5xx status code
func (o *ListIngestionRunsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list ingestion runs internal server error response a status code equal to that given
func (o *ListIngestionRunsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list ingestion runs internal server error response
func (o *ListIngestionRunsInternalServerError) Code() int {
	return 500
}

func (o *ListIngestionRunsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsInternalServerError %s", 500, payload)
}

func (o *ListIngestionRunsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/usageingestions][%d] listIngestionRunsInternalServerError %s", 500, payload)
}

func (o *ListIngestionRunsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListIngestionRunsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
