// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewListIngestionRunsParams creates a new ListIngestionRunsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListIngestionRunsParams() *ListIngestionRunsParams {
	return NewListIngestionRunsParamsWithTimeout(cr.DefaultTimeout)
}

// NewListIngestionRunsParamsWithTimeout creates a new ListIngestionRunsParams object
// with the ability to set a timeout on a request.
func NewListIngestionRunsParamsWithTimeout(timeout time.Duration) *ListIngestionRunsParams {
	return &ListIngestionRunsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListIngestionRunsParamsWithContext creates a new ListIngestionRunsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListIngestionRunsParams].
func NewListIngestionRunsParamsWithContext(ctx context.Context) *ListIngestionRunsParams {
	return &ListIngestionRunsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListIngestionRunsParamsWithHTTPClient creates a new ListIngestionRunsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListIngestionRunsParamsWithHTTPClient(client *http.Client) *ListIngestionRunsParams {
	return &ListIngestionRunsParams{
		HTTPClient: client,
	}
}

/*
ListIngestionRunsParams contains all the parameters to send to the API endpoint

	for the list ingestion runs operation.

	Typically these are written to a http.Request.
*/
type ListIngestionRunsParams struct {

	/* Cursor.

	   Pagination cursor
	*/
	Cursor *string

	/* Limit.

	   Page size
	*/
	Limit *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list ingestion runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIngestionRunsParams) WithDefaults() *ListIngestionRunsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list ingestion runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIngestionRunsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list ingestion runs params.
func (o *ListIngestionRunsParams) WithTimeout(timeout time.Duration) *ListIngestionRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list ingestion runs params.
func (o *ListIngestionRunsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list ingestion runs params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListIngestionRunsParams].
func (o *ListIngestionRunsParams) WithContext(ctx context.Context) *ListIngestionRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list ingestion runs params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListIngestionRunsParams].
func (o *ListIngestionRunsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list ingestion runs params.
func (o *ListIngestionRunsParams) WithHTTPClient(client *http.Client) *ListIngestionRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list ingestion runs params.
func (o *ListIngestionRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the list ingestion runs params.
func (o *ListIngestionRunsParams) WithCursor(cursor *string) *ListIngestionRunsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the list ingestion runs params.
func (o *ListIngestionRunsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithLimit adds the limit to the list ingestion runs params.
func (o *ListIngestionRunsParams) WithLimit(limit *int64) *ListIngestionRunsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list ingestion runs params.
func (o *ListIngestionRunsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListIngestionRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
