// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// NewSearchUsageBreakdownParams creates a new SearchUsageBreakdownParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchUsageBreakdownParams() *SearchUsageBreakdownParams {
	return NewSearchUsageBreakdownParamsWithTimeout(cr.DefaultTimeout)
}

// NewSearchUsageBreakdownParamsWithTimeout creates a new SearchUsageBreakdownParams object
// with the ability to set a timeout on a request.
func NewSearchUsageBreakdownParamsWithTimeout(timeout time.Duration) *SearchUsageBreakdownParams {
	return &SearchUsageBreakdownParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewSearchUsageBreakdownParamsWithContext creates a new SearchUsageBreakdownParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBreakdownParams].
func NewSearchUsageBreakdownParamsWithContext(ctx context.Context) *SearchUsageBreakdownParams {
	return &SearchUsageBreakdownParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewSearchUsageBreakdownParamsWithHTTPClient creates a new SearchUsageBreakdownParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchUsageBreakdownParamsWithHTTPClient(client *http.Client) *SearchUsageBreakdownParams {
	return &SearchUsageBreakdownParams{
		HTTPClient: client,
	}
}

/*
SearchUsageBreakdownParams contains all the parameters to send to the API endpoint

	for the search usage breakdown operation.

	Typically these are written to a http.Request.
*/
type SearchUsageBreakdownParams struct {

	/* Request.

	   Usage breakdown search
	*/
	Request *models.UsageBreakdownRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the search usage breakdown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageBreakdownParams) WithDefaults() *SearchUsageBreakdownParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search usage breakdown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageBreakdownParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) WithTimeout(timeout time.Duration) *SearchUsageBreakdownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the search usage breakdown params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBreakdownParams].
func (o *SearchUsageBreakdownParams) WithContext(ctx context.Context) *SearchUsageBreakdownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search usage breakdown params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBreakdownParams].
func (o *SearchUsageBreakdownParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) WithHTTPClient(client *http.Client) *SearchUsageBreakdownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) WithRequest(request *models.UsageBreakdownRequest) *SearchUsageBreakdownParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the search usage breakdown params.
func (o *SearchUsageBreakdownParams) SetRequest(request *models.UsageBreakdownRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *SearchUsageBreakdownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
