// Code generated by go-swagger; DO NOT EDIT.

package usages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// NewSearchUsageBucketsParams creates a new SearchUsageBucketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchUsageBucketsParams() *SearchUsageBucketsParams {
	return NewSearchUsageBucketsParamsWithTimeout(cr.DefaultTimeout)
}

// NewSearchUsageBucketsParamsWithTimeout creates a new SearchUsageBucketsParams object
// with the ability to set a timeout on a request.
func NewSearchUsageBucketsParamsWithTimeout(timeout time.Duration) *SearchUsageBucketsParams {
	return &SearchUsageBucketsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewSearchUsageBucketsParamsWithContext creates a new SearchUsageBucketsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBucketsParams].
func NewSearchUsageBucketsParamsWithContext(ctx context.Context) *SearchUsageBucketsParams {
	return &SearchUsageBucketsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewSearchUsageBucketsParamsWithHTTPClient creates a new SearchUsageBucketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchUsageBucketsParamsWithHTTPClient(client *http.Client) *SearchUsageBucketsParams {
	return &SearchUsageBucketsParams{
		HTTPClient: client,
	}
}

/*
SearchUsageBucketsParams contains all the parameters to send to the API endpoint

	for the search usage buckets operation.

	Typically these are written to a http.Request.
*/
type SearchUsageBucketsParams struct {

	/* Request.

	   Usage search
	*/
	Request *models.InternalMeteringAdaptersHTTPUsageSearchRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the search usage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageBucketsParams) WithDefaults() *SearchUsageBucketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search usage buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageBucketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search usage buckets params.
func (o *SearchUsageBucketsParams) WithTimeout(timeout time.Duration) *SearchUsageBucketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search usage buckets params.
func (o *SearchUsageBucketsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the search usage buckets params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBucketsParams].
func (o *SearchUsageBucketsParams) WithContext(ctx context.Context) *SearchUsageBucketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search usage buckets params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageBucketsParams].
func (o *SearchUsageBucketsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the search usage buckets params.
func (o *SearchUsageBucketsParams) WithHTTPClient(client *http.Client) *SearchUsageBucketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search usage buckets params.
func (o *SearchUsageBucketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the search usage buckets params.
func (o *SearchUsageBucketsParams) WithRequest(request *models.InternalMeteringAdaptersHTTPUsageSearchRequest) *SearchUsageBucketsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the search usage buckets params.
func (o *SearchUsageBucketsParams) SetRequest(request *models.InternalMeteringAdaptersHTTPUsageSearchRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *SearchUsageBucketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
