// Code generated by go-swagger; DO NOT EDIT.

package plans

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new plans API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new plans API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new plans API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for plans API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// CheckEntitlement check entitlement quota.
	CheckEntitlement(params *CheckEntitlementParams, opts ...ClientOption) (*CheckEntitlementOK, error)

	// CheckEntitlementContext check entitlement quota.
	CheckEntitlementContext(ctx context.Context, params *CheckEntitlementParams, opts ...ClientOption) (*CheckEntitlementOK, error)

	// GetSubjectPlanProgress get subject plan progress.
	GetSubjectPlanProgress(params *GetSubjectPlanProgressParams, opts ...ClientOption) (*GetSubjectPlanProgressOK, error)

	// GetSubjectPlanProgressContext get subject plan progress.
	GetSubjectPlanProgressContext(ctx context.Context, params *GetSubjectPlanProgressParams, opts ...ClientOption) (*GetSubjectPlanProgressOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
CheckEntitlementchecks entitlement quota.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.CheckEntitlementContext] instead.
*/
func (a *Client) CheckEntitlement(params *CheckEntitlementParams, opts ...ClientOption) (*CheckEntitlementOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CheckEntitlementContext(ctx, params, opts...)
}

/*
CheckEntitlementContextchecks entitlement quota.

Do not use the deprecated [CheckEntitlementParams.Context] with this method: it would be ignored.
*/
func (a *Client) CheckEntitlementContext(ctx context.Context, params *CheckEntitlementParams, opts ...ClientOption) (*CheckEntitlementOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCheckEntitlementParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "checkEntitlement",
		Method:             "POST",
		PathPattern:        "/v1/entitlements/check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckEntitlementReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CheckEntitlementOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for checkEntitlement: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSubjectPlanProgressgets subject plan progress.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetSubjectPlanProgressContext] instead.
*/
func (a *Client) GetSubjectPlanProgress(params *GetSubjectPlanProgressParams, opts ...ClientOption) (*GetSubjectPlanProgressOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetSubjectPlanProgressContext(ctx, params, opts...)
}

/*
GetSubjectPlanProgressContextgets subject plan progress.

Do not use the deprecated [GetSubjectPlanProgressParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetSubjectPlanProgressContext(ctx context.Context, params *GetSubjectPlanProgressParams, opts ...ClientOption) (*GetSubjectPlanProgressOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetSubjectPlanProgressParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getSubjectPlanProgress",
		Method:             "GET",
		PathPattern:        "/v1/plans/subjects/{subject}/progress",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSubjectPlanProgressReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetSubjectPlanProgressOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getSubjectPlanProgress: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [PlansParams].
	ctx context.Context
}
