// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// ListSubjectsReader is a Reader for the ListSubjects structure.
type ListSubjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSubjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListSubjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListSubjectsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListSubjectsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/subjects] listSubjects", response, response.Code())
	}
}

// NewListSubjectsOK creates a ListSubjectsOK with default headers values
func NewListSubjectsOK() *ListSubjectsOK {
	return &ListSubjectsOK{}
}

/*
ListSubjectsOK describes a response with status code 200, with default header values.

OK
*/
type ListSubjectsOK struct {
	Payload *models.SubjectStatsListResponse
}

// IsSuccess returns true when this list subjects o k response has a 2xx status code
func (o *ListSubjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list subjects o k response has a 3xx status code
func (o *ListSubjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list subjects o k response has a 4xx status code
func (o *ListSubjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list subjects o k response has a 5xx status code
func (o *ListSubjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list subjects o k response a status code equal to that given
func (o *ListSubjectsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list subjects o k response
func (o *ListSubjectsOK) Code() int {
	return 200
}

func (o *ListSubjectsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsOK %s", 200, payload)
}

func (o *ListSubjectsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsOK %s", 200, payload)
}

func (o *ListSubjectsOK) GetPayload() *models.SubjectStatsListResponse {
	return o.Payload
}

func (o *ListSubjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubjectStatsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListSubjectsBadRequest creates a ListSubjectsBadRequest with default headers values
func NewListSubjectsBadRequest() *ListSubjectsBadRequest {
	return &ListSubjectsBadRequest{}
}

/*
ListSubjectsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListSubjectsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list subjects bad request response has a 2xx status code
func (o *ListSubjectsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list subjects bad request response has a 3xx status code
func (o *ListSubjectsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list subjects bad request response has a 4xx status code
func (o *ListSubjectsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list subjects bad request response has a 5xx status code
func (o *ListSubjectsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list subjects bad request response a status code equal to that given
func (o *ListSubjectsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list subjects bad request response
func (o *ListSubjectsBadRequest) Code() int {
	return 400
}

func (o *ListSubjectsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsBadRequest %s", 400, payload)
}

func (o *ListSubjectsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsBadRequest %s", 400, payload)
}

func (o *ListSubjectsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListSubjectsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListSubjectsInternalServerError creates a ListSubjectsInternalServerError with default headers values
func NewListSubjectsInternalServerError() *ListSubjectsInternalServerError {
	return &ListSubjectsInternalServerError{}
}

/*
ListSubjectsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListSubjectsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list subjects internal server error response has a 2xx status code
func (o *ListSubjectsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list subjects internal server error response has a 3xx status code
func (o *ListSubjectsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list subjects internal server error response has a 4xx status code
func (o *ListSubjectsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list subjects internal server error response has a 5xx status code
func (o *ListSubjectsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list subjects internal server error response a status code equal to that given
func (o *ListSubjectsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list subjects internal server error response
func (o *ListSubjectsInternalServerError) Code() int {
	return 500
}

func (o *ListSubjectsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsInternalServerError %s", 500, payload)
}

func (o *ListSubjectsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/subjects][%d] listSubjectsInternalServerError %s", 500, payload)
}

func (o *ListSubjectsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListSubjectsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
