// Code generated by go-swagger; DO NOT EDIT.

package subjects

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewListSubjectsParams creates a new ListSubjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSubjectsParams() *ListSubjectsParams {
	return NewListSubjectsParamsWithTimeout(cr.DefaultTimeout)
}

// NewListSubjectsParamsWithTimeout creates a new ListSubjectsParams object
// with the ability to set a timeout on a request.
func NewListSubjectsParamsWithTimeout(timeout time.Duration) *ListSubjectsParams {
	return &ListSubjectsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListSubjectsParamsWithContext creates a new ListSubjectsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListSubjectsParams].
func NewListSubjectsParamsWithContext(ctx context.Context) *ListSubjectsParams {
	return &ListSubjectsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListSubjectsParamsWithHTTPClient creates a new ListSubjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSubjectsParamsWithHTTPClient(client *http.Client) *ListSubjectsParams {
	return &ListSubjectsParams{
		HTTPClient: client,
	}
}

/*
ListSubjectsParams contains all the parameters to send to the API endpoint

	for the list subjects operation.

	Typically these are written to a http.Request.
*/
type ListSubjectsParams struct {

	/* Cursor.

	   Pagination cursor
	*/
	Cursor *string

	/* Limit.

	   Page size
	*/
	Limit *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list subjects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubjectsParams) WithDefaults() *ListSubjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list subjects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list subjects params.
func (o *ListSubjectsParams) WithTimeout(timeout time.Duration) *ListSubjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list subjects params.
func (o *ListSubjectsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list subjects params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListSubjectsParams].
func (o *ListSubjectsParams) WithContext(ctx context.Context) *ListSubjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list subjects params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListSubjectsParams].
func (o *ListSubjectsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list subjects params.
func (o *ListSubjectsParams) WithHTTPClient(client *http.Client) *ListSubjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list subjects params.
func (o *ListSubjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the list subjects params.
func (o *ListSubjectsParams) WithCursor(cursor *string) *ListSubjectsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the list subjects params.
func (o *ListSubjectsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithLimit adds the limit to the list subjects params.
func (o *ListSubjectsParams) WithLimit(limit *int64) *ListSubjectsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list subjects params.
func (o *ListSubjectsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListSubjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
