DROP INDEX IF EXISTS idx_usage_events_subject_meter_event_time_id;
DROP INDEX IF EXISTS idx_usage_events_meter_event_time_id;
DROP INDEX IF EXISTS idx_usage_events_subject_event_time_id;
DROP INDEX IF EXISTS idx_usage_events_event_time_id;
