// Code generated by go-swagger; DO NOT EDIT.

package health

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReadinessCheckReader is a Reader for the ReadinessCheck structure.
type ReadinessCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadinessCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewReadinessCheckNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewReadinessCheckServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /ready] readinessCheck", response, response.Code())
	}
}

// NewReadinessCheckNoContent creates a ReadinessCheckNoContent with default headers values
func NewReadinessCheckNoContent() *ReadinessCheckNoContent {
	return &ReadinessCheckNoContent{}
}

/*
ReadinessCheckNoContent describes a response with status code 204, with default header values.

No Content
*/
type ReadinessCheckNoContent struct {
}

// IsSuccess returns true when this readiness check no content response has a 2xx status code
func (o *ReadinessCheckNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this readiness check no content response has a 3xx status code
func (o *ReadinessCheckNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this readiness check no content response has a 4xx status code
func (o *ReadinessCheckNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this readiness check no content response has a 5xx status code
func (o *ReadinessCheckNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this readiness check no content response a status code equal to that given
func (o *ReadinessCheckNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the readiness check no content response
func (o *ReadinessCheckNoContent) Code() int {
	return 204
}

func (o *ReadinessCheckNoContent) Error() string {
	return fmt.Sprintf("[GET /ready][%d] readinessCheckNoContent", 204)
}

func (o *ReadinessCheckNoContent) String() string {
	return fmt.Sprintf("[GET /ready][%d] readinessCheckNoContent", 204)
}

func (o *ReadinessCheckNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadinessCheckServiceUnavailable creates a ReadinessCheckServiceUnavailable with default headers values
func NewReadinessCheckServiceUnavailable() *ReadinessCheckServiceUnavailable {
	return &ReadinessCheckServiceUnavailable{}
}

/*
ReadinessCheckServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable
*/
type ReadinessCheckServiceUnavailable struct {
}

// IsSuccess returns true when this readiness check service unavailable response has a 2xx status code
func (o *ReadinessCheckServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this readiness check service unavailable response has a 3xx status code
func (o *ReadinessCheckServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this readiness check service unavailable response has a 4xx status code
func (o *ReadinessCheckServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this readiness check service unavailable response has a 5xx status code
func (o *ReadinessCheckServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this readiness check service unavailable response a status code equal to that given
func (o *ReadinessCheckServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the readiness check service unavailable response
func (o *ReadinessCheckServiceUnavailable) Code() int {
	return 503
}

func (o *ReadinessCheckServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /ready][%d] readinessCheckServiceUnavailable", 503)
}

func (o *ReadinessCheckServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /ready][%d] readinessCheckServiceUnavailable", 503)
}

func (o *ReadinessCheckServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
