// Code generated by go-swagger; DO NOT EDIT.

package health

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReadinessCheckParams creates a new ReadinessCheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReadinessCheckParams() *ReadinessCheckParams {
	return NewReadinessCheckParamsWithTimeout(cr.DefaultTimeout)
}

// NewReadinessCheckParamsWithTimeout creates a new ReadinessCheckParams object
// with the ability to set a timeout on a request.
func NewReadinessCheckParamsWithTimeout(timeout time.Duration) *ReadinessCheckParams {
	return &ReadinessCheckParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewReadinessCheckParamsWithContext creates a new ReadinessCheckParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ReadinessCheckParams].
func NewReadinessCheckParamsWithContext(ctx context.Context) *ReadinessCheckParams {
	return &ReadinessCheckParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewReadinessCheckParamsWithHTTPClient creates a new ReadinessCheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewReadinessCheckParamsWithHTTPClient(client *http.Client) *ReadinessCheckParams {
	return &ReadinessCheckParams{
		HTTPClient: client,
	}
}

/*
ReadinessCheckParams contains all the parameters to send to the API endpoint

	for the readiness check operation.

	Typically these are written to a http.Request.
*/
type ReadinessCheckParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the readiness check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadinessCheckParams) WithDefaults() *ReadinessCheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the readiness check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadinessCheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the readiness check params.
func (o *ReadinessCheckParams) WithTimeout(timeout time.Duration) *ReadinessCheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the readiness check params.
func (o *ReadinessCheckParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the readiness check params.
//
// Deprecated: use the operation call with context to pass the context instead of [ReadinessCheckParams].
func (o *ReadinessCheckParams) WithContext(ctx context.Context) *ReadinessCheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the readiness check params.
//
// Deprecated: use the operation call with context to pass the context instead of [ReadinessCheckParams].
func (o *ReadinessCheckParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the readiness check params.
func (o *ReadinessCheckParams) WithHTTPClient(client *http.Client) *ReadinessCheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the readiness check params.
func (o *ReadinessCheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ReadinessCheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
