// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumption_decisions.sql

package postgresdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countConsumptionDecisionPruneRuns = `-- name: CountConsumptionDecisionPruneRuns :one
SELECT COUNT(*) FROM consumption_decision_prune_runs WHERE workspace_id = $1
`

func (q *Queries) CountConsumptionDecisionPruneRuns(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConsumptionDecisionPruneRuns, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConsumptionDecisions = `-- name: CountConsumptionDecisions :one
SELECT COUNT(*) FROM consumption_decisions WHERE workspace_id = $1
`

func (q *Queries) CountConsumptionDecisions(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConsumptionDecisions, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiredConsumptionDecisions = `-- name: CountExpiredConsumptionDecisions :one
SELECT COUNT(*) FROM consumption_decisions
WHERE workspace_id = $1 AND created_at < $2
`

type CountExpiredConsumptionDecisionsParams struct {
	WorkspaceID string
	Before      time.Time
}

func (q *Queries) CountExpiredConsumptionDecisions(ctx context.Context, arg CountExpiredConsumptionDecisionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiredConsumptionDecisions, arg.WorkspaceID, arg.Before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findConsumptionDecision = `-- name: FindConsumptionDecision :one
SELECT response, created_at
FROM consumption_decisions
WHERE workspace_id = $1
	AND idempotency_key = $2
`

type FindConsumptionDecisionParams struct {
	WorkspaceID    string
	IdempotencyKey string
}

type FindConsumptionDecisionRow struct {
	Response  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) FindConsumptionDecision(ctx context.Context, arg FindConsumptionDecisionParams) (FindConsumptionDecisionRow, error) {
	row := q.db.QueryRowContext(ctx, findConsumptionDecision, arg.WorkspaceID, arg.IdempotencyKey)
	var i FindConsumptionDecisionRow
	err := row.Scan(&i.Response, &i.CreatedAt)
	return i, err
}

const findLatestConsumptionDecisionPruneRun = `-- name: FindLatestConsumptionDecisionPruneRun :one
SELECT id, before, dry_run, deleted, created_at
FROM consumption_decision_prune_runs
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC LIMIT 1
`

type FindLatestConsumptionDecisionPruneRunRow struct {
	ID        string
	Before    time.Time
	DryRun    bool
	Deleted   int64
	CreatedAt time.Time
}

func (q *Queries) FindLatestConsumptionDecisionPruneRun(ctx context.Context, workspaceID string) (FindLatestConsumptionDecisionPruneRunRow, error) {
	row := q.db.QueryRowContext(ctx, findLatestConsumptionDecisionPruneRun, workspaceID)
	var i FindLatestConsumptionDecisionPruneRunRow
	err := row.Scan(
		&i.ID,
		&i.Before,
		&i.DryRun,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const listConsumptionDecisions = `-- name: ListConsumptionDecisions :many
SELECT idempotency_key, response, subject, meter_name, accepted, evaluation_failed, enforcement, state, created_at
FROM consumption_decisions
WHERE workspace_id = $1
	AND ($2::text = '' OR subject = $2)
	AND ($3::text = '' OR meter_name = $3)
	AND ($4::boolean IS NULL OR accepted = $4)
	AND ($5::boolean IS NULL OR evaluation_failed = $5)
	AND ($6::text = '' OR enforcement = $6)
	AND ($7::text = '' OR state = $7)
	AND ($8::timestamptz IS NULL OR created_at < $8
		OR (created_at = $8 AND idempotency_key < $9))
ORDER BY created_at DESC, idempotency_key DESC
LIMIT $10::int
`

type ListConsumptionDecisionsParams struct {
	WorkspaceID      string
	Subject          string
	MeterName        string
	Accepted         sql.NullBool
	EvaluationFailed sql.NullBool
	Enforcement      string
	State            string
	CursorCreatedAt  sql.NullTime
	CursorID         string
	Limit            int32
}

type ListConsumptionDecisionsRow struct {
	IdempotencyKey   string
	Response         json.RawMessage
	Subject          string
	MeterName        string
	Accepted         bool
	EvaluationFailed bool
	Enforcement      string
	State            string
	CreatedAt        time.Time
}

func (q *Queries) ListConsumptionDecisions(ctx context.Context, arg ListConsumptionDecisionsParams) ([]ListConsumptionDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConsumptionDecisions,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Accepted,
		arg.EvaluationFailed,
		arg.Enforcement,
		arg.State,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsumptionDecisionsRow{}
	for rows.Next() {
		var i ListConsumptionDecisionsRow
		if err := rows.Scan(
			&i.IdempotencyKey,
			&i.Response,
			&i.Subject,
			&i.MeterName,
			&i.Accepted,
			&i.EvaluationFailed,
			&i.Enforcement,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredConsumptionDecisions = `-- name: PruneExpiredConsumptionDecisions :execrows
DELETE FROM consumption_decisions
WHERE workspace_id = $1 AND created_at < $2
`

type PruneExpiredConsumptionDecisionsParams struct {
	WorkspaceID string
	Before      time.Time
}

func (q *Queries) PruneExpiredConsumptionDecisions(ctx context.Context, arg PruneExpiredConsumptionDecisionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneExpiredConsumptionDecisions, arg.WorkspaceID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveConsumptionDecision = `-- name: SaveConsumptionDecision :execrows
INSERT INTO consumption_decisions (workspace_id, idempotency_key, response, subject, meter_name, accepted, evaluation_failed, enforcement, state, created_at)
VALUES ($1, $2, $3::jsonb, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT DO NOTHING
`

type SaveConsumptionDecisionParams struct {
	WorkspaceID      string
	IdempotencyKey   string
	Response         json.RawMessage
	Subject          string
	MeterName        string
	Accepted         bool
	EvaluationFailed bool
	Enforcement      string
	State            string
	CreatedAt        time.Time
}

func (q *Queries) SaveConsumptionDecision(ctx context.Context, arg SaveConsumptionDecisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveConsumptionDecision,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.Response,
		arg.Subject,
		arg.MeterName,
		arg.Accepted,
		arg.EvaluationFailed,
		arg.Enforcement,
		arg.State,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveConsumptionDecisionPruneRun = `-- name: SaveConsumptionDecisionPruneRun :exec
INSERT INTO consumption_decision_prune_runs (id, workspace_id, before, dry_run, deleted, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveConsumptionDecisionPruneRunParams struct {
	ID          string
	WorkspaceID string
	Before      time.Time
	DryRun      bool
	Deleted     int64
	CreatedAt   time.Time
}

func (q *Queries) SaveConsumptionDecisionPruneRun(ctx context.Context, arg SaveConsumptionDecisionPruneRunParams) error {
	_, err := q.db.ExecContext(ctx, saveConsumptionDecisionPruneRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Before,
		arg.DryRun,
		arg.Deleted,
		arg.CreatedAt,
	)
	return err
}
