// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meters.sql

package postgresdb

import (
	"context"
	"database/sql"
)

const countMeters = `-- name: CountMeters :one
SELECT COUNT(*)
FROM meters
`

func (q *Queries) CountMeters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMeters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageEventsForMeter = `-- name: CountUsageEventsForMeter :one
SELECT COUNT(*)
FROM usage_events
WHERE meter_name = $1
`

func (q *Queries) CountUsageEventsForMeter(ctx context.Context, meterName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsageEventsForMeter, meterName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMeter = `-- name: DeleteMeter :exec
DELETE FROM meters
WHERE id = $1
`

func (q *Queries) DeleteMeter(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMeter, id)
	return err
}

const listMeters = `-- name: ListMeters :many
SELECT id, name, description, unit, aggregation, metadata_schema, dimensions, event_retention_days, created_at
FROM meters
WHERE ($1::text IS NULL OR id = $1::text)
	AND ($2::text IS NULL OR name = $2::text)
	AND ($3::text IS NULL OR name > $3::text)
ORDER BY name
LIMIT $4::int
`

type ListMetersParams struct {
	ID     sql.NullString
	Name   sql.NullString
	Cursor sql.NullString
	Limit  int32
}

type ListMetersRow struct {
	ID                 string
	Name               string
	Description        string
	Unit               string
	Aggregation        string
	MetadataSchema     string
	Dimensions         string
	EventRetentionDays int32
	CreatedAt          string
}

func (q *Queries) ListMeters(ctx context.Context, arg ListMetersParams) ([]ListMetersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeters,
		arg.ID,
		arg.Name,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetersRow{}
	for rows.Next() {
		var i ListMetersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Aggregation,
			&i.MetadataSchema,
			&i.Dimensions,
			&i.EventRetentionDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMeter = `-- name: SaveMeter :exec
INSERT INTO meters (id, name, description, unit, aggregation, metadata_schema, dimensions, event_retention_days, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT(id) DO UPDATE SET
	description = excluded.description,
	unit = excluded.unit,
	aggregation = excluded.aggregation,
	metadata_schema = excluded.metadata_schema,
	dimensions = excluded.dimensions,
	event_retention_days = excluded.event_retention_days
`

type SaveMeterParams struct {
	ID                 string
	Name               string
	Description        string
	Unit               string
	Aggregation        string
	MetadataSchema     string
	Dimensions         string
	EventRetentionDays int32
	CreatedAt          string
}

func (q *Queries) SaveMeter(ctx context.Context, arg SaveMeterParams) error {
	_, err := q.db.ExecContext(ctx, saveMeter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.Aggregation,
		arg.MetadataSchema,
		arg.Dimensions,
		arg.EventRetentionDays,
		arg.CreatedAt,
	)
	return err
}
