// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"database/sql"
)

type AlertEvaluationJob struct {
	RuleID      string
	RunAfter    string
	LockedUntil sql.NullString
	Attempts    int32
	CreatedAt   string
	UpdatedAt   string
}

type AlertState struct {
	RuleID      string
	GroupKey    string
	GroupValue  string
	Status      string
	Value       float64
	Message     string
	EvaluatedAt sql.NullString
	UpdatedAt   string
}

type AuthIdentity struct {
	ID            string
	UserID        string
	Provider      string
	Subject       string
	Email         string
	EmailVerified bool
	CreatedAt     string
	UpdatedAt     string
}

type AuthUser struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}

type AuthWorkspace struct {
	ID        string
	Name      string
	CreatedAt string
}
