// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package postgresdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimReconciliationNotification = `-- name: ClaimReconciliationNotification :one
WITH due AS (
	SELECT id FROM reconciliation_notifications
	WHERE status = 'pending' AND next_attempt_at <= $2::timestamptz
		AND (locked_until IS NULL OR locked_until <= $2::timestamptz)
	ORDER BY next_attempt_at, id
	FOR UPDATE SKIP LOCKED
	LIMIT 1
)
UPDATE reconciliation_notifications n
SET locked_until = $1::timestamptz
FROM due
WHERE n.id = due.id
RETURNING n.id, n.workspace_id, n.event_type, n.fingerprint, n.payload,
	n.status, n.attempts, n.next_attempt_at, n.last_error, n.created_at, n.delivered_at,
	(SELECT COUNT(*) FROM reconciliation_notification_attempts a WHERE a.notification_id = n.id) AS total_attempts
`

type ClaimReconciliationNotificationParams struct {
	LockedUntil time.Time
	Now         time.Time
}

type ClaimReconciliationNotificationRow struct {
	ID            string
	WorkspaceID   string
	EventType     string
	Fingerprint   string
	Payload       json.RawMessage
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastError     string
	CreatedAt     time.Time
	DeliveredAt   sql.NullTime
	TotalAttempts int64
}

func (q *Queries) ClaimReconciliationNotification(ctx context.Context, arg ClaimReconciliationNotificationParams) (ClaimReconciliationNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, claimReconciliationNotification, arg.LockedUntil, arg.Now)
	var i ClaimReconciliationNotificationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EventType,
		&i.Fingerprint,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.TotalAttempts,
	)
	return i, err
}

const claimReconciliationSchedule = `-- name: ClaimReconciliationSchedule :one
WITH due AS (
	SELECT workspace_id
	FROM reconciliation_schedules
	WHERE next_run_at <= $2::timestamptz
		AND (locked_until IS NULL OR locked_until <= $2::timestamptz)
	ORDER BY next_run_at, workspace_id
	FOR UPDATE SKIP LOCKED
	LIMIT 1
)
UPDATE reconciliation_schedules s
SET locked_until = $1::timestamptz,
	updated_at = $2::timestamptz
FROM due
WHERE s.workspace_id = due.workspace_id
RETURNING s.workspace_id, s.last_fingerprint, s.last_notified_fingerprint, s.last_failure_fingerprint
`

type ClaimReconciliationScheduleParams struct {
	LockedUntil time.Time
	Now         time.Time
}

type ClaimReconciliationScheduleRow struct {
	WorkspaceID             string
	LastFingerprint         string
	LastNotifiedFingerprint string
	LastFailureFingerprint  string
}

func (q *Queries) ClaimReconciliationSchedule(ctx context.Context, arg ClaimReconciliationScheduleParams) (ClaimReconciliationScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, claimReconciliationSchedule, arg.LockedUntil, arg.Now)
	var i ClaimReconciliationScheduleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.LastFingerprint,
		&i.LastNotifiedFingerprint,
		&i.LastFailureFingerprint,
	)
	return i, err
}

const completeReconciliationNotification = `-- name: CompleteReconciliationNotification :exec
UPDATE reconciliation_notifications
SET status = 'delivered', attempts = attempts + 1, locked_until = NULL,
	last_error = '', delivered_at = $1::timestamptz
WHERE id = $2
`

type CompleteReconciliationNotificationParams struct {
	DeliveredAt time.Time
	ID          string
}

func (q *Queries) CompleteReconciliationNotification(ctx context.Context, arg CompleteReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, completeReconciliationNotification, arg.DeliveredAt, arg.ID)
	return err
}

const completeReconciliationSchedule = `-- name: CompleteReconciliationSchedule :exec
UPDATE reconciliation_schedules
SET next_run_at = $1::timestamptz,
	locked_until = NULL,
	last_fingerprint = $2,
	last_notified_fingerprint = CASE WHEN $2::text = '' THEN '' ELSE last_notified_fingerprint END,
	last_failure_fingerprint = '',
	updated_at = $3::timestamptz
WHERE workspace_id = $4
`

type CompleteReconciliationScheduleParams struct {
	NextRunAt   time.Time
	Fingerprint string
	UpdatedAt   time.Time
	WorkspaceID string
}

func (q *Queries) CompleteReconciliationSchedule(ctx context.Context, arg CompleteReconciliationScheduleParams) error {
	_, err := q.db.ExecContext(ctx, completeReconciliationSchedule,
		arg.NextRunAt,
		arg.Fingerprint,
		arg.UpdatedAt,
		arg.WorkspaceID,
	)
	return err
}

const countReconciliationNotificationStates = `-- name: CountReconciliationNotificationStates :one
SELECT
	COUNT(*) FILTER (WHERE status = 'pending') AS pending,
	COUNT(*) FILTER (WHERE status = 'dead_letter') AS dead_letter
FROM reconciliation_notifications
WHERE workspace_id = $1
`

type CountReconciliationNotificationStatesRow struct {
	Pending    int64
	DeadLetter int64
}

func (q *Queries) CountReconciliationNotificationStates(ctx context.Context, workspaceID string) (CountReconciliationNotificationStatesRow, error) {
	row := q.db.QueryRowContext(ctx, countReconciliationNotificationStates, workspaceID)
	var i CountReconciliationNotificationStatesRow
	err := row.Scan(&i.Pending, &i.DeadLetter)
	return i, err
}

const deleteEntitlementCounterForRepair = `-- name: DeleteEntitlementCounterForRepair :execrows
DELETE FROM entitlement_usage_counters
WHERE workspace_id = $1::text
	AND subject = $2::text
	AND meter_name = $3::text
	AND period = $4::text
	AND period_start = $5::text
	AND updated_at = $6::text
`

type DeleteEntitlementCounterForRepairParams struct {
	WorkspaceID       string
	Subject           string
	MeterName         string
	Period            string
	PeriodStart       string
	ExpectedUpdatedAt string
}

func (q *Queries) DeleteEntitlementCounterForRepair(ctx context.Context, arg DeleteEntitlementCounterForRepairParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntitlementCounterForRepair,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueAlertWorkerDeadLetter = `-- name: EnqueueAlertWorkerDeadLetter :execrows
INSERT INTO alert_evaluation_jobs (rule_id, run_after, locked_until, attempts, created_at, updated_at)
SELECT d.rule_id, $1::text, NULL, 0, $1::text, $1::text
FROM system_worker_dead_letters d
JOIN alert_rules r ON r.id = d.rule_id AND r.workspace_id = d.workspace_id
WHERE d.workspace_id = $2::text AND d.public_id = $3::uuid
	AND d.worker_name = 'alert' AND d.status = 'dead_letter'
ON CONFLICT(rule_id) DO UPDATE SET run_after = EXCLUDED.run_after, locked_until = NULL, attempts = 0, updated_at = EXCLUDED.updated_at
`

type EnqueueAlertWorkerDeadLetterParams struct {
	Now         string
	WorkspaceID string
	PublicID    uuid.UUID
}

func (q *Queries) EnqueueAlertWorkerDeadLetter(ctx context.Context, arg EnqueueAlertWorkerDeadLetterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueAlertWorkerDeadLetter, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueEntitlementWorkerDeadLetter = `-- name: EnqueueEntitlementWorkerDeadLetter :execrows
INSERT INTO entitlement_check_jobs (workspace_id, subject, meter_name, run_after, locked_until, attempts, created_at, updated_at)
SELECT d.workspace_id, d.subject, d.meter_name, $1::text, NULL, 0, $1::text, $1::text
FROM system_worker_dead_letters d
JOIN meters m ON m.workspace_id = d.workspace_id AND m.name = d.meter_name
WHERE d.workspace_id = $2::text AND d.public_id = $3::uuid
	AND d.worker_name = 'entitlement' AND d.status = 'dead_letter'
ON CONFLICT(workspace_id, subject, meter_name) DO UPDATE SET run_after = EXCLUDED.run_after, locked_until = NULL, attempts = 0, updated_at = EXCLUDED.updated_at
`

type EnqueueEntitlementWorkerDeadLetterParams struct {
	Now         string
	WorkspaceID string
	PublicID    uuid.UUID
}

func (q *Queries) EnqueueEntitlementWorkerDeadLetter(ctx context.Context, arg EnqueueEntitlementWorkerDeadLetterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueEntitlementWorkerDeadLetter, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureReconciliationSchedules = `-- name: EnsureReconciliationSchedules :exec
INSERT INTO reconciliation_schedules (workspace_id, next_run_at, updated_at)
SELECT id, $1::timestamptz, $1::timestamptz
FROM auth_workspaces
ON CONFLICT (workspace_id) DO NOTHING
`

func (q *Queries) EnsureReconciliationSchedules(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, ensureReconciliationSchedules, now)
	return err
}

const failReconciliationSchedule = `-- name: FailReconciliationSchedule :exec
UPDATE reconciliation_schedules
SET next_run_at = $1::timestamptz,
	locked_until = NULL,
	last_failure_fingerprint = $2,
	updated_at = $3::timestamptz
WHERE workspace_id = $4
`

type FailReconciliationScheduleParams struct {
	NextRunAt          time.Time
	FailureFingerprint string
	UpdatedAt          time.Time
	WorkspaceID        string
}

func (q *Queries) FailReconciliationSchedule(ctx context.Context, arg FailReconciliationScheduleParams) error {
	_, err := q.db.ExecContext(ctx, failReconciliationSchedule,
		arg.NextRunAt,
		arg.FailureFingerprint,
		arg.UpdatedAt,
		arg.WorkspaceID,
	)
	return err
}

const getEntitlementCounterForRepair = `-- name: GetEntitlementCounterForRepair :one
SELECT c.subject, c.meter_name, c.period, c.period_start, c.period_end,
	c.event_count, c.quantity_sum, c.quantity_min, c.quantity_max,
	c.first_quantity, c.first_event_time, c.last_quantity, c.last_event_time, c.updated_at,
	m.event_retention_days
FROM entitlement_usage_counters c
JOIN meters m ON m.workspace_id = c.workspace_id AND m.name = c.meter_name
WHERE c.workspace_id = $1::text
	AND c.subject = $2::text
	AND c.meter_name = $3::text
	AND c.period = $4::text
	AND c.period_start = $5::text
FOR UPDATE OF c
`

type GetEntitlementCounterForRepairParams struct {
	WorkspaceID string
	Subject     string
	MeterName   string
	Period      string
	PeriodStart string
}

type GetEntitlementCounterForRepairRow struct {
	Subject            string
	MeterName          string
	Period             string
	PeriodStart        string
	PeriodEnd          string
	EventCount         int64
	QuantitySum        float64
	QuantityMin        float64
	QuantityMax        float64
	FirstQuantity      float64
	FirstEventTime     string
	LastQuantity       float64
	LastEventTime      string
	UpdatedAt          string
	EventRetentionDays int32
}

func (q *Queries) GetEntitlementCounterForRepair(ctx context.Context, arg GetEntitlementCounterForRepairParams) (GetEntitlementCounterForRepairRow, error) {
	row := q.db.QueryRowContext(ctx, getEntitlementCounterForRepair,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
	)
	var i GetEntitlementCounterForRepairRow
	err := row.Scan(
		&i.Subject,
		&i.MeterName,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EventCount,
		&i.QuantitySum,
		&i.QuantityMin,
		&i.QuantityMax,
		&i.FirstQuantity,
		&i.FirstEventTime,
		&i.LastQuantity,
		&i.LastEventTime,
		&i.UpdatedAt,
		&i.EventRetentionDays,
	)
	return i, err
}

const getReconciliationSchedule = `-- name: GetReconciliationSchedule :one
SELECT next_run_at, locked_until, updated_at
FROM reconciliation_schedules
WHERE workspace_id = $1
`

type GetReconciliationScheduleRow struct {
	NextRunAt   time.Time
	LockedUntil sql.NullTime
	UpdatedAt   time.Time
}

func (q *Queries) GetReconciliationSchedule(ctx context.Context, workspaceID string) (GetReconciliationScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getReconciliationSchedule, workspaceID)
	var i GetReconciliationScheduleRow
	err := row.Scan(&i.NextRunAt, &i.LockedUntil, &i.UpdatedAt)
	return i, err
}

const getWorkerDeadLetter = `-- name: GetWorkerDeadLetter :one
SELECT public_id, worker_name, job_key, rule_id, subject, meter_name, attempts, last_error, status, created_at, requeued_at
FROM system_worker_dead_letters
WHERE workspace_id = $1::text AND public_id = $2::uuid
`

type GetWorkerDeadLetterParams struct {
	WorkspaceID string
	PublicID    uuid.UUID
}

type GetWorkerDeadLetterRow struct {
	PublicID   uuid.UUID
	WorkerName string
	JobKey     string
	RuleID     string
	Subject    string
	MeterName  string
	Attempts   int32
	LastError  string
	Status     string
	CreatedAt  time.Time
	RequeuedAt sql.NullTime
}

func (q *Queries) GetWorkerDeadLetter(ctx context.Context, arg GetWorkerDeadLetterParams) (GetWorkerDeadLetterRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkerDeadLetter, arg.WorkspaceID, arg.PublicID)
	var i GetWorkerDeadLetterRow
	err := row.Scan(
		&i.PublicID,
		&i.WorkerName,
		&i.JobKey,
		&i.RuleID,
		&i.Subject,
		&i.MeterName,
		&i.Attempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.RequeuedAt,
	)
	return i, err
}

const listActiveEntitlementCounters = `-- name: ListActiveEntitlementCounters :many
SELECT c.subject, c.meter_name, c.period, c.period_start, c.period_end,
	c.event_count, c.quantity_sum, c.quantity_min, c.quantity_max, c.updated_at,
	m.event_retention_days
FROM entitlement_usage_counters c
JOIN meters m ON m.workspace_id = c.workspace_id AND m.name = c.meter_name
WHERE c.workspace_id = $1::text
	AND c.period_start::timestamptz <= $2::timestamptz
	AND c.period_end::timestamptz > $2::timestamptz
ORDER BY c.updated_at DESC, c.subject, c.meter_name, c.period
LIMIT $3::int
`

type ListActiveEntitlementCountersParams struct {
	WorkspaceID string
	Now         time.Time
	Limit       int32
}

type ListActiveEntitlementCountersRow struct {
	Subject            string
	MeterName          string
	Period             string
	PeriodStart        string
	PeriodEnd          string
	EventCount         int64
	QuantitySum        float64
	QuantityMin        float64
	QuantityMax        float64
	UpdatedAt          string
	EventRetentionDays int32
}

func (q *Queries) ListActiveEntitlementCounters(ctx context.Context, arg ListActiveEntitlementCountersParams) ([]ListActiveEntitlementCountersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEntitlementCounters, arg.WorkspaceID, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEntitlementCountersRow{}
	for rows.Next() {
		var i ListActiveEntitlementCountersRow
		if err := rows.Scan(
			&i.Subject,
			&i.MeterName,
			&i.Period,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EventCount,
			&i.QuantitySum,
			&i.QuantityMin,
			&i.QuantityMax,
			&i.UpdatedAt,
			&i.EventRetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterReconciliationAssignments = `-- name: ListCounterReconciliationAssignments :many
SELECT id, assigned_at, period_anchor_at, unassigned_at
FROM plan_subject_assignments
WHERE workspace_id = $1::text
	AND subject = $2::text
	AND assigned_at::timestamptz < $3::timestamptz
	AND (unassigned_at IS NULL OR unassigned_at::timestamptz > $4::timestamptz)
ORDER BY assigned_at DESC, id DESC
`

type ListCounterReconciliationAssignmentsParams struct {
	WorkspaceID string
	Subject     string
	WindowEnd   time.Time
	WindowStart time.Time
}

type ListCounterReconciliationAssignmentsRow struct {
	ID             string
	AssignedAt     string
	PeriodAnchorAt string
	UnassignedAt   sql.NullString
}

func (q *Queries) ListCounterReconciliationAssignments(ctx context.Context, arg ListCounterReconciliationAssignmentsParams) ([]ListCounterReconciliationAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterReconciliationAssignments,
		arg.WorkspaceID,
		arg.Subject,
		arg.WindowEnd,
		arg.WindowStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterReconciliationAssignmentsRow{}
	for rows.Next() {
		var i ListCounterReconciliationAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignedAt,
			&i.PeriodAnchorAt,
			&i.UnassignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterReconciliationEvents = `-- name: ListCounterReconciliationEvents :many
SELECT id, quantity, event_time, received_at
FROM usage_events
WHERE workspace_id = $1::text
	AND subject = $2::text
	AND meter_name = $3::text
	AND event_time::timestamptz >= $4::timestamptz
	AND event_time::timestamptz < $5::timestamptz
ORDER BY received_at, id
`

type ListCounterReconciliationEventsParams struct {
	WorkspaceID string
	Subject     string
	MeterName   string
	PeriodStart time.Time
	PeriodEnd   time.Time
}

type ListCounterReconciliationEventsRow struct {
	ID         string
	Quantity   float64
	EventTime  string
	ReceivedAt string
}

func (q *Queries) ListCounterReconciliationEvents(ctx context.Context, arg ListCounterReconciliationEventsParams) ([]ListCounterReconciliationEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterReconciliationEvents,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterReconciliationEventsRow{}
	for rows.Next() {
		var i ListCounterReconciliationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.EventTime,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionReconciliationRows = `-- name: ListDecisionReconciliationRows :many
SELECT d.idempotency_key, d.subject, d.meter_name, d.accepted, d.created_at,
	e.id AS event_id, e.subject AS event_subject, e.meter_name AS event_meter_name
FROM consumption_decisions d
LEFT JOIN usage_events e
	ON e.workspace_id = d.workspace_id AND e.idempotency_key = d.idempotency_key
WHERE d.workspace_id = $1::text
	AND d.created_at >= $2::timestamptz
ORDER BY d.created_at DESC, d.idempotency_key DESC
LIMIT $3::int
`

type ListDecisionReconciliationRowsParams struct {
	WorkspaceID string
	Since       time.Time
	Limit       int32
}

type ListDecisionReconciliationRowsRow struct {
	IdempotencyKey string
	Subject        string
	MeterName      string
	Accepted       bool
	CreatedAt      time.Time
	EventID        sql.NullString
	EventSubject   sql.NullString
	EventMeterName sql.NullString
}

func (q *Queries) ListDecisionReconciliationRows(ctx context.Context, arg ListDecisionReconciliationRowsParams) ([]ListDecisionReconciliationRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionReconciliationRows, arg.WorkspaceID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecisionReconciliationRowsRow{}
	for rows.Next() {
		var i ListDecisionReconciliationRowsRow
		if err := rows.Scan(
			&i.IdempotencyKey,
			&i.Subject,
			&i.MeterName,
			&i.Accepted,
			&i.CreatedAt,
			&i.EventID,
			&i.EventSubject,
			&i.EventMeterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaCounterRepairRuns = `-- name: ListQuotaCounterRepairRuns :many
SELECT id, subject, meter_name, period, period_start, period_end, dry_run, applied,
	before_snapshot, after_snapshot, counter_updated_at, created_at
FROM quota_counter_repair_runs
WHERE workspace_id = $1::text
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListQuotaCounterRepairRunsParams struct {
	WorkspaceID string
	Limit       int32
}

type ListQuotaCounterRepairRunsRow struct {
	ID               string
	Subject          string
	MeterName        string
	Period           string
	PeriodStart      string
	PeriodEnd        string
	DryRun           bool
	Applied          bool
	BeforeSnapshot   json.RawMessage
	AfterSnapshot    json.RawMessage
	CounterUpdatedAt string
	CreatedAt        time.Time
}

func (q *Queries) ListQuotaCounterRepairRuns(ctx context.Context, arg ListQuotaCounterRepairRunsParams) ([]ListQuotaCounterRepairRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuotaCounterRepairRuns, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotaCounterRepairRunsRow{}
	for rows.Next() {
		var i ListQuotaCounterRepairRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.MeterName,
			&i.Period,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DryRun,
			&i.Applied,
			&i.BeforeSnapshot,
			&i.AfterSnapshot,
			&i.CounterUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationNotificationAttempts = `-- name: ListReconciliationNotificationAttempts :many
SELECT id, attempt, status, error, created_at
FROM reconciliation_notification_attempts
WHERE notification_id = $1
ORDER BY created_at, id
`

type ListReconciliationNotificationAttemptsRow struct {
	ID        string
	Attempt   int32
	Status    string
	Error     string
	CreatedAt time.Time
}

func (q *Queries) ListReconciliationNotificationAttempts(ctx context.Context, notificationID string) ([]ListReconciliationNotificationAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationNotificationAttempts, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationNotificationAttemptsRow{}
	for rows.Next() {
		var i ListReconciliationNotificationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationNotifications = `-- name: ListReconciliationNotifications :many
SELECT id, event_type, fingerprint, payload, status, attempts, next_attempt_at,
	locked_until, last_error, created_at, delivered_at
FROM reconciliation_notifications
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListReconciliationNotificationsParams struct {
	WorkspaceID string
	Limit       int32
}

type ListReconciliationNotificationsRow struct {
	ID            string
	EventType     string
	Fingerprint   string
	Payload       json.RawMessage
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LockedUntil   sql.NullTime
	LastError     string
	CreatedAt     time.Time
	DeliveredAt   sql.NullTime
}

func (q *Queries) ListReconciliationNotifications(ctx context.Context, arg ListReconciliationNotificationsParams) ([]ListReconciliationNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationNotifications, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationNotificationsRow{}
	for rows.Next() {
		var i ListReconciliationNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Fingerprint,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationRuns = `-- name: ListReconciliationRuns :many
SELECT id, status, decisions_checked, counters_checked, issue_count, truncated,
	lookback_hours, duration_ms, fingerprint, issues, error, created_at
FROM reconciliation_runs
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListReconciliationRunsParams struct {
	WorkspaceID string
	Limit       int32
}

type ListReconciliationRunsRow struct {
	ID               string
	Status           string
	DecisionsChecked int32
	CountersChecked  int32
	IssueCount       int32
	Truncated        bool
	LookbackHours    int32
	DurationMs       int64
	Fingerprint      string
	Issues           json.RawMessage
	Error            string
	CreatedAt        time.Time
}

func (q *Queries) ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]ListReconciliationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationRuns, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationRunsRow{}
	for rows.Next() {
		var i ListReconciliationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.DecisionsChecked,
			&i.CountersChecked,
			&i.IssueCount,
			&i.Truncated,
			&i.LookbackHours,
			&i.DurationMs,
			&i.Fingerprint,
			&i.Issues,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerDeadLetters = `-- name: ListWorkerDeadLetters :many
SELECT public_id, worker_name, job_key, rule_id, subject, meter_name, attempts, last_error, status, created_at, requeued_at
FROM system_worker_dead_letters
WHERE workspace_id = $1::text
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListWorkerDeadLettersParams struct {
	WorkspaceID string
	Limit       int32
}

type ListWorkerDeadLettersRow struct {
	PublicID   uuid.UUID
	WorkerName string
	JobKey     string
	RuleID     string
	Subject    string
	MeterName  string
	Attempts   int32
	LastError  string
	Status     string
	CreatedAt  time.Time
	RequeuedAt sql.NullTime
}

func (q *Queries) ListWorkerDeadLetters(ctx context.Context, arg ListWorkerDeadLettersParams) ([]ListWorkerDeadLettersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerDeadLetters, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerDeadLettersRow{}
	for rows.Next() {
		var i ListWorkerDeadLettersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.WorkerName,
			&i.JobKey,
			&i.RuleID,
			&i.Subject,
			&i.MeterName,
			&i.Attempts,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.RequeuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerDiagnostics = `-- name: ListWorkerDiagnostics :many
SELECT 'export'::text AS worker_name,
	COUNT(*) FILTER (WHERE status = 'queued' OR (status = 'running' AND locked_until::timestamptz < $1::timestamptz)) AS pending_jobs,
	COUNT(*) FILTER (WHERE status = 'running' AND locked_until::timestamptz >= $1::timestamptz) AS running_jobs,
	COUNT(*) FILTER (WHERE status = 'failed') AS failed_jobs,
	COALESCE(MIN(created_at) FILTER (WHERE status = 'queued' OR (status = 'running' AND locked_until::timestamptz < $1::timestamptz)), '') AS oldest_pending_at,
	COALESCE(MAX(completed_at) FILTER (WHERE status = 'completed'), '') AS last_success_at,
	COALESCE(MAX(updated_at) FILTER (WHERE status = 'failed'), '') AS last_failure_at
FROM usage_export_jobs
UNION ALL
SELECT 'alert',
	(SELECT COUNT(*) FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE (j.locked_until IS NULL OR j.locked_until::timestamptz < $1::timestamptz) AND ($2::text = '' OR r.workspace_id = $2::text))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE (status = 'pending' OR (status = 'running' AND (locked_until IS NULL OR locked_until < $1::timestamptz))) AND ($2::text = '' OR workspace_id = $2::text)),
	(SELECT COUNT(*) FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE j.locked_until::timestamptz >= $1::timestamptz AND ($2::text = '' OR r.workspace_id = $2::text))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE status = 'running' AND locked_until >= $1::timestamptz AND ($2::text = '' OR workspace_id = $2::text)),
	(SELECT COUNT(*) FROM system_worker_dead_letters WHERE worker_name = 'alert' AND status = 'dead_letter' AND ($2::text = '' OR workspace_id = $2::text))
		+ (SELECT COUNT(*) FROM alert_delivery_jobs WHERE status = 'dead_letter' AND ($2::text = '' OR workspace_id = $2::text)),
	COALESCE((SELECT MIN(pending_at) FROM (
		SELECT j.created_at AS pending_at FROM alert_evaluation_jobs j JOIN alert_rules r ON r.id = j.rule_id WHERE (j.locked_until IS NULL OR j.locked_until::timestamptz < $1::timestamptz) AND ($2::text = '' OR r.workspace_id = $2::text)
		UNION ALL
		SELECT created_at::text FROM alert_delivery_jobs WHERE (status = 'pending' OR (status = 'running' AND (locked_until IS NULL OR locked_until < $1::timestamptz))) AND ($2::text = '' OR workspace_id = $2::text)
	) pending), ''),
	GREATEST(COALESCE((SELECT MAX(s.evaluated_at) FROM alert_states s JOIN alert_rules r ON r.id = s.rule_id WHERE $2::text = '' OR r.workspace_id = $2::text), ''), COALESCE((SELECT MAX(delivered_at)::text FROM alert_delivery_jobs WHERE $2::text = '' OR workspace_id = $2::text), '')),
	GREATEST(COALESCE((SELECT MAX(created_at)::text FROM system_worker_dead_letters WHERE worker_name = 'alert' AND status = 'dead_letter' AND ($2::text = '' OR workspace_id = $2::text)), ''), COALESCE((SELECT MAX(updated_at)::text FROM alert_delivery_jobs WHERE status = 'dead_letter' AND ($2::text = '' OR workspace_id = $2::text)), ''))
UNION ALL
SELECT 'entitlement',
	COUNT(*) FILTER (WHERE locked_until IS NULL OR locked_until::timestamptz < $1::timestamptz),
	COUNT(*) FILTER (WHERE locked_until::timestamptz >= $1::timestamptz),
	(SELECT COUNT(*) FROM system_worker_dead_letters WHERE worker_name = 'entitlement' AND status = 'dead_letter'),
	COALESCE(MIN(created_at) FILTER (WHERE locked_until IS NULL OR locked_until::timestamptz < $1::timestamptz), ''),
	COALESCE((SELECT MAX(evaluated_at) FROM entitlement_states), ''),
	COALESCE((SELECT MAX(created_at)::text FROM system_worker_dead_letters WHERE worker_name = 'entitlement' AND status = 'dead_letter'), '')
FROM entitlement_check_jobs
UNION ALL
SELECT 'retention', 0, 0, 0, '',
	GREATEST(COALESCE((SELECT MAX(created_at) FROM usage_prune_runs), ''), COALESCE((SELECT MAX(created_at)::text FROM consumption_decision_prune_runs), '')), ''
UNION ALL
SELECT 'reconciliation',
	COUNT(*) FILTER (WHERE status = 'pending' AND (locked_until IS NULL OR locked_until < $1::timestamptz))
		+ (SELECT COUNT(*) FROM reconciliation_schedules s WHERE s.next_run_at <= $1::timestamptz AND (s.locked_until IS NULL OR s.locked_until < $1::timestamptz)),
	COUNT(*) FILTER (WHERE status = 'pending' AND locked_until >= $1::timestamptz)
		+ (SELECT COUNT(*) FROM reconciliation_schedules s WHERE s.locked_until >= $1::timestamptz),
	COUNT(*) FILTER (WHERE status = 'dead_letter'),
	COALESCE((SELECT MIN(pending_at)::text FROM (
		SELECT created_at AS pending_at FROM reconciliation_notifications WHERE status = 'pending' AND (locked_until IS NULL OR locked_until < $1::timestamptz)
		UNION ALL
		SELECT next_run_at FROM reconciliation_schedules WHERE next_run_at <= $1::timestamptz AND (locked_until IS NULL OR locked_until < $1::timestamptz)
	) pending), ''),
	COALESCE((SELECT MAX(created_at)::text FROM reconciliation_runs WHERE status IN ('healthy', 'drift_detected')), ''),
	GREATEST(
		COALESCE((SELECT MAX(created_at)::text FROM reconciliation_runs WHERE status = 'failed'), ''),
		COALESCE((SELECT MAX(created_at)::text FROM reconciliation_notification_attempts WHERE status = 'failed'), '')
	)
FROM reconciliation_notifications
`

type ListWorkerDiagnosticsParams struct {
	Now         time.Time
	WorkspaceID string
}

type ListWorkerDiagnosticsRow struct {
	WorkerName      string
	PendingJobs     int64
	RunningJobs     int64
	FailedJobs      int64
	OldestPendingAt interface{}
	LastSuccessAt   interface{}
	LastFailureAt   interface{}
}

func (q *Queries) ListWorkerDiagnostics(ctx context.Context, arg ListWorkerDiagnosticsParams) ([]ListWorkerDiagnosticsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerDiagnostics, arg.Now, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerDiagnosticsRow{}
	for rows.Next() {
		var i ListWorkerDiagnosticsRow
		if err := rows.Scan(
			&i.WorkerName,
			&i.PendingJobs,
			&i.RunningJobs,
			&i.FailedJobs,
			&i.OldestPendingAt,
			&i.LastSuccessAt,
			&i.LastFailureAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerHeartbeats = `-- name: ListWorkerHeartbeats :many
SELECT worker_name, started_at, last_heartbeat_at
FROM system_worker_heartbeats
ORDER BY worker_name ASC
`

func (q *Queries) ListWorkerHeartbeats(ctx context.Context) ([]SystemWorkerHeartbeat, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemWorkerHeartbeat{}
	for rows.Next() {
		var i SystemWorkerHeartbeat
		if err := rows.Scan(&i.WorkerName, &i.StartedAt, &i.LastHeartbeatAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReconciliationNotified = `-- name: MarkReconciliationNotified :exec
UPDATE reconciliation_schedules
SET last_notified_fingerprint = $1, updated_at = $2::timestamptz
WHERE workspace_id = $3 AND last_fingerprint = $1
`

type MarkReconciliationNotifiedParams struct {
	Fingerprint string
	UpdatedAt   time.Time
	WorkspaceID string
}

func (q *Queries) MarkReconciliationNotified(ctx context.Context, arg MarkReconciliationNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, markReconciliationNotified, arg.Fingerprint, arg.UpdatedAt, arg.WorkspaceID)
	return err
}

const markWorkerDeadLetterRequeued = `-- name: MarkWorkerDeadLetterRequeued :execrows
UPDATE system_worker_dead_letters
SET status = 'requeued', requeued_at = $1::timestamptz
WHERE workspace_id = $2::text AND public_id = $3::uuid AND status = 'dead_letter'
`

type MarkWorkerDeadLetterRequeuedParams struct {
	Now         time.Time
	WorkspaceID string
	PublicID    uuid.UUID
}

func (q *Queries) MarkWorkerDeadLetterRequeued(ctx context.Context, arg MarkWorkerDeadLetterRequeuedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWorkerDeadLetterRequeued, arg.Now, arg.WorkspaceID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueReconciliationNotification = `-- name: RequeueReconciliationNotification :execrows
UPDATE reconciliation_notifications
SET status = 'pending', attempts = 0, next_attempt_at = $1::timestamptz,
	locked_until = NULL, last_error = '', delivered_at = NULL
WHERE id = $2 AND workspace_id = $3 AND status = 'dead_letter'
`

type RequeueReconciliationNotificationParams struct {
	NextAttemptAt time.Time
	ID            string
	WorkspaceID   string
}

func (q *Queries) RequeueReconciliationNotification(ctx context.Context, arg RequeueReconciliationNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueReconciliationNotification, arg.NextAttemptAt, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryReconciliationNotification = `-- name: RetryReconciliationNotification :exec
UPDATE reconciliation_notifications
SET status = CASE WHEN attempts + 1 >= $1::int THEN 'dead_letter' ELSE 'pending' END,
	attempts = attempts + 1, next_attempt_at = $2::timestamptz,
	locked_until = NULL, last_error = $3
WHERE id = $4
`

type RetryReconciliationNotificationParams struct {
	MaxAttempts   int32
	NextAttemptAt time.Time
	LastError     string
	ID            string
}

func (q *Queries) RetryReconciliationNotification(ctx context.Context, arg RetryReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, retryReconciliationNotification,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const saveQuotaCounterRepairRun = `-- name: SaveQuotaCounterRepairRun :exec
INSERT INTO quota_counter_repair_runs (
	id, workspace_id, subject, meter_name, period, period_start, period_end,
	dry_run, applied, before_snapshot, after_snapshot, counter_updated_at, created_at
) VALUES (
	$1, $2, $3, $4,
	$5, $6, $7, $8,
	$9, $10, $11,
	$12, $13
)
`

type SaveQuotaCounterRepairRunParams struct {
	ID               string
	WorkspaceID      string
	Subject          string
	MeterName        string
	Period           string
	PeriodStart      string
	PeriodEnd        string
	DryRun           bool
	Applied          bool
	BeforeSnapshot   json.RawMessage
	AfterSnapshot    json.RawMessage
	CounterUpdatedAt string
	CreatedAt        time.Time
}

func (q *Queries) SaveQuotaCounterRepairRun(ctx context.Context, arg SaveQuotaCounterRepairRunParams) error {
	_, err := q.db.ExecContext(ctx, saveQuotaCounterRepairRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DryRun,
		arg.Applied,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
		arg.CounterUpdatedAt,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationNotification = `-- name: SaveReconciliationNotification :exec
INSERT INTO reconciliation_notifications (
	id, workspace_id, event_type, fingerprint, payload, status,
	attempts, next_attempt_at, created_at
) VALUES (
	$1, $2, $3, $4,
	$5, 'pending', 0, $6, $7
)
`

type SaveReconciliationNotificationParams struct {
	ID            string
	WorkspaceID   string
	EventType     string
	Fingerprint   string
	Payload       json.RawMessage
	NextAttemptAt time.Time
	CreatedAt     time.Time
}

func (q *Queries) SaveReconciliationNotification(ctx context.Context, arg SaveReconciliationNotificationParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationNotification,
		arg.ID,
		arg.WorkspaceID,
		arg.EventType,
		arg.Fingerprint,
		arg.Payload,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationNotificationAttempt = `-- name: SaveReconciliationNotificationAttempt :exec
INSERT INTO reconciliation_notification_attempts (id, notification_id, attempt, status, error, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveReconciliationNotificationAttemptParams struct {
	ID             string
	NotificationID string
	Attempt        int32
	Status         string
	Error          string
	CreatedAt      time.Time
}

func (q *Queries) SaveReconciliationNotificationAttempt(ctx context.Context, arg SaveReconciliationNotificationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationNotificationAttempt,
		arg.ID,
		arg.NotificationID,
		arg.Attempt,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const saveReconciliationRun = `-- name: SaveReconciliationRun :exec
INSERT INTO reconciliation_runs (
	id, workspace_id, status, decisions_checked, counters_checked, issue_count,
	truncated, lookback_hours, duration_ms, fingerprint, issues, error, created_at
) VALUES (
	$1, $2, $3,
	$4, $5, $6,
	$7, $8, $9,
	$10, $11, $12, $13
)
`

type SaveReconciliationRunParams struct {
	ID               string
	WorkspaceID      string
	Status           string
	DecisionsChecked int32
	CountersChecked  int32
	IssueCount       int32
	Truncated        bool
	LookbackHours    int32
	DurationMs       int64
	Fingerprint      string
	Issues           json.RawMessage
	Error            string
	CreatedAt        time.Time
}

func (q *Queries) SaveReconciliationRun(ctx context.Context, arg SaveReconciliationRunParams) error {
	_, err := q.db.ExecContext(ctx, saveReconciliationRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.DecisionsChecked,
		arg.CountersChecked,
		arg.IssueCount,
		arg.Truncated,
		arg.LookbackHours,
		arg.DurationMs,
		arg.Fingerprint,
		arg.Issues,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const updateEntitlementCounterForRepair = `-- name: UpdateEntitlementCounterForRepair :execrows
UPDATE entitlement_usage_counters SET
	event_count = $1, quantity_sum = $2,
	quantity_min = $3, quantity_max = $4,
	first_quantity = $5, first_event_time = $6,
	last_quantity = $7, last_event_time = $8,
	updated_at = $9
WHERE workspace_id = $10::text
	AND subject = $11::text
	AND meter_name = $12::text
	AND period = $13::text
	AND period_start = $14::text
	AND updated_at = $15::text
`

type UpdateEntitlementCounterForRepairParams struct {
	EventCount        int64
	QuantitySum       float64
	QuantityMin       float64
	QuantityMax       float64
	FirstQuantity     float64
	FirstEventTime    string
	LastQuantity      float64
	LastEventTime     string
	UpdatedAt         string
	WorkspaceID       string
	Subject           string
	MeterName         string
	Period            string
	PeriodStart       string
	ExpectedUpdatedAt string
}

func (q *Queries) UpdateEntitlementCounterForRepair(ctx context.Context, arg UpdateEntitlementCounterForRepairParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntitlementCounterForRepair,
		arg.EventCount,
		arg.QuantitySum,
		arg.QuantityMin,
		arg.QuantityMax,
		arg.FirstQuantity,
		arg.FirstEventTime,
		arg.LastQuantity,
		arg.LastEventTime,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.Subject,
		arg.MeterName,
		arg.Period,
		arg.PeriodStart,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO system_worker_heartbeats (worker_name, started_at, last_heartbeat_at)
VALUES ($1, $2, $3)
ON CONFLICT(worker_name) DO UPDATE SET started_at = EXCLUDED.started_at, last_heartbeat_at = EXCLUDED.last_heartbeat_at
`

type UpsertWorkerHeartbeatParams struct {
	WorkerName      string
	StartedAt       time.Time
	LastHeartbeatAt time.Time
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkerHeartbeat, arg.WorkerName, arg.StartedAt, arg.LastHeartbeatAt)
	return err
}
