// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_runs.sql

package postgresdb

import (
	"context"
	"database/sql"
)

const claimUsageExportJob = `-- name: ClaimUsageExportJob :one
WITH next_job AS (
	SELECT id
	FROM usage_export_jobs
	WHERE (status = 'queued'
		OR (status = 'running' AND locked_until IS NOT NULL AND locked_until < $2::text))
		AND usage_export_jobs.attempts < $3::int
	ORDER BY created_at ASC, id ASC
	FOR UPDATE SKIP LOCKED
	LIMIT 1
)
UPDATE usage_export_jobs
SET status = 'running',
	attempts = usage_export_jobs.attempts + 1,
	locked_until = $1::text,
	error = '',
	updated_at = $2::text
WHERE id = (SELECT id FROM next_job)
RETURNING id, kind, status, format, query_json, error, attempts, locked_until, artifact_path, artifact_size, created_at, updated_at, completed_at
`

type ClaimUsageExportJobParams struct {
	LockedUntil string
	Now         string
	MaxAttempts int32
}

type ClaimUsageExportJobRow struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) ClaimUsageExportJob(ctx context.Context, arg ClaimUsageExportJobParams) (ClaimUsageExportJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimUsageExportJob, arg.LockedUntil, arg.Now, arg.MaxAttempts)
	var i ClaimUsageExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Format,
		&i.QueryJson,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.ArtifactPath,
		&i.ArtifactSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeUsageExportJob = `-- name: CompleteUsageExportJob :one
UPDATE usage_export_jobs
SET status = 'completed',
	artifact_path = $1::text,
	artifact_size = $2::bigint,
	locked_until = NULL,
	error = '',
	updated_at = $3::text,
	completed_at = $3::text
WHERE id = $4::text
RETURNING id, kind, status, format, query_json, error, attempts, locked_until, artifact_path, artifact_size, created_at, updated_at, completed_at
`

type CompleteUsageExportJobParams struct {
	ArtifactPath string
	ArtifactSize int64
	CompletedAt  string
	ID           string
}

type CompleteUsageExportJobRow struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) CompleteUsageExportJob(ctx context.Context, arg CompleteUsageExportJobParams) (CompleteUsageExportJobRow, error) {
	row := q.db.QueryRowContext(ctx, completeUsageExportJob,
		arg.ArtifactPath,
		arg.ArtifactSize,
		arg.CompletedAt,
		arg.ID,
	)
	var i CompleteUsageExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Format,
		&i.QueryJson,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.ArtifactPath,
		&i.ArtifactSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countPrunableUsageEvents = `-- name: CountPrunableUsageEvents :one
SELECT COUNT(*)
FROM usage_events
WHERE meter_name = $1
	AND event_time < $2
`

type CountPrunableUsageEventsParams struct {
	MeterName string
	EventTime string
}

func (q *Queries) CountPrunableUsageEvents(ctx context.Context, arg CountPrunableUsageEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableUsageEvents, arg.MeterName, arg.EventTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsagePruneRuns = `-- name: CountUsagePruneRuns :one
SELECT COUNT(*)
FROM usage_prune_runs
`

func (q *Queries) CountUsagePruneRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsagePruneRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failUsageExportJob = `-- name: FailUsageExportJob :one
UPDATE usage_export_jobs
SET status = 'failed',
	error = $1::text,
	locked_until = NULL,
	updated_at = $2::text,
	completed_at = $2::text
WHERE id = $3::text
RETURNING id, kind, status, format, query_json, error, attempts, locked_until, artifact_path, artifact_size, created_at, updated_at, completed_at
`

type FailUsageExportJobParams struct {
	Error    string
	FailedAt string
	ID       string
}

type FailUsageExportJobRow struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) FailUsageExportJob(ctx context.Context, arg FailUsageExportJobParams) (FailUsageExportJobRow, error) {
	row := q.db.QueryRowContext(ctx, failUsageExportJob, arg.Error, arg.FailedAt, arg.ID)
	var i FailUsageExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Format,
		&i.QueryJson,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.ArtifactPath,
		&i.ArtifactSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const findUsageExportJob = `-- name: FindUsageExportJob :one
SELECT id, kind, status, format, query_json, error, attempts, locked_until, artifact_path, artifact_size, created_at, updated_at, completed_at
FROM usage_export_jobs
WHERE id = $1
`

type FindUsageExportJobRow struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) FindUsageExportJob(ctx context.Context, id string) (FindUsageExportJobRow, error) {
	row := q.db.QueryRowContext(ctx, findUsageExportJob, id)
	var i FindUsageExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Format,
		&i.QueryJson,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.ArtifactPath,
		&i.ArtifactSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listUsageExportJobs = `-- name: ListUsageExportJobs :many
SELECT id, kind, status, format, query_json, error, attempts, locked_until, artifact_path, artifact_size, created_at, updated_at, completed_at
FROM usage_export_jobs
WHERE ($1::text IS NULL
	OR (created_at < $1::text
		OR (created_at = $1::text AND id < $2::text)))
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListUsageExportJobsParams struct {
	CursorCreatedAt sql.NullString
	CursorID        sql.NullString
	Limit           int32
}

type ListUsageExportJobsRow struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) ListUsageExportJobs(ctx context.Context, arg ListUsageExportJobsParams) ([]ListUsageExportJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageExportJobs, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageExportJobsRow{}
	for rows.Next() {
		var i ListUsageExportJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Format,
			&i.QueryJson,
			&i.Error,
			&i.Attempts,
			&i.LockedUntil,
			&i.ArtifactPath,
			&i.ArtifactSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageIngestionRuns = `-- name: ListUsageIngestionRuns :many
SELECT id, kind, accepted, duplicates, failed, created_at
FROM usage_ingestions
WHERE ($1::text IS NULL
	OR (created_at < $1::text
		OR (created_at = $1::text AND id < $2::text)))
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListUsageIngestionRunsParams struct {
	CursorCreatedAt sql.NullString
	CursorID        sql.NullString
	Limit           int32
}

func (q *Queries) ListUsageIngestionRuns(ctx context.Context, arg ListUsageIngestionRunsParams) ([]UsageIngestion, error) {
	rows, err := q.db.QueryContext(ctx, listUsageIngestionRuns, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageIngestion{}
	for rows.Next() {
		var i UsageIngestion
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Accepted,
			&i.Duplicates,
			&i.Failed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsagePruneRuns = `-- name: ListUsagePruneRuns :many
SELECT id, dry_run, deleted, meters, created_at
FROM usage_prune_runs
WHERE ($1::text IS NULL
	OR (created_at < $1::text
		OR (created_at = $1::text AND id < $2::text)))
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListUsagePruneRunsParams struct {
	CursorCreatedAt sql.NullString
	CursorID        sql.NullString
	Limit           int32
}

func (q *Queries) ListUsagePruneRuns(ctx context.Context, arg ListUsagePruneRunsParams) ([]UsagePruneRun, error) {
	rows, err := q.db.QueryContext(ctx, listUsagePruneRuns, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsagePruneRun{}
	for rows.Next() {
		var i UsagePruneRun
		if err := rows.Scan(
			&i.ID,
			&i.DryRun,
			&i.Deleted,
			&i.Meters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneUsageEventsBatch = `-- name: PruneUsageEventsBatch :execrows
WITH deleted AS (
	SELECT usage_events.id
	FROM usage_events
	WHERE usage_events.meter_name = $1
		AND usage_events.event_time < $2
	ORDER BY usage_events.event_time ASC, usage_events.id ASC
	LIMIT $3
)
DELETE FROM usage_events
WHERE usage_events.id IN (SELECT deleted.id FROM deleted)
`

type PruneUsageEventsBatchParams struct {
	MeterName string
	EventTime string
	Limit     int32
}

func (q *Queries) PruneUsageEventsBatch(ctx context.Context, arg PruneUsageEventsBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneUsageEventsBatch, arg.MeterName, arg.EventTime, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveUsageExportJob = `-- name: SaveUsageExportJob :exec
INSERT INTO usage_export_jobs (
	id,
	kind,
	status,
	format,
	query_json,
	error,
	attempts,
	locked_until,
	artifact_path,
	artifact_size,
	created_at,
	updated_at,
	completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type SaveUsageExportJobParams struct {
	ID           string
	Kind         string
	Status       string
	Format       string
	QueryJson    string
	Error        string
	Attempts     int32
	LockedUntil  sql.NullString
	ArtifactPath string
	ArtifactSize int64
	CreatedAt    string
	UpdatedAt    string
	CompletedAt  sql.NullString
}

func (q *Queries) SaveUsageExportJob(ctx context.Context, arg SaveUsageExportJobParams) error {
	_, err := q.db.ExecContext(ctx, saveUsageExportJob,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.Format,
		arg.QueryJson,
		arg.Error,
		arg.Attempts,
		arg.LockedUntil,
		arg.ArtifactPath,
		arg.ArtifactSize,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}

const saveUsageIngestionRun = `-- name: SaveUsageIngestionRun :exec
INSERT INTO usage_ingestions (id, kind, accepted, duplicates, failed, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveUsageIngestionRunParams struct {
	ID         string
	Kind       string
	Accepted   int32
	Duplicates int32
	Failed     int32
	CreatedAt  string
}

func (q *Queries) SaveUsageIngestionRun(ctx context.Context, arg SaveUsageIngestionRunParams) error {
	_, err := q.db.ExecContext(ctx, saveUsageIngestionRun,
		arg.ID,
		arg.Kind,
		arg.Accepted,
		arg.Duplicates,
		arg.Failed,
		arg.CreatedAt,
	)
	return err
}

const saveUsagePruneRun = `-- name: SaveUsagePruneRun :exec
INSERT INTO usage_prune_runs (id, dry_run, deleted, meters, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveUsagePruneRunParams struct {
	ID        string
	DryRun    int32
	Deleted   int32
	Meters    string
	CreatedAt string
}

func (q *Queries) SaveUsagePruneRun(ctx context.Context, arg SaveUsagePruneRunParams) error {
	_, err := q.db.ExecContext(ctx, saveUsagePruneRun,
		arg.ID,
		arg.DryRun,
		arg.Deleted,
		arg.Meters,
		arg.CreatedAt,
	)
	return err
}

const tryPruneLock = `-- name: TryPruneLock :one
SELECT pg_try_advisory_xact_lock($1)
`

func (q *Queries) TryPruneLock(ctx context.Context, pgTryAdvisoryXactLock int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, tryPruneLock, pgTryAdvisoryXactLock)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
