// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_ingestion.sql

package postgresdb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const findBulkUsageIngestion = `-- name: FindBulkUsageIngestion :one
SELECT response
FROM bulk_usage_ingestions
WHERE workspace_id = $1::text
	AND idempotency_key = $2::text
`

type FindBulkUsageIngestionParams struct {
	WorkspaceID    string
	IdempotencyKey string
}

func (q *Queries) FindBulkUsageIngestion(ctx context.Context, arg FindBulkUsageIngestionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findBulkUsageIngestion, arg.WorkspaceID, arg.IdempotencyKey)
	var response string
	err := row.Scan(&response)
	return response, err
}

const findUsageEventByID = `-- name: FindUsageEventByID :one
SELECT id, idempotency_key, subject, meter_name, quantity, event_time, received_at, metadata
FROM usage_events
WHERE workspace_id = $1::text
	AND id = $2::text
`

type FindUsageEventByIDParams struct {
	WorkspaceID string
	ID          string
}

type FindUsageEventByIDRow struct {
	ID             string
	IdempotencyKey sql.NullString
	Subject        string
	MeterName      string
	Quantity       float64
	EventTime      string
	ReceivedAt     string
	Metadata       json.RawMessage
}

func (q *Queries) FindUsageEventByID(ctx context.Context, arg FindUsageEventByIDParams) (FindUsageEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findUsageEventByID, arg.WorkspaceID, arg.ID)
	var i FindUsageEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Subject,
		&i.MeterName,
		&i.Quantity,
		&i.EventTime,
		&i.ReceivedAt,
		&i.Metadata,
	)
	return i, err
}

const findUsageEventByIdempotencyKey = `-- name: FindUsageEventByIdempotencyKey :one
SELECT id, idempotency_key, subject, meter_name, quantity, event_time, received_at, metadata
FROM usage_events
WHERE workspace_id = $1::text
	AND idempotency_key = $2::text
`

type FindUsageEventByIdempotencyKeyParams struct {
	WorkspaceID    string
	IdempotencyKey string
}

type FindUsageEventByIdempotencyKeyRow struct {
	ID             string
	IdempotencyKey sql.NullString
	Subject        string
	MeterName      string
	Quantity       float64
	EventTime      string
	ReceivedAt     string
	Metadata       json.RawMessage
}

func (q *Queries) FindUsageEventByIdempotencyKey(ctx context.Context, arg FindUsageEventByIdempotencyKeyParams) (FindUsageEventByIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, findUsageEventByIdempotencyKey, arg.WorkspaceID, arg.IdempotencyKey)
	var i FindUsageEventByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Subject,
		&i.MeterName,
		&i.Quantity,
		&i.EventTime,
		&i.ReceivedAt,
		&i.Metadata,
	)
	return i, err
}

const saveBulkUsageIngestion = `-- name: SaveBulkUsageIngestion :exec
INSERT INTO bulk_usage_ingestions (workspace_id, idempotency_key, response, created_at)
VALUES ($1, $2, $3, $4)
`

type SaveBulkUsageIngestionParams struct {
	WorkspaceID    string
	IdempotencyKey string
	Response       string
	CreatedAt      string
}

func (q *Queries) SaveBulkUsageIngestion(ctx context.Context, arg SaveBulkUsageIngestionParams) error {
	_, err := q.db.ExecContext(ctx, saveBulkUsageIngestion,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const saveUsageEvent = `-- name: SaveUsageEvent :exec
INSERT INTO usage_events (
	id,
	workspace_id,
	idempotency_key,
	subject,
	meter_name,
	quantity,
	event_time,
	received_at,
	metadata
) VALUES (
	$1,
	$2,
	NULLIF($3::text, ''),
	$4,
	$5,
	$6,
	$7,
	$8,
	$9::jsonb
)
`

type SaveUsageEventParams struct {
	ID             string
	WorkspaceID    string
	IdempotencyKey string
	Subject        string
	MeterName      string
	Quantity       float64
	EventTime      string
	ReceivedAt     string
	Metadata       json.RawMessage
}

func (q *Queries) SaveUsageEvent(ctx context.Context, arg SaveUsageEventParams) error {
	_, err := q.db.ExecContext(ctx, saveUsageEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.Subject,
		arg.MeterName,
		arg.Quantity,
		arg.EventTime,
		arg.ReceivedAt,
		arg.Metadata,
	)
	return err
}
