// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_breakdowns.sql

package postgresdb

import (
	"context"
	"database/sql"
)

const listUsageBreakdown = `-- name: ListUsageBreakdown :many
WITH filtered AS (
	SELECT
		(CASE
			WHEN $4::text = 'subject' THEN subject
			ELSE metadata #>> string_to_array($4::text, '.')
		END)::text AS value,
		quantity,
		event_time::timestamptz AS event_at
	FROM usage_events
	WHERE workspace_id = $5::text
		AND meter_name = $6
		AND event_time >= $7::text
		AND event_time < $8::text
		AND ($9::text IS NULL OR subject = $9::text)
)
SELECT
	value,
	(CASE $1::text
		WHEN 'count' THEN COUNT(*)::double precision
		WHEN 'avg' THEN AVG(quantity)
		WHEN 'min' THEN MIN(quantity)
		WHEN 'max' THEN MAX(quantity)
		WHEN 'first' THEN (array_agg(quantity ORDER BY event_at ASC))[1]
		WHEN 'last' THEN (array_agg(quantity ORDER BY event_at DESC))[1]
		WHEN 'rate' THEN COUNT(*)::double precision / $2::double precision
		ELSE SUM(quantity)
	END)::double precision AS quantity,
	COUNT(*)::bigint AS usage_events
FROM filtered
WHERE value IS NOT NULL AND value != ''
GROUP BY value
ORDER BY quantity DESC, value ASC
LIMIT $3::int
`

type ListUsageBreakdownParams struct {
	Aggregation     string
	DurationSeconds float64
	Limit           int32
	Field           string
	WorkspaceID     string
	MeterName       string
	FromTime        string
	ToTime          string
	Subject         sql.NullString
}

type ListUsageBreakdownRow struct {
	Value       string
	Quantity    float64
	UsageEvents int64
}

func (q *Queries) ListUsageBreakdown(ctx context.Context, arg ListUsageBreakdownParams) ([]ListUsageBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageBreakdown,
		arg.Aggregation,
		arg.DurationSeconds,
		arg.Limit,
		arg.Field,
		arg.WorkspaceID,
		arg.MeterName,
		arg.FromTime,
		arg.ToTime,
		arg.Subject,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageBreakdownRow{}
	for rows.Next() {
		var i ListUsageBreakdownRow
		if err := rows.Scan(&i.Value, &i.Quantity, &i.UsageEvents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
