// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: open_spanner/v1/usage.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace OpenSpanner.Grpc.V1 {
  public static partial class UsageService
  {
    static readonly string __ServiceName = "open_spanner.v1.UsageService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.CreateUsageRequest> __Marshaller_open_spanner_v1_CreateUsageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.CreateUsageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.CreateUsageResponse> __Marshaller_open_spanner_v1_CreateUsageResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.CreateUsageResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest> __Marshaller_open_spanner_v1_CreateUsageBulkRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse> __Marshaller_open_spanner_v1_CreateUsageBulkResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.StreamUsageRequest> __Marshaller_open_spanner_v1_StreamUsageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.StreamUsageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OpenSpanner.Grpc.V1.StreamUsageResponse> __Marshaller_open_spanner_v1_StreamUsageResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OpenSpanner.Grpc.V1.StreamUsageResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::OpenSpanner.Grpc.V1.CreateUsageRequest, global::OpenSpanner.Grpc.V1.CreateUsageResponse> __Method_CreateUsage = new grpc::Method<global::OpenSpanner.Grpc.V1.CreateUsageRequest, global::OpenSpanner.Grpc.V1.CreateUsageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateUsage",
        __Marshaller_open_spanner_v1_CreateUsageRequest,
        __Marshaller_open_spanner_v1_CreateUsageResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest, global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse> __Method_CreateUsageBulk = new grpc::Method<global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest, global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateUsageBulk",
        __Marshaller_open_spanner_v1_CreateUsageBulkRequest,
        __Marshaller_open_spanner_v1_CreateUsageBulkResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::OpenSpanner.Grpc.V1.StreamUsageRequest, global::OpenSpanner.Grpc.V1.StreamUsageResponse> __Method_StreamUsage = new grpc::Method<global::OpenSpanner.Grpc.V1.StreamUsageRequest, global::OpenSpanner.Grpc.V1.StreamUsageResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "StreamUsage",
        __Marshaller_open_spanner_v1_StreamUsageRequest,
        __Marshaller_open_spanner_v1_StreamUsageResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::OpenSpanner.Grpc.V1.UsageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UsageService</summary>
    [grpc::BindServiceMethod(typeof(UsageService), "BindService")]
    public abstract partial class UsageServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::OpenSpanner.Grpc.V1.CreateUsageResponse> CreateUsage(global::OpenSpanner.Grpc.V1.CreateUsageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse> CreateUsageBulk(global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::OpenSpanner.Grpc.V1.StreamUsageResponse> StreamUsage(grpc::IAsyncStreamReader<global::OpenSpanner.Grpc.V1.StreamUsageRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UsageService</summary>
    public partial class UsageServiceClient : grpc::ClientBase<UsageServiceClient>
    {
      /// <summary>Creates a new client for UsageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UsageServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UsageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UsageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UsageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UsageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OpenSpanner.Grpc.V1.CreateUsageResponse CreateUsage(global::OpenSpanner.Grpc.V1.CreateUsageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUsage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OpenSpanner.Grpc.V1.CreateUsageResponse CreateUsage(global::OpenSpanner.Grpc.V1.CreateUsageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateUsage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OpenSpanner.Grpc.V1.CreateUsageResponse> CreateUsageAsync(global::OpenSpanner.Grpc.V1.CreateUsageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUsageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OpenSpanner.Grpc.V1.CreateUsageResponse> CreateUsageAsync(global::OpenSpanner.Grpc.V1.CreateUsageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateUsage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse CreateUsageBulk(global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUsageBulk(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse CreateUsageBulk(global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateUsageBulk, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse> CreateUsageBulkAsync(global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUsageBulkAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse> CreateUsageBulkAsync(global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateUsageBulk, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::OpenSpanner.Grpc.V1.StreamUsageRequest, global::OpenSpanner.Grpc.V1.StreamUsageResponse> StreamUsage(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamUsage(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::OpenSpanner.Grpc.V1.StreamUsageRequest, global::OpenSpanner.Grpc.V1.StreamUsageResponse> StreamUsage(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_StreamUsage, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override UsageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UsageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(UsageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateUsage, serviceImpl.CreateUsage)
          .AddMethod(__Method_CreateUsageBulk, serviceImpl.CreateUsageBulk)
          .AddMethod(__Method_StreamUsage, serviceImpl.StreamUsage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UsageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateUsage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::OpenSpanner.Grpc.V1.CreateUsageRequest, global::OpenSpanner.Grpc.V1.CreateUsageResponse>(serviceImpl.CreateUsage));
      serviceBinder.AddMethod(__Method_CreateUsageBulk, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::OpenSpanner.Grpc.V1.CreateUsageBulkRequest, global::OpenSpanner.Grpc.V1.CreateUsageBulkResponse>(serviceImpl.CreateUsageBulk));
      serviceBinder.AddMethod(__Method_StreamUsage, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::OpenSpanner.Grpc.V1.StreamUsageRequest, global::OpenSpanner.Grpc.V1.StreamUsageResponse>(serviceImpl.StreamUsage));
    }

  }
}
#endregion
