// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OpenSpanner.Models;
using OpenSpanner.V1.Usages.Bulk;
using OpenSpanner.V1.Usages.Export;
using OpenSpanner.V1.Usages.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OpenSpanner.V1.Usages
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\usages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::OpenSpanner.V1.Usages.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::OpenSpanner.V1.Usages.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export property</summary>
        public global::OpenSpanner.V1.Usages.Export.ExportRequestBuilder Export
        {
            get => new global::OpenSpanner.V1.Usages.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::OpenSpanner.V1.Usages.Search.SearchRequestBuilder Search
        {
            get => new global::OpenSpanner.V1.Usages.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Usages.UsagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/usages{?bucket_size*,group_by*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Usages.UsagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/usages{?bucket_size*,group_by*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// List usage buckets
        /// </summary>
        /// <returns>A List&lt;global::OpenSpanner.Models.UsageBucket&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::OpenSpanner.Models.UsageBucket>?> GetAsync(Action<RequestConfiguration<global::OpenSpanner.V1.Usages.UsagesRequestBuilder.UsagesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::OpenSpanner.Models.UsageBucket>> GetAsync(Action<RequestConfiguration<global::OpenSpanner.V1.Usages.UsagesRequestBuilder.UsagesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::OpenSpanner.Models.UsageBucket>(requestInfo, global::OpenSpanner.Models.UsageBucket.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create usage
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.Models.UsageEvent"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OpenSpanner.Models.UsageEvent?> PostAsync(global::OpenSpanner.Models.UsageCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OpenSpanner.Models.UsageEvent> PostAsync(global::OpenSpanner.Models.UsageCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OpenSpanner.Models.UsageEvent>(requestInfo, global::OpenSpanner.Models.UsageEvent.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List usage buckets
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenSpanner.V1.Usages.UsagesRequestBuilder.UsagesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenSpanner.V1.Usages.UsagesRequestBuilder.UsagesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/v1/usages?from={from}&meter={meter}&subject={subject}&to={to}{&bucket_size*,group_by*,limit*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create usage
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::OpenSpanner.Models.UsageCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::OpenSpanner.Models.UsageCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.V1.Usages.UsagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OpenSpanner.V1.Usages.UsagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OpenSpanner.V1.Usages.UsagesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List usage buckets
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsagesRequestBuilderGetQueryParameters 
        {
            /// <summary>Bucket size: hour, day, month</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bucket_size")]
            public string? BucketSize { get; set; }
#nullable restore
#else
            [QueryParameter("bucket_size")]
            public string BucketSize { get; set; }
#endif
            /// <summary>RFC3339 start time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("from")]
            public string? From { get; set; }
#nullable restore
#else
            [QueryParameter("from")]
            public string From { get; set; }
#endif
            /// <summary>Metadata key to group by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("group_by")]
            public string? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("group_by")]
            public string GroupBy { get; set; }
#endif
            /// <summary>Result limit</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Meter name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("meter")]
            public string? Meter { get; set; }
#nullable restore
#else
            [QueryParameter("meter")]
            public string Meter { get; set; }
#endif
            /// <summary>Subject</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject")]
            public string? Subject { get; set; }
#nullable restore
#else
            [QueryParameter("subject")]
            public string Subject { get; set; }
#endif
            /// <summary>RFC3339 end time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("to")]
            public string? To { get; set; }
#nullable restore
#else
            [QueryParameter("to")]
            public string To { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
