/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUsageRouteRouteImport } from './routes/_dashboard/usage/route'
import { Route as DashboardOverviewRouteRouteImport } from './routes/_dashboard/overview/route'
import { Route as DashboardMetersRouteRouteImport } from './routes/_dashboard/meters/route'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsageRouteRoute = DashboardUsageRouteRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOverviewRouteRoute = DashboardOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMetersRouteRoute = DashboardMetersRouteRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/meters': typeof DashboardMetersRouteRoute
  '/overview': typeof DashboardOverviewRouteRoute
  '/usage': typeof DashboardUsageRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/meters': typeof DashboardMetersRouteRoute
  '/overview': typeof DashboardOverviewRouteRoute
  '/usage': typeof DashboardUsageRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_dashboard/meters': typeof DashboardMetersRouteRoute
  '/_dashboard/overview': typeof DashboardOverviewRouteRoute
  '/_dashboard/usage': typeof DashboardUsageRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/meters' | '/overview' | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/meters' | '/overview' | '/usage'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/meters'
    | '/_dashboard/overview'
    | '/_dashboard/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/usage': {
      id: '/_dashboard/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof DashboardUsageRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/meters': {
      id: '/_dashboard/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof DashboardMetersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardMetersRouteRoute: typeof DashboardMetersRouteRoute
  DashboardOverviewRouteRoute: typeof DashboardOverviewRouteRoute
  DashboardUsageRouteRoute: typeof DashboardUsageRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMetersRouteRoute: DashboardMetersRouteRoute,
  DashboardOverviewRouteRoute: DashboardOverviewRouteRoute,
  DashboardUsageRouteRoute: DashboardUsageRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
