// Code generated by go-swagger; DO NOT EDIT.

package usage_events

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewExportUsageEventsParams creates a new ExportUsageEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportUsageEventsParams() *ExportUsageEventsParams {
	return NewExportUsageEventsParamsWithTimeout(cr.DefaultTimeout)
}

// NewExportUsageEventsParamsWithTimeout creates a new ExportUsageEventsParams object
// with the ability to set a timeout on a request.
func NewExportUsageEventsParamsWithTimeout(timeout time.Duration) *ExportUsageEventsParams {
	return &ExportUsageEventsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewExportUsageEventsParamsWithContext creates a new ExportUsageEventsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ExportUsageEventsParams].
func NewExportUsageEventsParamsWithContext(ctx context.Context) *ExportUsageEventsParams {
	return &ExportUsageEventsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewExportUsageEventsParamsWithHTTPClient creates a new ExportUsageEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportUsageEventsParamsWithHTTPClient(client *http.Client) *ExportUsageEventsParams {
	return &ExportUsageEventsParams{
		HTTPClient: client,
	}
}

/*
ExportUsageEventsParams contains all the parameters to send to the API endpoint

	for the export usage events operation.

	Typically these are written to a http.Request.
*/
type ExportUsageEventsParams struct {

	/* From.

	   RFC3339 start time
	*/
	From *string

	/* Limit.

	   Result limit
	*/
	Limit *int64

	/* Meter.

	   Meter name
	*/
	Meter *string

	/* Subject.

	   Subject
	*/
	Subject *string

	/* To.

	   RFC3339 end time
	*/
	To *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the export usage events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportUsageEventsParams) WithDefaults() *ExportUsageEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export usage events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportUsageEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export usage events params.
func (o *ExportUsageEventsParams) WithTimeout(timeout time.Duration) *ExportUsageEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export usage events params.
func (o *ExportUsageEventsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the export usage events params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExportUsageEventsParams].
func (o *ExportUsageEventsParams) WithContext(ctx context.Context) *ExportUsageEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export usage events params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExportUsageEventsParams].
func (o *ExportUsageEventsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the export usage events params.
func (o *ExportUsageEventsParams) WithHTTPClient(client *http.Client) *ExportUsageEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export usage events params.
func (o *ExportUsageEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the export usage events params.
func (o *ExportUsageEventsParams) WithFrom(from *string) *ExportUsageEventsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the export usage events params.
func (o *ExportUsageEventsParams) SetFrom(from *string) {
	o.From = from
}

// WithLimit adds the limit to the export usage events params.
func (o *ExportUsageEventsParams) WithLimit(limit *int64) *ExportUsageEventsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the export usage events params.
func (o *ExportUsageEventsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithMeter adds the meter to the export usage events params.
func (o *ExportUsageEventsParams) WithMeter(meter *string) *ExportUsageEventsParams {
	o.SetMeter(meter)
	return o
}

// SetMeter adds the meter to the export usage events params.
func (o *ExportUsageEventsParams) SetMeter(meter *string) {
	o.Meter = meter
}

// WithSubject adds the subject to the export usage events params.
func (o *ExportUsageEventsParams) WithSubject(subject *string) *ExportUsageEventsParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the export usage events params.
func (o *ExportUsageEventsParams) SetSubject(subject *string) {
	o.Subject = subject
}

// WithTo adds the to to the export usage events params.
func (o *ExportUsageEventsParams) WithTo(to *string) *ExportUsageEventsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the export usage events params.
func (o *ExportUsageEventsParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ExportUsageEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Meter != nil {

		// query param meter
		var qrMeter string

		if o.Meter != nil {
			qrMeter = *o.Meter
		}
		qMeter := qrMeter
		if qMeter != "" {

			if err := r.SetQueryParam("meter", qMeter); err != nil {
				return err
			}
		}
	}

	if o.Subject != nil {

		// query param subject
		var qrSubject string

		if o.Subject != nil {
			qrSubject = *o.Subject
		}
		qSubject := qrSubject
		if qSubject != "" {

			if err := r.SetQueryParam("subject", qSubject); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
