// Code generated by go-swagger; DO NOT EDIT.

package usage_events

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// SearchUsageEventsReader is a Reader for the SearchUsageEvents structure.
type SearchUsageEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchUsageEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSearchUsageEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchUsageEventsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSearchUsageEventsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/usageevents/search] searchUsageEvents", response, response.Code())
	}
}

// NewSearchUsageEventsOK creates a SearchUsageEventsOK with default headers values
func NewSearchUsageEventsOK() *SearchUsageEventsOK {
	return &SearchUsageEventsOK{}
}

/*
SearchUsageEventsOK describes a response with status code 200, with default header values.

OK
*/
type SearchUsageEventsOK struct {
	Payload *models.UsageEventListResponse
}

// IsSuccess returns true when this search usage events o k response has a 2xx status code
func (o *SearchUsageEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search usage events o k response has a 3xx status code
func (o *SearchUsageEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search usage events o k response has a 4xx status code
func (o *SearchUsageEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search usage events o k response has a 5xx status code
func (o *SearchUsageEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search usage events o k response a status code equal to that given
func (o *SearchUsageEventsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search usage events o k response
func (o *SearchUsageEventsOK) Code() int {
	return 200
}

func (o *SearchUsageEventsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsOK %s", 200, payload)
}

func (o *SearchUsageEventsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsOK %s", 200, payload)
}

func (o *SearchUsageEventsOK) GetPayload() *models.UsageEventListResponse {
	return o.Payload
}

func (o *SearchUsageEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsageEventListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSearchUsageEventsBadRequest creates a SearchUsageEventsBadRequest with default headers values
func NewSearchUsageEventsBadRequest() *SearchUsageEventsBadRequest {
	return &SearchUsageEventsBadRequest{}
}

/*
SearchUsageEventsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SearchUsageEventsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this search usage events bad request response has a 2xx status code
func (o *SearchUsageEventsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search usage events bad request response has a 3xx status code
func (o *SearchUsageEventsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search usage events bad request response has a 4xx status code
func (o *SearchUsageEventsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this search usage events bad request response has a 5xx status code
func (o *SearchUsageEventsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this search usage events bad request response a status code equal to that given
func (o *SearchUsageEventsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the search usage events bad request response
func (o *SearchUsageEventsBadRequest) Code() int {
	return 400
}

func (o *SearchUsageEventsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsBadRequest %s", 400, payload)
}

func (o *SearchUsageEventsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsBadRequest %s", 400, payload)
}

func (o *SearchUsageEventsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SearchUsageEventsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSearchUsageEventsInternalServerError creates a SearchUsageEventsInternalServerError with default headers values
func NewSearchUsageEventsInternalServerError() *SearchUsageEventsInternalServerError {
	return &SearchUsageEventsInternalServerError{}
}

/*
SearchUsageEventsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SearchUsageEventsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this search usage events internal server error response has a 2xx status code
func (o *SearchUsageEventsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search usage events internal server error response has a 3xx status code
func (o *SearchUsageEventsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search usage events internal server error response has a 4xx status code
func (o *SearchUsageEventsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this search usage events internal server error response has a 5xx status code
func (o *SearchUsageEventsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this search usage events internal server error response a status code equal to that given
func (o *SearchUsageEventsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the search usage events internal server error response
func (o *SearchUsageEventsInternalServerError) Code() int {
	return 500
}

func (o *SearchUsageEventsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsInternalServerError %s", 500, payload)
}

func (o *SearchUsageEventsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/usageevents/search][%d] searchUsageEventsInternalServerError %s", 500, payload)
}

func (o *SearchUsageEventsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SearchUsageEventsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
