// Code generated by go-swagger; DO NOT EDIT.

package usage_events

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/ssubedir/open-spanner/sdk/go/models"
)

// NewSearchUsageEventsParams creates a new SearchUsageEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchUsageEventsParams() *SearchUsageEventsParams {
	return NewSearchUsageEventsParamsWithTimeout(cr.DefaultTimeout)
}

// NewSearchUsageEventsParamsWithTimeout creates a new SearchUsageEventsParams object
// with the ability to set a timeout on a request.
func NewSearchUsageEventsParamsWithTimeout(timeout time.Duration) *SearchUsageEventsParams {
	return &SearchUsageEventsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewSearchUsageEventsParamsWithContext creates a new SearchUsageEventsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageEventsParams].
func NewSearchUsageEventsParamsWithContext(ctx context.Context) *SearchUsageEventsParams {
	return &SearchUsageEventsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewSearchUsageEventsParamsWithHTTPClient creates a new SearchUsageEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchUsageEventsParamsWithHTTPClient(client *http.Client) *SearchUsageEventsParams {
	return &SearchUsageEventsParams{
		HTTPClient: client,
	}
}

/*
SearchUsageEventsParams contains all the parameters to send to the API endpoint

	for the search usage events operation.

	Typically these are written to a http.Request.
*/
type SearchUsageEventsParams struct {

	/* Request.

	   Usage event search
	*/
	Request *models.InternalMeteringAdaptersHTTPUsageEventSearchRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the search usage events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageEventsParams) WithDefaults() *SearchUsageEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search usage events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUsageEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search usage events params.
func (o *SearchUsageEventsParams) WithTimeout(timeout time.Duration) *SearchUsageEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search usage events params.
func (o *SearchUsageEventsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the search usage events params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageEventsParams].
func (o *SearchUsageEventsParams) WithContext(ctx context.Context) *SearchUsageEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search usage events params.
//
// Deprecated: use the operation call with context to pass the context instead of [SearchUsageEventsParams].
func (o *SearchUsageEventsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the search usage events params.
func (o *SearchUsageEventsParams) WithHTTPClient(client *http.Client) *SearchUsageEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search usage events params.
func (o *SearchUsageEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the search usage events params.
func (o *SearchUsageEventsParams) WithRequest(request *models.InternalMeteringAdaptersHTTPUsageEventSearchRequest) *SearchUsageEventsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the search usage events params.
func (o *SearchUsageEventsParams) SetRequest(request *models.InternalMeteringAdaptersHTTPUsageEventSearchRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *SearchUsageEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
