// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenSpanner.V1.Plans.Subjects.Item.Progress;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenSpanner.V1.Plans.Subjects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\plans\subjects\{subject}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSubjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The progress property</summary>
        public global::OpenSpanner.V1.Plans.Subjects.Item.Progress.ProgressRequestBuilder Progress
        {
            get => new global::OpenSpanner.V1.Plans.Subjects.Item.Progress.ProgressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Plans.Subjects.Item.WithSubjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/plans/subjects/{subject}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Plans.Subjects.Item.WithSubjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSubjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/plans/subjects/{subject}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
