// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OpenSpanner.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OpenSpanner.V1.Entitlements.States
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\entitlements\states
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/entitlements/states{?limit*,meter*,state*,subject*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/entitlements/states{?limit*,meter*,state*,subject*}", rawUrl)
        {
        }
        /// <summary>
        /// List entitlement states
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.Models.EntitlementStateListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::OpenSpanner.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OpenSpanner.Models.EntitlementStateListResponse?> GetAsync(Action<RequestConfiguration<global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder.StatesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OpenSpanner.Models.EntitlementStateListResponse> GetAsync(Action<RequestConfiguration<global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder.StatesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::OpenSpanner.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OpenSpanner.Models.EntitlementStateListResponse>(requestInfo, global::OpenSpanner.Models.EntitlementStateListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List entitlement states
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder.StatesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder.StatesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OpenSpanner.V1.Entitlements.States.StatesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List entitlement states
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StatesRequestBuilderGetQueryParameters
        {
            /// <summary>Page size</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Meter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("meter")]
            public string? Meter { get; set; }
#nullable restore
#else
            [QueryParameter("meter")]
            public string Meter { get; set; }
#endif
            /// <summary>State</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>Subject</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject")]
            public string? Subject { get; set; }
#nullable restore
#else
            [QueryParameter("subject")]
            public string Subject { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
